import { describe, expect, it, vi } from "vitest";
import { DEFAULT_EMBEDDING_DIMENSIONS, DeterministicFakeEmbeddingAdapter, MemoryEmbeddingCache, VercelAiGatewayEmbeddingAdapter, validateVector } from "./index.js";

const request = { vectorSpaceVersionId:"version-1", idempotencyKey:"embed-operation-1", expectedDimensions:3, inputs:[{projectionId:"a",text:"alpha"},{projectionId:"b",text:"beta"}] };
describe("embedding adapters",()=>{
  it("returns stable ordered deterministic embeddings and manifests",async()=>{const adapter=new DeterministicFakeEmbeddingAdapter(8);const first=await adapter.embedMany({...request,expectedDimensions:8});const second=await adapter.embedMany({...request,expectedDimensions:8});expect(first.items.map(x=>x.projectionId)).toEqual(["a","b"]);expect(first.outputManifestDigest).toBe(second.outputManifestDigest);expect(first.items[0]!.embedding).toHaveLength(8);});
  it("rejects wrong dimensions and non-finite values",()=>{expect(()=>validateVector([1,2],3)).toThrow("DIMENSION");expect(()=>validateVector([1,Number.NaN,3],3)).toThrow("NON_FINITE");expect(()=>validateVector(Array(DEFAULT_EMBEDDING_DIMENSIONS-1).fill(0),DEFAULT_EMBEDDING_DIMENSIONS)).toThrow();});
  it("retries with one idempotency key, validates provider order, and caches per version",async()=>{let calls=0;const seenKeys:string[]=[];const fetch=vi.fn(async (_url:unknown,init?:RequestInit)=>{calls++;seenKeys.push(new Headers(init?.headers).get("idempotency-key")??"");if(calls===1)return new Response("busy",{status:503});return Response.json({id:"req",model:"openai/text-embedding-3-small",data:[{index:0,embedding:[1,0,0]},{index:1,embedding:[0,1,0]}],usage:{total_tokens:2},providerMetadata:{gateway:{cost:"0.0001",provider:"openai"}}});});const cache=new MemoryEmbeddingCache();const adapter=new VercelAiGatewayEmbeddingAdapter({apiKey:"not-logged",fetch:fetch as typeof globalThis.fetch,sleep:async()=>{},cache,now:(()=>{let n=0;return()=>++n;})()});const first=await adapter.embedMany(request);expect(first.retryHistory).toHaveLength(1);expect(seenKeys).toEqual([request.idempotencyKey,request.idempotencyKey]);expect(first.items.every(x=>!x.cached)).toBe(true);const second=await adapter.embedMany(request);expect(calls).toBe(2);expect(second.items.every(x=>x.cached)).toBe(true);expect(second.observedProviderRoute).toBe("cache");const other=await adapter.embedMany({...request,vectorSpaceVersionId:"version-2"});expect(other.items.every(x=>!x.cached)).toBe(true);expect(calls).toBe(3);});
  it("rejects reordered, partial and malformed output atomically",async()=>{for(const data of [[{index:1,embedding:[1,0,0]},{index:0,embedding:[0,1,0]}],[{index:0,embedding:[1,0,0]}],[{index:0,embedding:[1,0]},{index:1,embedding:[0,1,0]}],[{index:0,embedding:[1,0,0]},{index:1,embedding:[0,Number.POSITIVE_INFINITY,0]}]]){const adapter=new VercelAiGatewayEmbeddingAdapter({apiKey:"secret",fetch:async()=>Response.json({data})});await expect(adapter.embedMany(request)).rejects.toThrow();}});
  it("rejects caller-supplied digest mismatches and duplicate projection identities",async()=>{const adapter=new DeterministicFakeEmbeddingAdapter(3);await expect(adapter.embedMany({...request,inputs:[{projectionId:"a",text:"alpha",textDigest:"sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}]})).rejects.toThrow("TEXT_DIGEST_MISMATCH");await expect(adapter.embedMany({...request,inputs:[{projectionId:"a",text:"alpha"},{projectionId:"a",text:"beta"}]})).rejects.toThrow("DUPLICATE_EMBEDDING_PROJECTION");});
  it("discovers the configured model without exposing credentials",async()=>{const adapter=new VercelAiGatewayEmbeddingAdapter({apiKey:"secret-never-returned",fetch:async()=>Response.json({data:[{id:"openai/text-embedding-3-small"}] }),now:()=>0});const found=await adapter.discoverModel("openai/text-embedding-3-small");expect(found.available).toBe(true);expect(JSON.stringify(found)).not.toContain("secret-never-returned");});
});
