// Compiler consumer probe generated from the merged baseline's public export symbols.
import type { AdvancedRetrievalPlan as PublicType0 } from "@aiengineer/knowledge-retrieval";
type PublicValue1 = typeof import("@aiengineer/knowledge-retrieval").buildRetrievalPlan;
import type { EvidenceMember as PublicType2 } from "@aiengineer/knowledge-retrieval";
import type { FilterValue as PublicType3 } from "@aiengineer/knowledge-retrieval";
import type { GraphEdge as PublicType4 } from "@aiengineer/knowledge-retrieval";
import type { ImmutableEvidencePacket as PublicType5 } from "@aiengineer/knowledge-retrieval";
import type { Reranker as PublicType6 } from "@aiengineer/knowledge-retrieval";
import type { RetrievalChannel as PublicType7 } from "@aiengineer/knowledge-retrieval";
import type { RetrievalFilter as PublicType8 } from "@aiengineer/knowledge-retrieval";
import type { RetrievalFlags as PublicType9 } from "@aiengineer/knowledge-retrieval";
import type { RetrievalIntent as PublicType10 } from "@aiengineer/knowledge-retrieval";
import type { RetrievalPolicy as PublicType11 } from "@aiengineer/knowledge-retrieval";
import type { RetrievalRecord as PublicType12 } from "@aiengineer/knowledge-retrieval";
import type { RetrievalStages as PublicType13 } from "@aiengineer/knowledge-retrieval";
import type { RetrievalSubquery as PublicType14 } from "@aiengineer/knowledge-retrieval";
type PublicValue15 = typeof import("@aiengineer/knowledge-retrieval").retrieve;
import type { RetrievedCandidate as PublicType16 } from "@aiengineer/knowledge-retrieval";
import type { RetrieveOptions as PublicType17 } from "@aiengineer/knowledge-retrieval";
import type { StageContribution as PublicType18 } from "@aiengineer/knowledge-retrieval";
import type { ClassificationProposal as PublicType19 } from "@aiengineer/knowledge-retrieval";
type PublicValue20 = typeof import("@aiengineer/knowledge-retrieval").classifyProjectionSpaces;
type PublicValue21 = typeof import("@aiengineer/knowledge-retrieval").createProjection;
import type { DomainDisposition as PublicType22 } from "@aiengineer/knowledge-retrieval";
import type { EvidenceSupport as PublicType23 } from "@aiengineer/knowledge-retrieval";
import type { EvidenceValidationResult as PublicType24 } from "@aiengineer/knowledge-retrieval";
import type { ProjectionInput as PublicType25 } from "@aiengineer/knowledge-retrieval";
type PublicValue26 = typeof import("@aiengineer/knowledge-retrieval").publicProjectionSpaces;
import type { SupportedAssertion as PublicType27 } from "@aiengineer/knowledge-retrieval";
type PublicValue28 = typeof import("@aiengineer/knowledge-retrieval").validateEvidenceSupport;
type PublicValue29 = typeof import("@aiengineer/knowledge-retrieval").AI_GATEWAY_BASE_URL;
type PublicValue30 = typeof import("@aiengineer/knowledge-retrieval").createGatewayEmbeddingAdapterFromEnvironment;
type PublicValue31 = typeof import("@aiengineer/knowledge-retrieval").DEFAULT_EMBEDDING_DIMENSIONS;
type PublicValue32 = typeof import("@aiengineer/knowledge-retrieval").DEFAULT_EMBEDDING_MODEL;
import type { DeterministicFakeEmbeddingAdapter as PublicType33 } from "@aiengineer/knowledge-retrieval";
type PublicValue33 = typeof import("@aiengineer/knowledge-retrieval").DeterministicFakeEmbeddingAdapter;
import type { EmbedBatchReceipt as PublicType34 } from "@aiengineer/knowledge-retrieval";
import type { EmbeddedItem as PublicType35 } from "@aiengineer/knowledge-retrieval";
import type { EmbeddingAdapter as PublicType36 } from "@aiengineer/knowledge-retrieval";
import type { EmbeddingCache as PublicType37 } from "@aiengineer/knowledge-retrieval";
import type { EmbedInput as PublicType38 } from "@aiengineer/knowledge-retrieval";
import type { EmbedManyRequest as PublicType39 } from "@aiengineer/knowledge-retrieval";
import type { EmbedOneRequest as PublicType40 } from "@aiengineer/knowledge-retrieval";
import type { EmbedReceipt as PublicType41 } from "@aiengineer/knowledge-retrieval";
import type { EmbedRequestBase as PublicType42 } from "@aiengineer/knowledge-retrieval";
import type { GatewayAdapterOptions as PublicType43 } from "@aiengineer/knowledge-retrieval";
import type { MemoryEmbeddingCache as PublicType44 } from "@aiengineer/knowledge-retrieval";
type PublicValue44 = typeof import("@aiengineer/knowledge-retrieval").MemoryEmbeddingCache;
import type { ModelDescriptor as PublicType45 } from "@aiengineer/knowledge-retrieval";
import type { RetryAttempt as PublicType46 } from "@aiengineer/knowledge-retrieval";
type PublicValue47 = typeof import("@aiengineer/knowledge-retrieval").validateVector;
type PublicValue48 = typeof import("@aiengineer/knowledge-retrieval").vectorDigest;
import type { VercelAiGatewayEmbeddingAdapter as PublicType49 } from "@aiengineer/knowledge-retrieval";
type PublicValue49 = typeof import("@aiengineer/knowledge-retrieval").VercelAiGatewayEmbeddingAdapter;
import type { ActivePublicationPointer as PublicType50 } from "@aiengineer/knowledge-retrieval";
type PublicValue51 = typeof import("@aiengineer/knowledge-retrieval").CANONICAL_EMBEDDING_DIMENSIONS;
import type { Digest as PublicType52 } from "@aiengineer/knowledge-retrieval";
import type { ExactVectorItem as PublicType53 } from "@aiengineer/knowledge-retrieval";
import type { ExploratoryPublication as PublicType54 } from "@aiengineer/knowledge-retrieval";
import type { ExploratoryPublicationCoordinator as PublicType55 } from "@aiengineer/knowledge-retrieval";
type PublicValue55 = typeof import("@aiengineer/knowledge-retrieval").ExploratoryPublicationCoordinator;
import type { InMemoryExactCosineBackend as PublicType56 } from "@aiengineer/knowledge-retrieval";
type PublicValue56 = typeof import("@aiengineer/knowledge-retrieval").InMemoryExactCosineBackend;
import type { InMemoryPublicationRepository as PublicType57 } from "@aiengineer/knowledge-retrieval";
type PublicValue57 = typeof import("@aiengineer/knowledge-retrieval").InMemoryPublicationRepository;
import type { PostgresRpcClient as PublicType58 } from "@aiengineer/knowledge-retrieval";
import type { PostgresRpcResult as PublicType59 } from "@aiengineer/knowledge-retrieval";
import type { PostgresVectorSearchBackend as PublicType60 } from "@aiengineer/knowledge-retrieval";
type PublicValue60 = typeof import("@aiengineer/knowledge-retrieval").PostgresVectorSearchBackend;
import type { PublicationEvent as PublicType61 } from "@aiengineer/knowledge-retrieval";
import type { PublicationInspection as PublicType62 } from "@aiengineer/knowledge-retrieval";
import type { PublicationInspector as PublicType63 } from "@aiengineer/knowledge-retrieval";
import type { PublicationManifests as PublicType64 } from "@aiengineer/knowledge-retrieval";
import type { PublicationReconciliationReport as PublicType65 } from "@aiengineer/knowledge-retrieval";
import type { PublicationRepository as PublicType66 } from "@aiengineer/knowledge-retrieval";
import type { PublicationState as PublicType67 } from "@aiengineer/knowledge-retrieval";
import type { PublicationTransaction as PublicType68 } from "@aiengineer/knowledge-retrieval";
import type { PublishExploratoryRequest as PublicType69 } from "@aiengineer/knowledge-retrieval";
import type { ReconciliationFinding as PublicType70 } from "@aiengineer/knowledge-retrieval";
import type { RollbackPublicationRequest as PublicType71 } from "@aiengineer/knowledge-retrieval";
type PublicValue72 = typeof import("@aiengineer/knowledge-retrieval").serializeHalfVector;
type PublicValue73 = typeof import("@aiengineer/knowledge-retrieval").validateEmbedding;
type PublicValue74 = typeof import("@aiengineer/knowledge-retrieval").validateSearchLimit;
type PublicValue75 = typeof import("@aiengineer/knowledge-retrieval").validateVectorItemEntityLink;
import type { VectorBackendError as PublicType76 } from "@aiengineer/knowledge-retrieval";
type PublicValue76 = typeof import("@aiengineer/knowledge-retrieval").VectorBackendError;
import type { VectorItemEntityLink as PublicType77 } from "@aiengineer/knowledge-retrieval";
import type { VectorSearchBackend as PublicType78 } from "@aiengineer/knowledge-retrieval";
import type { VectorSearchCandidate as PublicType79 } from "@aiengineer/knowledge-retrieval";
import type { VectorSearchRequest as PublicType80 } from "@aiengineer/knowledge-retrieval";
export {};
