// Compiler consumer probe generated from the merged baseline's public export symbols.
type PublicValue0 = typeof import("@aiengineer/knowledge-core").assertAppendOnly;
type PublicValue1 = typeof import("@aiengineer/knowledge-core").assertAuthorityCompatible;
type PublicValue2 = typeof import("@aiengineer/knowledge-core").assertCanonicalPublicationAuthority;
type PublicValue3 = typeof import("@aiengineer/knowledge-core").assertDecisionAuthority;
type PublicValue4 = typeof import("@aiengineer/knowledge-core").assertIdempotentReplay;
type PublicValue5 = typeof import("@aiengineer/knowledge-core").assertSourceNativeIntegrity;
type PublicValue6 = typeof import("@aiengineer/knowledge-core").canonicalJson;
type PublicValue7 = typeof import("@aiengineer/knowledge-core").createIdempotencyKey;
type PublicValue8 = typeof import("@aiengineer/knowledge-core").deepFreeze;
import type { DomainInvariantError as PublicType9 } from "@aiengineer/knowledge-core";
type PublicValue9 = typeof import("@aiengineer/knowledge-core").DomainInvariantError;
import type { IdempotencyIdentity as PublicType10 } from "@aiengineer/knowledge-core";
type PublicValue11 = typeof import("@aiengineer/knowledge-core").KNOWLEDGE_SERVICE_NAME;
import type { KnowledgeOperationState as PublicType12 } from "@aiengineer/knowledge-core";
type PublicValue13 = typeof import("@aiengineer/knowledge-core").knowledgeOperationStates;
import type { PromotionState as PublicType14 } from "@aiengineer/knowledge-core";
type PublicValue15 = typeof import("@aiengineer/knowledge-core").promotionStates;
import type { PublicationState as PublicType16 } from "@aiengineer/knowledge-core";
type PublicValue17 = typeof import("@aiengineer/knowledge-core").publicationStates;
type PublicValue18 = typeof import("@aiengineer/knowledge-core").sha256Digest;
import type { TransitionGuard as PublicType19 } from "@aiengineer/knowledge-core";
type PublicValue20 = typeof import("@aiengineer/knowledge-core").transitionOperation;
type PublicValue21 = typeof import("@aiengineer/knowledge-core").transitionPromotion;
type PublicValue22 = typeof import("@aiengineer/knowledge-core").transitionPublication;
import type { ActivityReceipt as PublicType23 } from "@aiengineer/knowledge-core";
import type { ArtifactDigest as PublicType24 } from "@aiengineer/knowledge-core";
import type { ArtifactFetch as PublicType25 } from "@aiengineer/knowledge-core";
import type { ArtifactStore as PublicType26 } from "@aiengineer/knowledge-core";
import type { Clock as PublicType27 } from "@aiengineer/knowledge-core";
type PublicValue28 = typeof import("@aiengineer/knowledge-core").createEveRuntimeAttestation;
type PublicValue29 = typeof import("@aiengineer/knowledge-core").deterministicUuid;
type PublicValue30 = typeof import("@aiengineer/knowledge-core").digestBytes;
import type { InMemoryArtifactStore as PublicType31 } from "@aiengineer/knowledge-core";
type PublicValue31 = typeof import("@aiengineer/knowledge-core").InMemoryArtifactStore;
import type { InMemoryOperationLedger as PublicType32 } from "@aiengineer/knowledge-core";
type PublicValue32 = typeof import("@aiengineer/knowledge-core").InMemoryOperationLedger;
import type { LedgerEvent as PublicType33 } from "@aiengineer/knowledge-core";
import type { LocalArtifactStore as PublicType34 } from "@aiengineer/knowledge-core";
type PublicValue34 = typeof import("@aiengineer/knowledge-core").LocalArtifactStore;
import type { OperationContext as PublicType35 } from "@aiengineer/knowledge-core";
import type { OperationLedgerSnapshot as PublicType36 } from "@aiengineer/knowledge-core";
import type { OperationRecord as PublicType37 } from "@aiengineer/knowledge-core";
import type { OperationState as PublicType38 } from "@aiengineer/knowledge-core";
type PublicValue39 = typeof import("@aiengineer/knowledge-core").parseEveRuntimeAttestation;
import type { PutArtifact as PublicType40 } from "@aiengineer/knowledge-core";
import type { StepRecord as PublicType41 } from "@aiengineer/knowledge-core";
import type { StepState as PublicType42 } from "@aiengineer/knowledge-core";
import type { StoredArtifact as PublicType43 } from "@aiengineer/knowledge-core";
import type { SupabaseArtifactStore as PublicType44 } from "@aiengineer/knowledge-core";
type PublicValue44 = typeof import("@aiengineer/knowledge-core").SupabaseArtifactStore;
import type { SupabaseArtifactStoreConfig as PublicType45 } from "@aiengineer/knowledge-core";
type PublicValue46 = typeof import("@aiengineer/knowledge-core").verifyEveRuntimeAttestation;
import type { InMemoryTelemetry as PublicType47 } from "@aiengineer/knowledge-core";
type PublicValue47 = typeof import("@aiengineer/knowledge-core").InMemoryTelemetry;
import type { OperationMetric as PublicType48 } from "@aiengineer/knowledge-core";
type PublicValue49 = typeof import("@aiengineer/knowledge-core").reconcileManifests;
import type { ReconciliationFinding as PublicType50 } from "@aiengineer/knowledge-core";
import type { ServiceSloSnapshot as PublicType51 } from "@aiengineer/knowledge-core";
export {};
