// Compiler consumer probe generated from the merged baseline's public export symbols.
type PublicValue0 = typeof import("@aiengineer/knowledge-schema-workspace").assertHeadMatches;
import type { CatalogEntry as PublicType1 } from "@aiengineer/knowledge-schema-workspace";
type PublicValue2 = typeof import("@aiengineer/knowledge-schema-workspace").CatalogEntrySchema;
type PublicValue3 = typeof import("@aiengineer/knowledge-schema-workspace").compareHeads;
type PublicValue4 = typeof import("@aiengineer/knowledge-schema-workspace").domainError;
import type { ExitClass as PublicType5 } from "@aiengineer/knowledge-schema-workspace";
type PublicValue6 = typeof import("@aiengineer/knowledge-schema-workspace").getPage;
import type { HeadCheck as PublicType7 } from "@aiengineer/knowledge-schema-workspace";
type PublicValue8 = typeof import("@aiengineer/knowledge-schema-workspace").infrastructureError;
type PublicValue9 = typeof import("@aiengineer/knowledge-schema-workspace").isKnowledgeError;
import type { KnowledgeError as PublicType10 } from "@aiengineer/knowledge-schema-workspace";
type PublicValue10 = typeof import("@aiengineer/knowledge-schema-workspace").KnowledgeError;
type PublicValue11 = typeof import("@aiengineer/knowledge-schema-workspace").loadMaterialized;
type PublicValue12 = typeof import("@aiengineer/knowledge-schema-workspace").loadWorkspace;
import type { LocateOptions as PublicType13 } from "@aiengineer/knowledge-schema-workspace";
import type { MaterializeInput as PublicType14 } from "@aiengineer/knowledge-schema-workspace";
import type { MaterializeResult as PublicType15 } from "@aiengineer/knowledge-schema-workspace";
type PublicValue16 = typeof import("@aiengineer/knowledge-schema-workspace").materializeScope;
import type { Page as PublicType17 } from "@aiengineer/knowledge-schema-workspace";
import type { PageOptions as PublicType18 } from "@aiengineer/knowledge-schema-workspace";
import type { QueryCatalog as PublicType19 } from "@aiengineer/knowledge-schema-workspace";
type PublicValue20 = typeof import("@aiengineer/knowledge-schema-workspace").QueryCatalogSchema;
type PublicValue21 = typeof import("@aiengineer/knowledge-schema-workspace").requireCatalog;
type PublicValue22 = typeof import("@aiengineer/knowledge-schema-workspace").resolveWorkspaceDir;
import type { SchemaScope as PublicType23 } from "@aiengineer/knowledge-schema-workspace";
import type { SearchEntry as PublicType24 } from "@aiengineer/knowledge-schema-workspace";
type PublicValue25 = typeof import("@aiengineer/knowledge-schema-workspace").SearchEntrySchema;
import type { SearchHit as PublicType26 } from "@aiengineer/knowledge-schema-workspace";
import type { SearchOptions as PublicType27 } from "@aiengineer/knowledge-schema-workspace";
import type { SearchResult as PublicType28 } from "@aiengineer/knowledge-schema-workspace";
type PublicValue29 = typeof import("@aiengineer/knowledge-schema-workspace").searchWorkspace;
import type { TerminologyEntry as PublicType30 } from "@aiengineer/knowledge-schema-workspace";
import type { Workspace as PublicType31 } from "@aiengineer/knowledge-schema-workspace";
type PublicValue32 = typeof import("@aiengineer/knowledge-schema-workspace").WORKSPACE_FILES;
import type { WorkspaceManifest as PublicType33 } from "@aiengineer/knowledge-schema-workspace";
type PublicValue34 = typeof import("@aiengineer/knowledge-db-read").applyDefaults;
import type { ArtifactLedger as PublicType35 } from "@aiengineer/knowledge-db-read";
type PublicValue35 = typeof import("@aiengineer/knowledge-db-read").ArtifactLedger;
import type { ArtifactLedgerConfig as PublicType36 } from "@aiengineer/knowledge-db-read";
import type { ArtifactRecord as PublicType37 } from "@aiengineer/knowledge-db-read";
type PublicValue38 = typeof import("@aiengineer/knowledge-db-read").assertSingleReadStatement;
type PublicValue39 = typeof import("@aiengineer/knowledge-db-read").bindKnowledgeClock;
type PublicValue40 = typeof import("@aiengineer/knowledge-db-read").buildSpaceManifest;
import type { BuildSpaceManifestInput as PublicType41 } from "@aiengineer/knowledge-db-read";
type PublicValue42 = typeof import("@aiengineer/knowledge-db-read").canonicalJson;
import type { Digest as PublicType43 } from "@aiengineer/knowledge-db-read";
type PublicValue44 = typeof import("@aiengineer/knowledge-db-read").digestHexOf;
type PublicValue45 = typeof import("@aiengineer/knowledge-db-read").digestOf;
type PublicValue46 = typeof import("@aiengineer/knowledge-db-read").isDigest;
type PublicValue47 = typeof import("@aiengineer/knowledge-db-read").isUuid;
import type { JsonPrimitive as PublicType48 } from "@aiengineer/knowledge-db-read";
type PublicValue49 = typeof import("@aiengineer/knowledge-db-read").jsonSafeRow;
import type { JsonSchema as PublicType50 } from "@aiengineer/knowledge-db-read";
import type { JsonValue as PublicType51 } from "@aiengineer/knowledge-db-read";
import type { KnowledgeArtifactType as PublicType52 } from "@aiengineer/knowledge-db-read";
import type { KnowledgeHead as PublicType53 } from "@aiengineer/knowledge-db-read";
import type { LineageEdge as PublicType54 } from "@aiengineer/knowledge-db-read";
type PublicValue55 = typeof import("@aiengineer/knowledge-db-read").MAX_OPERATIONS;
type PublicValue56 = typeof import("@aiengineer/knowledge-db-read").MAX_STATEMENT_TIMEOUT_MS;
import type { OperationResult as PublicType57 } from "@aiengineer/knowledge-db-read";
import type { OperationStatus as PublicType58 } from "@aiengineer/knowledge-db-read";
import type { PutArtifactInput as PublicType59 } from "@aiengineer/knowledge-db-read";
type PublicValue60 = typeof import("@aiengineer/knowledge-db-read").ReadContextSchema;
import type { ReadExecutor as PublicType61 } from "@aiengineer/knowledge-db-read";
type PublicValue61 = typeof import("@aiengineer/knowledge-db-read").ReadExecutor;
import type { ReadExecutorConfig as PublicType62 } from "@aiengineer/knowledge-db-read";
import type { ReadIntent as PublicType63 } from "@aiengineer/knowledge-db-read";
import type { ReadIntentInput as PublicType64 } from "@aiengineer/knowledge-db-read";
type PublicValue65 = typeof import("@aiengineer/knowledge-db-read").ReadIntentSchema;
import type { ReadOperation as PublicType66 } from "@aiengineer/knowledge-db-read";
type PublicValue67 = typeof import("@aiengineer/knowledge-db-read").ReadOperationSchema;
type PublicValue68 = typeof import("@aiengineer/knowledge-db-read").ReadRoleSchema;
import type { ReadSnapshot as PublicType69 } from "@aiengineer/knowledge-db-read";
type PublicValue70 = typeof import("@aiengineer/knowledge-db-read").readSpaceManifest;
import type { ReadSpaceManifestInput as PublicType71 } from "@aiengineer/knowledge-db-read";
import type { ResolvedParams as PublicType72 } from "@aiengineer/knowledge-db-read";
type PublicValue73 = typeof import("@aiengineer/knowledge-db-read").resolveReferences;
import type { Row as PublicType74 } from "@aiengineer/knowledge-db-read";
import type { RunIntentOptions as PublicType75 } from "@aiengineer/knowledge-db-read";
import type { SchemaIssue as PublicType76 } from "@aiengineer/knowledge-db-read";
type PublicValue77 = typeof import("@aiengineer/knowledge-db-read").sha256Hex;
type PublicValue78 = typeof import("@aiengineer/knowledge-db-read").SLUG;
type PublicValue79 = typeof import("@aiengineer/knowledge-db-read").SlugSchema;
type PublicValue80 = typeof import("@aiengineer/knowledge-db-read").snapshotDigest;
import type { SnapshotExpectation as PublicType81 } from "@aiengineer/knowledge-db-read";
type PublicValue82 = typeof import("@aiengineer/knowledge-db-read").SPACE_MANIFEST_SCHEMA_VERSION;
import type { SpaceManifest as PublicType83 } from "@aiengineer/knowledge-db-read";
import type { SpaceManifestActivePublication as PublicType84 } from "@aiengineer/knowledge-db-read";
import type { SpaceManifestAuthorityClass as PublicType85 } from "@aiengineer/knowledge-db-read";
import type { SpaceManifestBudget as PublicType86 } from "@aiengineer/knowledge-db-read";
import type { SpaceManifestEntry as PublicType87 } from "@aiengineer/knowledge-db-read";
import type { SpaceManifestLiveFacts as PublicType88 } from "@aiengineer/knowledge-db-read";
import type { SpaceManifestProfile as PublicType89 } from "@aiengineer/knowledge-db-read";
import type { SpaceManifestProfileTable as PublicType90 } from "@aiengineer/knowledge-db-read";
import type { SpaceManifestReads as PublicType91 } from "@aiengineer/knowledge-db-read";
import type { SpaceManifestUnavailable as PublicType92 } from "@aiengineer/knowledge-db-read";
import type { SqlReadInput as PublicType93 } from "@aiengineer/knowledge-db-read";
import type { SqlReadResult as PublicType94 } from "@aiengineer/knowledge-db-read";
type PublicValue95 = typeof import("@aiengineer/knowledge-db-read").UUID_PATTERN;
type PublicValue96 = typeof import("@aiengineer/knowledge-db-read").UuidSchema;
type PublicValue97 = typeof import("@aiengineer/knowledge-db-read").uuidv7;
type PublicValue98 = typeof import("@aiengineer/knowledge-db-read").validatePersistedSnapshot;
type PublicValue99 = typeof import("@aiengineer/knowledge-db-read").validateSchema;
type PublicValue100 = typeof import("@aiengineer/knowledge-ingestion").admissionIssues;
import type { AffectedRef as PublicType101 } from "@aiengineer/knowledge-ingestion";
type PublicValue102 = typeof import("@aiengineer/knowledge-ingestion").ALIAS_KINDS;
import type { ApplyContext as PublicType103 } from "@aiengineer/knowledge-ingestion";
import type { ApplyOutcome as PublicType104 } from "@aiengineer/knowledge-ingestion";
type PublicValue105 = typeof import("@aiengineer/knowledge-ingestion").applyPlan;
type PublicValue106 = typeof import("@aiengineer/knowledge-ingestion").applyRules;
type PublicValue107 = typeof import("@aiengineer/knowledge-ingestion").authenticateCanonicalContentEvidence;
import type { AuthenticatedContentEvidence as PublicType108 } from "@aiengineer/knowledge-ingestion";
import type { AuthoritativeClaim as PublicType109 } from "@aiengineer/knowledge-ingestion";
type PublicValue110 = typeof import("@aiengineer/knowledge-ingestion").awaitWinnerReceipt;
type PublicValue111 = typeof import("@aiengineer/knowledge-ingestion").buildPlan;
import type { ChangedItem as PublicType112 } from "@aiengineer/knowledge-ingestion";
import type { ClaimEligibility as PublicType113 } from "@aiengineer/knowledge-ingestion";
import type { ClaimFacts as PublicType114 } from "@aiengineer/knowledge-ingestion";
type PublicValue115 = typeof import("@aiengineer/knowledge-ingestion").classifyFailure;
type PublicValue116 = typeof import("@aiengineer/knowledge-ingestion").contentEvidenceAssessmentDigest;
import type { ContentLinkAuthority as PublicType117 } from "@aiengineer/knowledge-ingestion";
type PublicValue118 = typeof import("@aiengineer/knowledge-ingestion").contentLinkEffect;
import type { ContentLinkExecutor as PublicType119 } from "@aiengineer/knowledge-ingestion";
type PublicValue119 = typeof import("@aiengineer/knowledge-ingestion").ContentLinkExecutor;
import type { ContentLinkPlan as PublicType120 } from "@aiengineer/knowledge-ingestion";
import type { ContentLinkReceipt as PublicType121 } from "@aiengineer/knowledge-ingestion";
import type { ContentSourceReader as PublicType122 } from "@aiengineer/knowledge-ingestion";
type PublicValue122 = typeof import("@aiengineer/knowledge-ingestion").ContentSourceReader;
import type { ContentSummaryPreparationResult as PublicType123 } from "@aiengineer/knowledge-ingestion";
import type { ContentSummaryPreparer as PublicType124 } from "@aiengineer/knowledge-ingestion";
type PublicValue124 = typeof import("@aiengineer/knowledge-ingestion").ContentSummaryPreparer;
type PublicValue125 = typeof import("@aiengineer/knowledge-ingestion").DEFAULT_DUPLICATE_WAIT;
type PublicValue126 = typeof import("@aiengineer/knowledge-ingestion").deterministicId;
import type { DuplicateIdentity as PublicType127 } from "@aiengineer/knowledge-ingestion";
import type { DuplicateWaitPolicy as PublicType128 } from "@aiengineer/knowledge-ingestion";
type PublicValue129 = typeof import("@aiengineer/knowledge-ingestion").ENTITY_REF_KINDS;
import type { EntityKind as PublicType130 } from "@aiengineer/knowledge-ingestion";
import type { EntityMatch as PublicType131 } from "@aiengineer/knowledge-ingestion";
import type { EventKind as PublicType132 } from "@aiengineer/knowledge-ingestion";
import type { EvidenceOracle as PublicType133 } from "@aiengineer/knowledge-ingestion";
import type { EvidenceRef as PublicType134 } from "@aiengineer/knowledge-ingestion";
type PublicValue135 = typeof import("@aiengineer/knowledge-ingestion").EvidenceRefSchema;
import type { ExistingFacts as PublicType136 } from "@aiengineer/knowledge-ingestion";
type PublicValue137 = typeof import("@aiengineer/knowledge-ingestion").ExtentSchema;
import type { FactGatheringDeps as PublicType138 } from "@aiengineer/knowledge-ingestion";
type PublicValue139 = typeof import("@aiengineer/knowledge-ingestion").gatherFacts;
type PublicValue140 = typeof import("@aiengineer/knowledge-ingestion").IDENTIFIER_SCHEMES;
import type { IngestionExecutor as PublicType141 } from "@aiengineer/knowledge-ingestion";
type PublicValue141 = typeof import("@aiengineer/knowledge-ingestion").IngestionExecutor;
import type { IngestionExecutorConfig as PublicType142 } from "@aiengineer/knowledge-ingestion";
import type { IngestionIntent as PublicType143 } from "@aiengineer/knowledge-ingestion";
import type { IngestionIntentInput as PublicType144 } from "@aiengineer/knowledge-ingestion";
type PublicValue145 = typeof import("@aiengineer/knowledge-ingestion").IngestionIntentSchema;
import type { IngestionOptions as PublicType146 } from "@aiengineer/knowledge-ingestion";
import type { IngestionPlan as PublicType147 } from "@aiengineer/knowledge-ingestion";
import type { IngestionReceipt as PublicType148 } from "@aiengineer/knowledge-ingestion";
import type { IngestionRule as PublicType149 } from "@aiengineer/knowledge-ingestion";
import type { InlineClaim as PublicType150 } from "@aiengineer/knowledge-ingestion";
type PublicValue151 = typeof import("@aiengineer/knowledge-ingestion").InlineClaimSchema;
type PublicValue152 = typeof import("@aiengineer/knowledge-ingestion").intentDigestOf;
type PublicValue153 = typeof import("@aiengineer/knowledge-ingestion").intentIdempotencyKey;
type PublicValue154 = typeof import("@aiengineer/knowledge-ingestion").isIdempotencyKeyCollision;
type PublicValue155 = typeof import("@aiengineer/knowledge-ingestion").isOfficiallyAdmittedVerdict;
type PublicValue156 = typeof import("@aiengineer/knowledge-ingestion").loadRules;
type PublicValue157 = typeof import("@aiengineer/knowledge-ingestion").loadVocabulary;
import type { NewSubject as PublicType158 } from "@aiengineer/knowledge-ingestion";
type PublicValue159 = typeof import("@aiengineer/knowledge-ingestion").NO_RULES;
import type { PlanError as PublicType160 } from "@aiengineer/knowledge-ingestion";
import type { PlanExecutorIdentity as PublicType161 } from "@aiengineer/knowledge-ingestion";
import type { PlanFacts as PublicType162 } from "@aiengineer/knowledge-ingestion";
import type { PlannedAction as PublicType163 } from "@aiengineer/knowledge-ingestion";
import type { PlannedOutcome as PublicType164 } from "@aiengineer/knowledge-ingestion";
import type { PlannedProposal as PublicType165 } from "@aiengineer/knowledge-ingestion";
import type { PlannedSubject as PublicType166 } from "@aiengineer/knowledge-ingestion";
import type { Proposal as PublicType167 } from "@aiengineer/knowledge-ingestion";
type PublicValue168 = typeof import("@aiengineer/knowledge-ingestion").proposalClaims;
type PublicValue169 = typeof import("@aiengineer/knowledge-ingestion").proposalEffect;
type PublicValue170 = typeof import("@aiengineer/knowledge-ingestion").proposalIdempotencyKey;
import type { ProposalKind as PublicType171 } from "@aiengineer/knowledge-ingestion";
import type { ProposalOf as PublicType172 } from "@aiengineer/knowledge-ingestion";
import type { ProposalOutcome as PublicType173 } from "@aiengineer/knowledge-ingestion";
import type { ProposalReceipt as PublicType174 } from "@aiengineer/knowledge-ingestion";
type PublicValue175 = typeof import("@aiengineer/knowledge-ingestion").ProposalSchema;
type PublicValue176 = typeof import("@aiengineer/knowledge-ingestion").readContentLinkReceipt;
import type { ReceiptFailure as PublicType177 } from "@aiengineer/knowledge-ingestion";
import type { RegisterReportInput as PublicType178 } from "@aiengineer/knowledge-ingestion";
import type { RelationshipKind as PublicType179 } from "@aiengineer/knowledge-ingestion";
import type { RenderedAssertion as PublicType180 } from "@aiengineer/knowledge-ingestion";
type PublicValue181 = typeof import("@aiengineer/knowledge-ingestion").renderReport;
type PublicValue182 = typeof import("@aiengineer/knowledge-ingestion").REPORT_BUCKET;
import type { ReportClaimReference as PublicType183 } from "@aiengineer/knowledge-ingestion";
import type { ReportEvidence as PublicType184 } from "@aiengineer/knowledge-ingestion";
import type { ReportPackageRead as PublicType185 } from "@aiengineer/knowledge-ingestion";
import type { ReportRegistration as PublicType186 } from "@aiengineer/knowledge-ingestion";
import type { ReportService as PublicType187 } from "@aiengineer/knowledge-ingestion";
type PublicValue187 = typeof import("@aiengineer/knowledge-ingestion").ReportService;
import type { ReportServiceConfig as PublicType188 } from "@aiengineer/knowledge-ingestion";
import type { ReportStructure as PublicType189 } from "@aiengineer/knowledge-ingestion";
type PublicValue190 = typeof import("@aiengineer/knowledge-ingestion").ReportStructureSchema;
import type { Rewrite as PublicType191 } from "@aiengineer/knowledge-ingestion";
import type { RuleApplication as PublicType192 } from "@aiengineer/knowledge-ingestion";
import type { RuleCheck as PublicType193 } from "@aiengineer/knowledge-ingestion";
import type { RuleCondition as PublicType194 } from "@aiengineer/knowledge-ingestion";
import type { RuleFacts as PublicType195 } from "@aiengineer/knowledge-ingestion";
import type { RuleSet as PublicType196 } from "@aiengineer/knowledge-ingestion";
type PublicValue197 = typeof import("@aiengineer/knowledge-ingestion").slugify;
import type { StreamKind as PublicType198 } from "@aiengineer/knowledge-ingestion";
type PublicValue199 = typeof import("@aiengineer/knowledge-ingestion").STRONG_MATCH;
import type { Subject as PublicType200 } from "@aiengineer/knowledge-ingestion";
import type { SubjectFacts as PublicType201 } from "@aiengineer/knowledge-ingestion";
type PublicValue202 = typeof import("@aiengineer/knowledge-ingestion").subjectIdentity;
type PublicValue203 = typeof import("@aiengineer/knowledge-ingestion").subjectRefsOf;
type PublicValue204 = typeof import("@aiengineer/knowledge-ingestion").SubjectSchema;
type PublicValue205 = typeof import("@aiengineer/knowledge-ingestion").validateProposal;
import type { ValidationContext as PublicType206 } from "@aiengineer/knowledge-ingestion";
import type { Vocabulary as PublicType207 } from "@aiengineer/knowledge-ingestion";
import type { VocabularyIssue as PublicType208 } from "@aiengineer/knowledge-ingestion";
import type { WorldInterval as PublicType209 } from "@aiengineer/knowledge-ingestion";
type PublicValue210 = typeof import("@aiengineer/knowledge-ingestion").WorldIntervalSchema;
export {};
