// Compiler consumer probe generated from the merged baseline's public export symbols.
type PublicValue0 = typeof import("@aiengineer/knowledge-domain").assertAppendOnly;
type PublicValue1 = typeof import("@aiengineer/knowledge-domain").assertAuthorityCompatible;
type PublicValue2 = typeof import("@aiengineer/knowledge-domain").assertCanonicalPublicationAuthority;
type PublicValue3 = typeof import("@aiengineer/knowledge-domain").assertDecisionAuthority;
type PublicValue4 = typeof import("@aiengineer/knowledge-domain").assertIdempotentReplay;
type PublicValue5 = typeof import("@aiengineer/knowledge-domain").assertSourceNativeIntegrity;
type PublicValue6 = typeof import("@aiengineer/knowledge-domain").canonicalJson;
type PublicValue7 = typeof import("@aiengineer/knowledge-domain").createIdempotencyKey;
type PublicValue8 = typeof import("@aiengineer/knowledge-domain").deepFreeze;
import type { DomainInvariantError as PublicType9 } from "@aiengineer/knowledge-domain";
type PublicValue9 = typeof import("@aiengineer/knowledge-domain").DomainInvariantError;
import type { IdempotencyIdentity as PublicType10 } from "@aiengineer/knowledge-domain";
type PublicValue11 = typeof import("@aiengineer/knowledge-domain").KNOWLEDGE_SERVICE_NAME;
import type { KnowledgeOperationState as PublicType12 } from "@aiengineer/knowledge-domain";
type PublicValue13 = typeof import("@aiengineer/knowledge-domain").knowledgeOperationStates;
import type { PromotionState as PublicType14 } from "@aiengineer/knowledge-domain";
type PublicValue15 = typeof import("@aiengineer/knowledge-domain").promotionStates;
import type { PublicationState as PublicType16 } from "@aiengineer/knowledge-domain";
type PublicValue17 = typeof import("@aiengineer/knowledge-domain").publicationStates;
type PublicValue18 = typeof import("@aiengineer/knowledge-domain").sha256Digest;
import type { TransitionGuard as PublicType19 } from "@aiengineer/knowledge-domain";
type PublicValue20 = typeof import("@aiengineer/knowledge-domain").transitionOperation;
type PublicValue21 = typeof import("@aiengineer/knowledge-domain").transitionPromotion;
type PublicValue22 = typeof import("@aiengineer/knowledge-domain").transitionPublication;
import type { ActivityReceipt as PublicType23 } from "@aiengineer/knowledge-runtime";
import type { ArtifactDigest as PublicType24 } from "@aiengineer/knowledge-runtime";
import type { ArtifactFetch as PublicType25 } from "@aiengineer/knowledge-runtime";
import type { ArtifactStore as PublicType26 } from "@aiengineer/knowledge-runtime";
import type { Clock as PublicType27 } from "@aiengineer/knowledge-runtime";
type PublicValue28 = typeof import("@aiengineer/knowledge-runtime").createEveRuntimeAttestation;
type PublicValue29 = typeof import("@aiengineer/knowledge-runtime").deterministicUuid;
type PublicValue30 = typeof import("@aiengineer/knowledge-runtime").digestBytes;
import type { InMemoryArtifactStore as PublicType31 } from "@aiengineer/knowledge-runtime";
type PublicValue31 = typeof import("@aiengineer/knowledge-runtime").InMemoryArtifactStore;
import type { InMemoryOperationLedger as PublicType32 } from "@aiengineer/knowledge-runtime";
type PublicValue32 = typeof import("@aiengineer/knowledge-runtime").InMemoryOperationLedger;
import type { LedgerEvent as PublicType33 } from "@aiengineer/knowledge-runtime";
import type { LocalArtifactStore as PublicType34 } from "@aiengineer/knowledge-runtime";
type PublicValue34 = typeof import("@aiengineer/knowledge-runtime").LocalArtifactStore;
import type { OperationContext as PublicType35 } from "@aiengineer/knowledge-runtime";
import type { OperationLedgerSnapshot as PublicType36 } from "@aiengineer/knowledge-runtime";
import type { OperationRecord as PublicType37 } from "@aiengineer/knowledge-runtime";
import type { OperationState as PublicType38 } from "@aiengineer/knowledge-runtime";
type PublicValue39 = typeof import("@aiengineer/knowledge-runtime").parseEveRuntimeAttestation;
import type { PutArtifact as PublicType40 } from "@aiengineer/knowledge-runtime";
import type { StepRecord as PublicType41 } from "@aiengineer/knowledge-runtime";
import type { StepState as PublicType42 } from "@aiengineer/knowledge-runtime";
import type { StoredArtifact as PublicType43 } from "@aiengineer/knowledge-runtime";
import type { SupabaseArtifactStore as PublicType44 } from "@aiengineer/knowledge-runtime";
type PublicValue44 = typeof import("@aiengineer/knowledge-runtime").SupabaseArtifactStore;
import type { SupabaseArtifactStoreConfig as PublicType45 } from "@aiengineer/knowledge-runtime";
type PublicValue46 = typeof import("@aiengineer/knowledge-runtime").verifyEveRuntimeAttestation;
import type { InMemoryTelemetry as PublicType47 } from "@aiengineer/knowledge-observability";
type PublicValue47 = typeof import("@aiengineer/knowledge-observability").InMemoryTelemetry;
import type { OperationMetric as PublicType48 } from "@aiengineer/knowledge-observability";
type PublicValue49 = typeof import("@aiengineer/knowledge-observability").reconcileManifests;
import type { ReconciliationFinding as PublicType50 } from "@aiengineer/knowledge-observability";
import type { ServiceSloSnapshot as PublicType51 } from "@aiengineer/knowledge-observability";
export {};
