// Compiler consumer probe generated from the merged baseline's public export symbols.
import type { ConversionAttemptOutcome as PublicType0 } from "@aiengineer/knowledge-conversion";
import type { ConversionFailureClass as PublicType1 } from "@aiengineer/knowledge-conversion";
import type { ConversionFetch as PublicType2 } from "@aiengineer/knowledge-conversion";
import type { ConversionLocator as PublicType3 } from "@aiengineer/knowledge-conversion";
import type { ConversionMetrics as PublicType4 } from "@aiengineer/knowledge-conversion";
import type { ConversionNode as PublicType5 } from "@aiengineer/knowledge-conversion";
import type { ConversionNodeKind as PublicType6 } from "@aiengineer/knowledge-conversion";
import type { ConversionOutput as PublicType7 } from "@aiengineer/knowledge-conversion";
import type { ConversionProfile as PublicType8 } from "@aiengineer/knowledge-conversion";
import type { ConversionRequest as PublicType9 } from "@aiengineer/knowledge-conversion";
import type { ConversionRouteAttempt as PublicType10 } from "@aiengineer/knowledge-conversion";
import type { ConversionRouteOptions as PublicType11 } from "@aiengineer/knowledge-conversion";
import type { ConversionRouter as PublicType12 } from "@aiengineer/knowledge-conversion";
type PublicValue12 = typeof import("@aiengineer/knowledge-conversion").ConversionRouter;
type PublicValue13 = typeof import("@aiengineer/knowledge-conversion").conversionRouterFromProviders;
import type { ConversionRouterProviders as PublicType14 } from "@aiengineer/knowledge-conversion";
import type { ConversionRoutingReceipt as PublicType15 } from "@aiengineer/knowledge-conversion";
type PublicValue16 = typeof import("@aiengineer/knowledge-conversion").convertTextToNodes;
type PublicValue17 = typeof import("@aiengineer/knowledge-conversion").createDoclingServeClientFromEnvironment;
type PublicValue18 = typeof import("@aiengineer/knowledge-conversion").DEFAULT_DOCLING_BASE_URL;
type PublicValue19 = typeof import("@aiengineer/knowledge-conversion").DEFAULT_DOCLING_MAXIMUM_RESULT_BYTES;
type PublicValue20 = typeof import("@aiengineer/knowledge-conversion").DEFAULT_DOCLING_REQUEST_TIMEOUT_MS;
type PublicValue21 = typeof import("@aiengineer/knowledge-conversion").DEFAULT_UNSTRUCTURED_POLLS;
type PublicValue22 = typeof import("@aiengineer/knowledge-conversion").DETERMINISTIC_PROVIDER_KEY;
type PublicValue23 = typeof import("@aiengineer/knowledge-conversion").DETERMINISTIC_PROVIDER_VERSION;
import type { DeterministicTextConversionProvider as PublicType24 } from "@aiengineer/knowledge-conversion";
type PublicValue24 = typeof import("@aiengineer/knowledge-conversion").DeterministicTextConversionProvider;
type PublicValue25 = typeof import("@aiengineer/knowledge-conversion").DOCLING_PROVIDER_KEY;
import type { DoclingServeClient as PublicType26 } from "@aiengineer/knowledge-conversion";
import type { DoclingServeEnvironment as PublicType27 } from "@aiengineer/knowledge-conversion";
import type { DoclingServeHttpConfig as PublicType28 } from "@aiengineer/knowledge-conversion";
import type { DoclingServeProvider as PublicType29 } from "@aiengineer/knowledge-conversion";
type PublicValue29 = typeof import("@aiengineer/knowledge-conversion").DoclingServeProvider;
import type { DocumentConversionProvider as PublicType30 } from "@aiengineer/knowledge-conversion";
import type { FidelityFinding as PublicType31 } from "@aiengineer/knowledge-conversion";
import type { FidelityFindingDisposition as PublicType32 } from "@aiengineer/knowledge-conversion";
import type { FidelityGrade as PublicType33 } from "@aiengineer/knowledge-conversion";
import type { FidelityReport as PublicType34 } from "@aiengineer/knowledge-conversion";
import type { HttpDoclingServeClient as PublicType35 } from "@aiengineer/knowledge-conversion";
type PublicValue35 = typeof import("@aiengineer/knowledge-conversion").HttpDoclingServeClient;
import type { HttpUnstructuredTransformClient as PublicType36 } from "@aiengineer/knowledge-conversion";
type PublicValue36 = typeof import("@aiengineer/knowledge-conversion").HttpUnstructuredTransformClient;
type PublicValue37 = typeof import("@aiengineer/knowledge-conversion").inspectConversion;
type PublicValue38 = typeof import("@aiengineer/knowledge-conversion").isDeterministicTextMediaType;
type PublicValue39 = typeof import("@aiengineer/knowledge-conversion").isDoclingMediaType;
type PublicValue40 = typeof import("@aiengineer/knowledge-conversion").isExclusiveTextMediaType;
type PublicValue41 = typeof import("@aiengineer/knowledge-conversion").isHtmlMediaType;
type PublicValue42 = typeof import("@aiengineer/knowledge-conversion").LOW_COVERAGE_THRESHOLD;
type PublicValue43 = typeof import("@aiengineer/knowledge-conversion").normalizeMediaType;
type PublicValue44 = typeof import("@aiengineer/knowledge-conversion").REPEATED_BLOCK_REVIEW_RATIO;
type PublicValue45 = typeof import("@aiengineer/knowledge-conversion").requiresAlternateConversion;
import type { SandboxedVerificationParser as PublicType46 } from "@aiengineer/knowledge-conversion";
type PublicValue46 = typeof import("@aiengineer/knowledge-conversion").SandboxedVerificationParser;
type PublicValue47 = typeof import("@aiengineer/knowledge-conversion").UNSTRUCTURED_PROVIDER_KEY;
import type { UnstructuredHttpConfig as PublicType48 } from "@aiengineer/knowledge-conversion";
import type { UnstructuredTransformClient as PublicType49 } from "@aiengineer/knowledge-conversion";
import type { UnstructuredTransformProvider as PublicType50 } from "@aiengineer/knowledge-conversion";
type PublicValue50 = typeof import("@aiengineer/knowledge-conversion").UnstructuredTransformProvider;
type PublicValue51 = typeof import("@aiengineer/knowledge-conversion").VERIFICATION_PARSER_LIMITS;
import type { VerificationParserOutput as PublicType52 } from "@aiengineer/knowledge-conversion";
import type { VerificationParserRequest as PublicType53 } from "@aiengineer/knowledge-conversion";
type PublicValue54 = typeof import("@aiengineer/knowledge-documents").convertStructuralDocument;
type PublicValue55 = typeof import("@aiengineer/knowledge-documents").createSourceLocator;
type PublicValue56 = typeof import("@aiengineer/knowledge-documents").deterministicUuid;
type PublicValue57 = typeof import("@aiengineer/knowledge-documents").normalizeDocumentText;
type PublicValue58 = typeof import("@aiengineer/knowledge-documents").reconstructNodeSpan;
import type { StructuralBlock as PublicType59 } from "@aiengineer/knowledge-documents";
import type { StructuralDocument as PublicType60 } from "@aiengineer/knowledge-documents";
import type { StructuralDocumentInput as PublicType61 } from "@aiengineer/knowledge-documents";
type PublicValue62 = typeof import("@aiengineer/knowledge-documents").verifyNodeLocators;
type PublicValue63 = typeof import("@aiengineer/knowledge-chunking").CHUNK_PROFILE_TABLE;
type PublicValue64 = typeof import("@aiengineer/knowledge-chunking").chunkDocument;
import type { ChunkingResult as PublicType65 } from "@aiengineer/knowledge-chunking";
import type { ChunkProfile as PublicType66 } from "@aiengineer/knowledge-chunking";
import type { ChunkProfileRegistry as PublicType67 } from "@aiengineer/knowledge-chunking";
type PublicValue67 = typeof import("@aiengineer/knowledge-chunking").ChunkProfileRegistry;
import type { ChunkProfileTable as PublicType68 } from "@aiengineer/knowledge-chunking";
import type { ChunkQaResult as PublicType69 } from "@aiengineer/knowledge-chunking";
import type { ChunkStrategy as PublicType70 } from "@aiengineer/knowledge-chunking";
type PublicValue71 = typeof import("@aiengineer/knowledge-chunking").defaultChunkProfileRegistry;
import type { PreparedChunk as PublicType72 } from "@aiengineer/knowledge-chunking";
import type { PreparedChunkSpan as PublicType73 } from "@aiengineer/knowledge-chunking";
type PublicValue74 = typeof import("@aiengineer/knowledge-chunking").reconstructChunk;
type PublicValue75 = typeof import("@aiengineer/knowledge-chunking").tokenize;
type PublicValue76 = typeof import("@aiengineer/knowledge-chunking").TOKENIZER_VERSION;
type PublicValue77 = typeof import("@aiengineer/knowledge-chunking").validateChunks;
export {};
