// Compiler consumer probe generated from the merged baseline's public export symbols.
type PublicValue0 = typeof import("@aiengineer/knowledge-knowledge-db").assertHeadMatches;
import type { CatalogEntry as PublicType1 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue2 = typeof import("@aiengineer/knowledge-knowledge-db").CatalogEntrySchema;
type PublicValue3 = typeof import("@aiengineer/knowledge-knowledge-db").compareHeads;
type PublicValue4 = typeof import("@aiengineer/knowledge-knowledge-db").domainError;
import type { ExitClass as PublicType5 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue6 = typeof import("@aiengineer/knowledge-knowledge-db").getPage;
import type { HeadCheck as PublicType7 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue8 = typeof import("@aiengineer/knowledge-knowledge-db").infrastructureError;
type PublicValue9 = typeof import("@aiengineer/knowledge-knowledge-db").isKnowledgeError;
import type { KnowledgeError as PublicType10 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue10 = typeof import("@aiengineer/knowledge-knowledge-db").KnowledgeError;
type PublicValue11 = typeof import("@aiengineer/knowledge-knowledge-db").loadMaterialized;
type PublicValue12 = typeof import("@aiengineer/knowledge-knowledge-db").loadWorkspace;
import type { LocateOptions as PublicType13 } from "@aiengineer/knowledge-knowledge-db";
import type { MaterializeInput as PublicType14 } from "@aiengineer/knowledge-knowledge-db";
import type { MaterializeResult as PublicType15 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue16 = typeof import("@aiengineer/knowledge-knowledge-db").materializeScope;
import type { Page as PublicType17 } from "@aiengineer/knowledge-knowledge-db";
import type { PageOptions as PublicType18 } from "@aiengineer/knowledge-knowledge-db";
import type { QueryCatalog as PublicType19 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue20 = typeof import("@aiengineer/knowledge-knowledge-db").QueryCatalogSchema;
type PublicValue21 = typeof import("@aiengineer/knowledge-knowledge-db").requireCatalog;
type PublicValue22 = typeof import("@aiengineer/knowledge-knowledge-db").resolveWorkspaceDir;
import type { SchemaScope as PublicType23 } from "@aiengineer/knowledge-knowledge-db";
import type { SearchEntry as PublicType24 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue25 = typeof import("@aiengineer/knowledge-knowledge-db").SearchEntrySchema;
import type { SearchHit as PublicType26 } from "@aiengineer/knowledge-knowledge-db";
import type { SearchOptions as PublicType27 } from "@aiengineer/knowledge-knowledge-db";
import type { SearchResult as PublicType28 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue29 = typeof import("@aiengineer/knowledge-knowledge-db").searchWorkspace;
import type { TerminologyEntry as PublicType30 } from "@aiengineer/knowledge-knowledge-db";
import type { Workspace as PublicType31 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue32 = typeof import("@aiengineer/knowledge-knowledge-db").WORKSPACE_FILES;
import type { WorkspaceManifest as PublicType33 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue34 = typeof import("@aiengineer/knowledge-knowledge-db").applyDefaults;
import type { ArtifactLedger as PublicType35 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue35 = typeof import("@aiengineer/knowledge-knowledge-db").ArtifactLedger;
import type { ArtifactLedgerConfig as PublicType36 } from "@aiengineer/knowledge-knowledge-db";
import type { ArtifactRecord as PublicType37 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue38 = typeof import("@aiengineer/knowledge-knowledge-db").assertSingleReadStatement;
type PublicValue39 = typeof import("@aiengineer/knowledge-knowledge-db").bindKnowledgeClock;
type PublicValue40 = typeof import("@aiengineer/knowledge-knowledge-db").buildSpaceManifest;
import type { BuildSpaceManifestInput as PublicType41 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue42 = typeof import("@aiengineer/knowledge-knowledge-db").canonicalJson;
import type { Digest as PublicType43 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue44 = typeof import("@aiengineer/knowledge-knowledge-db").digestHexOf;
type PublicValue45 = typeof import("@aiengineer/knowledge-knowledge-db").digestOf;
type PublicValue46 = typeof import("@aiengineer/knowledge-knowledge-db").isDigest;
type PublicValue47 = typeof import("@aiengineer/knowledge-knowledge-db").isUuid;
import type { JsonPrimitive as PublicType48 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue49 = typeof import("@aiengineer/knowledge-knowledge-db").jsonSafeRow;
import type { JsonSchema as PublicType50 } from "@aiengineer/knowledge-knowledge-db";
import type { JsonValue as PublicType51 } from "@aiengineer/knowledge-knowledge-db";
import type { KnowledgeArtifactType as PublicType52 } from "@aiengineer/knowledge-knowledge-db";
import type { KnowledgeHead as PublicType53 } from "@aiengineer/knowledge-knowledge-db";
import type { LineageEdge as PublicType54 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue55 = typeof import("@aiengineer/knowledge-knowledge-db").MAX_OPERATIONS;
type PublicValue56 = typeof import("@aiengineer/knowledge-knowledge-db").MAX_STATEMENT_TIMEOUT_MS;
import type { OperationResult as PublicType57 } from "@aiengineer/knowledge-knowledge-db";
import type { OperationStatus as PublicType58 } from "@aiengineer/knowledge-knowledge-db";
import type { PutArtifactInput as PublicType59 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue60 = typeof import("@aiengineer/knowledge-knowledge-db").ReadContextSchema;
import type { ReadExecutor as PublicType61 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue61 = typeof import("@aiengineer/knowledge-knowledge-db").ReadExecutor;
import type { ReadExecutorConfig as PublicType62 } from "@aiengineer/knowledge-knowledge-db";
import type { ReadIntent as PublicType63 } from "@aiengineer/knowledge-knowledge-db";
import type { ReadIntentInput as PublicType64 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue65 = typeof import("@aiengineer/knowledge-knowledge-db").ReadIntentSchema;
import type { ReadOperation as PublicType66 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue67 = typeof import("@aiengineer/knowledge-knowledge-db").ReadOperationSchema;
type PublicValue68 = typeof import("@aiengineer/knowledge-knowledge-db").ReadRoleSchema;
import type { ReadSnapshot as PublicType69 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue70 = typeof import("@aiengineer/knowledge-knowledge-db").readSpaceManifest;
import type { ReadSpaceManifestInput as PublicType71 } from "@aiengineer/knowledge-knowledge-db";
import type { ResolvedParams as PublicType72 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue73 = typeof import("@aiengineer/knowledge-knowledge-db").resolveReferences;
import type { Row as PublicType74 } from "@aiengineer/knowledge-knowledge-db";
import type { RunIntentOptions as PublicType75 } from "@aiengineer/knowledge-knowledge-db";
import type { SchemaIssue as PublicType76 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue77 = typeof import("@aiengineer/knowledge-knowledge-db").sha256Hex;
type PublicValue78 = typeof import("@aiengineer/knowledge-knowledge-db").SLUG;
type PublicValue79 = typeof import("@aiengineer/knowledge-knowledge-db").SlugSchema;
type PublicValue80 = typeof import("@aiengineer/knowledge-knowledge-db").snapshotDigest;
import type { SnapshotExpectation as PublicType81 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue82 = typeof import("@aiengineer/knowledge-knowledge-db").SPACE_MANIFEST_SCHEMA_VERSION;
import type { SpaceManifest as PublicType83 } from "@aiengineer/knowledge-knowledge-db";
import type { SpaceManifestActivePublication as PublicType84 } from "@aiengineer/knowledge-knowledge-db";
import type { SpaceManifestAuthorityClass as PublicType85 } from "@aiengineer/knowledge-knowledge-db";
import type { SpaceManifestBudget as PublicType86 } from "@aiengineer/knowledge-knowledge-db";
import type { SpaceManifestEntry as PublicType87 } from "@aiengineer/knowledge-knowledge-db";
import type { SpaceManifestLiveFacts as PublicType88 } from "@aiengineer/knowledge-knowledge-db";
import type { SpaceManifestProfile as PublicType89 } from "@aiengineer/knowledge-knowledge-db";
import type { SpaceManifestProfileTable as PublicType90 } from "@aiengineer/knowledge-knowledge-db";
import type { SpaceManifestReads as PublicType91 } from "@aiengineer/knowledge-knowledge-db";
import type { SpaceManifestUnavailable as PublicType92 } from "@aiengineer/knowledge-knowledge-db";
import type { SqlReadInput as PublicType93 } from "@aiengineer/knowledge-knowledge-db";
import type { SqlReadResult as PublicType94 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue95 = typeof import("@aiengineer/knowledge-knowledge-db").UUID_PATTERN;
type PublicValue96 = typeof import("@aiengineer/knowledge-knowledge-db").UuidSchema;
type PublicValue97 = typeof import("@aiengineer/knowledge-knowledge-db").uuidv7;
type PublicValue98 = typeof import("@aiengineer/knowledge-knowledge-db").validatePersistedSnapshot;
type PublicValue99 = typeof import("@aiengineer/knowledge-knowledge-db").validateSchema;
type PublicValue100 = typeof import("@aiengineer/knowledge-knowledge-db").admissionIssues;
import type { AffectedRef as PublicType101 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue102 = typeof import("@aiengineer/knowledge-knowledge-db").ALIAS_KINDS;
import type { ApplyContext as PublicType103 } from "@aiengineer/knowledge-knowledge-db";
import type { ApplyOutcome as PublicType104 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue105 = typeof import("@aiengineer/knowledge-knowledge-db").applyPlan;
type PublicValue106 = typeof import("@aiengineer/knowledge-knowledge-db").applyRules;
type PublicValue107 = typeof import("@aiengineer/knowledge-knowledge-db").authenticateCanonicalContentEvidence;
import type { AuthenticatedContentEvidence as PublicType108 } from "@aiengineer/knowledge-knowledge-db";
import type { AuthoritativeClaim as PublicType109 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue110 = typeof import("@aiengineer/knowledge-knowledge-db").awaitWinnerReceipt;
type PublicValue111 = typeof import("@aiengineer/knowledge-knowledge-db").buildPlan;
import type { ChangedItem as PublicType112 } from "@aiengineer/knowledge-knowledge-db";
import type { ClaimEligibility as PublicType113 } from "@aiengineer/knowledge-knowledge-db";
import type { ClaimFacts as PublicType114 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue115 = typeof import("@aiengineer/knowledge-knowledge-db").classifyFailure;
type PublicValue116 = typeof import("@aiengineer/knowledge-knowledge-db").contentEvidenceAssessmentDigest;
import type { ContentLinkAuthority as PublicType117 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue118 = typeof import("@aiengineer/knowledge-knowledge-db").contentLinkEffect;
import type { ContentLinkExecutor as PublicType119 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue119 = typeof import("@aiengineer/knowledge-knowledge-db").ContentLinkExecutor;
import type { ContentLinkPlan as PublicType120 } from "@aiengineer/knowledge-knowledge-db";
import type { ContentLinkReceipt as PublicType121 } from "@aiengineer/knowledge-knowledge-db";
import type { ContentSourceReader as PublicType122 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue122 = typeof import("@aiengineer/knowledge-knowledge-db").ContentSourceReader;
import type { ContentSummaryPreparationResult as PublicType123 } from "@aiengineer/knowledge-knowledge-db";
import type { ContentSummaryPreparer as PublicType124 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue124 = typeof import("@aiengineer/knowledge-knowledge-db").ContentSummaryPreparer;
type PublicValue125 = typeof import("@aiengineer/knowledge-knowledge-db").DEFAULT_DUPLICATE_WAIT;
type PublicValue126 = typeof import("@aiengineer/knowledge-knowledge-db").deterministicId;
import type { DuplicateIdentity as PublicType127 } from "@aiengineer/knowledge-knowledge-db";
import type { DuplicateWaitPolicy as PublicType128 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue129 = typeof import("@aiengineer/knowledge-knowledge-db").ENTITY_REF_KINDS;
import type { EntityKind as PublicType130 } from "@aiengineer/knowledge-knowledge-db";
import type { EntityMatch as PublicType131 } from "@aiengineer/knowledge-knowledge-db";
import type { EventKind as PublicType132 } from "@aiengineer/knowledge-knowledge-db";
import type { EvidenceOracle as PublicType133 } from "@aiengineer/knowledge-knowledge-db";
import type { EvidenceRef as PublicType134 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue135 = typeof import("@aiengineer/knowledge-knowledge-db").EvidenceRefSchema;
import type { ExistingFacts as PublicType136 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue137 = typeof import("@aiengineer/knowledge-knowledge-db").ExtentSchema;
import type { FactGatheringDeps as PublicType138 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue139 = typeof import("@aiengineer/knowledge-knowledge-db").gatherFacts;
type PublicValue140 = typeof import("@aiengineer/knowledge-knowledge-db").IDENTIFIER_SCHEMES;
import type { IngestionExecutor as PublicType141 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue141 = typeof import("@aiengineer/knowledge-knowledge-db").IngestionExecutor;
import type { IngestionExecutorConfig as PublicType142 } from "@aiengineer/knowledge-knowledge-db";
import type { IngestionIntent as PublicType143 } from "@aiengineer/knowledge-knowledge-db";
import type { IngestionIntentInput as PublicType144 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue145 = typeof import("@aiengineer/knowledge-knowledge-db").IngestionIntentSchema;
import type { IngestionOptions as PublicType146 } from "@aiengineer/knowledge-knowledge-db";
import type { IngestionPlan as PublicType147 } from "@aiengineer/knowledge-knowledge-db";
import type { IngestionReceipt as PublicType148 } from "@aiengineer/knowledge-knowledge-db";
import type { IngestionRule as PublicType149 } from "@aiengineer/knowledge-knowledge-db";
import type { InlineClaim as PublicType150 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue151 = typeof import("@aiengineer/knowledge-knowledge-db").InlineClaimSchema;
type PublicValue152 = typeof import("@aiengineer/knowledge-knowledge-db").intentDigestOf;
type PublicValue153 = typeof import("@aiengineer/knowledge-knowledge-db").intentIdempotencyKey;
type PublicValue154 = typeof import("@aiengineer/knowledge-knowledge-db").isIdempotencyKeyCollision;
type PublicValue155 = typeof import("@aiengineer/knowledge-knowledge-db").isOfficiallyAdmittedVerdict;
type PublicValue156 = typeof import("@aiengineer/knowledge-knowledge-db").loadRules;
type PublicValue157 = typeof import("@aiengineer/knowledge-knowledge-db").loadVocabulary;
import type { NewSubject as PublicType158 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue159 = typeof import("@aiengineer/knowledge-knowledge-db").NO_RULES;
import type { PlanError as PublicType160 } from "@aiengineer/knowledge-knowledge-db";
import type { PlanExecutorIdentity as PublicType161 } from "@aiengineer/knowledge-knowledge-db";
import type { PlanFacts as PublicType162 } from "@aiengineer/knowledge-knowledge-db";
import type { PlannedAction as PublicType163 } from "@aiengineer/knowledge-knowledge-db";
import type { PlannedOutcome as PublicType164 } from "@aiengineer/knowledge-knowledge-db";
import type { PlannedProposal as PublicType165 } from "@aiengineer/knowledge-knowledge-db";
import type { PlannedSubject as PublicType166 } from "@aiengineer/knowledge-knowledge-db";
import type { Proposal as PublicType167 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue168 = typeof import("@aiengineer/knowledge-knowledge-db").proposalClaims;
type PublicValue169 = typeof import("@aiengineer/knowledge-knowledge-db").proposalEffect;
type PublicValue170 = typeof import("@aiengineer/knowledge-knowledge-db").proposalIdempotencyKey;
import type { ProposalKind as PublicType171 } from "@aiengineer/knowledge-knowledge-db";
import type { ProposalOf as PublicType172 } from "@aiengineer/knowledge-knowledge-db";
import type { ProposalOutcome as PublicType173 } from "@aiengineer/knowledge-knowledge-db";
import type { ProposalReceipt as PublicType174 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue175 = typeof import("@aiengineer/knowledge-knowledge-db").ProposalSchema;
type PublicValue176 = typeof import("@aiengineer/knowledge-knowledge-db").readContentLinkReceipt;
import type { ReceiptFailure as PublicType177 } from "@aiengineer/knowledge-knowledge-db";
import type { RegisterReportInput as PublicType178 } from "@aiengineer/knowledge-knowledge-db";
import type { RelationshipKind as PublicType179 } from "@aiengineer/knowledge-knowledge-db";
import type { RenderedAssertion as PublicType180 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue181 = typeof import("@aiengineer/knowledge-knowledge-db").renderReport;
type PublicValue182 = typeof import("@aiengineer/knowledge-knowledge-db").REPORT_BUCKET;
import type { ReportClaimReference as PublicType183 } from "@aiengineer/knowledge-knowledge-db";
import type { ReportEvidence as PublicType184 } from "@aiengineer/knowledge-knowledge-db";
import type { ReportPackageRead as PublicType185 } from "@aiengineer/knowledge-knowledge-db";
import type { ReportRegistration as PublicType186 } from "@aiengineer/knowledge-knowledge-db";
import type { ReportService as PublicType187 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue187 = typeof import("@aiengineer/knowledge-knowledge-db").ReportService;
import type { ReportServiceConfig as PublicType188 } from "@aiengineer/knowledge-knowledge-db";
import type { ReportStructure as PublicType189 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue190 = typeof import("@aiengineer/knowledge-knowledge-db").ReportStructureSchema;
import type { Rewrite as PublicType191 } from "@aiengineer/knowledge-knowledge-db";
import type { RuleApplication as PublicType192 } from "@aiengineer/knowledge-knowledge-db";
import type { RuleCheck as PublicType193 } from "@aiengineer/knowledge-knowledge-db";
import type { RuleCondition as PublicType194 } from "@aiengineer/knowledge-knowledge-db";
import type { RuleFacts as PublicType195 } from "@aiengineer/knowledge-knowledge-db";
import type { RuleSet as PublicType196 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue197 = typeof import("@aiengineer/knowledge-knowledge-db").slugify;
import type { StreamKind as PublicType198 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue199 = typeof import("@aiengineer/knowledge-knowledge-db").STRONG_MATCH;
import type { Subject as PublicType200 } from "@aiengineer/knowledge-knowledge-db";
import type { SubjectFacts as PublicType201 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue202 = typeof import("@aiengineer/knowledge-knowledge-db").subjectIdentity;
type PublicValue203 = typeof import("@aiengineer/knowledge-knowledge-db").subjectRefsOf;
type PublicValue204 = typeof import("@aiengineer/knowledge-knowledge-db").SubjectSchema;
type PublicValue205 = typeof import("@aiengineer/knowledge-knowledge-db").validateProposal;
import type { ValidationContext as PublicType206 } from "@aiengineer/knowledge-knowledge-db";
import type { Vocabulary as PublicType207 } from "@aiengineer/knowledge-knowledge-db";
import type { VocabularyIssue as PublicType208 } from "@aiengineer/knowledge-knowledge-db";
import type { WorldInterval as PublicType209 } from "@aiengineer/knowledge-knowledge-db";
type PublicValue210 = typeof import("@aiengineer/knowledge-knowledge-db").WorldIntervalSchema;
export {};
