import { VerificationReportLedgerSchema, type OperationContext, type VerificationArtifactHandle, type VerificationBundle, type VerificationPolicyDefinition } from "@aiengineer/knowledge-contracts";
import type { ClaimsVerificationResult, ReportVerificationResult } from "@aiengineer/knowledge-application";
import { replayVerificationAudit, VerificationSealPolicyCatalog } from "@aiengineer/knowledge-application";
import type { RegisterContentAddressedVerificationArtifactInput } from "@aiengineer/knowledge-persistence";
import { deterministicUuid } from "@aiengineer/knowledge-runtime";
import { canonicalizeJson, digestCanonicalJson, inspectAuditBundle, sha256Digest, verifyDeterministicBundle, verifyReportWideFromLedger, type RuntimePrincipalBinding, type VerificationAuditBundle } from "@aiengineer/knowledge-verification";
import { describe, expect, it } from "vitest";
import { createVerificationClaimsAuditSealer, type ClaimsSealerOptions } from "./verification-claims-sealer.js";
import type { VerificationMetricAuditSealerRepository } from "./verification-metric-sealer.js";

const tenantId="11111111-1111-4111-8111-111111111111",operationId="22222222-2222-4222-8222-222222222222";
const verifierAttemptId="33333333-3333-4333-8333-333333333333",missionId="44444444-4444-4444-8444-444444444444",workItemId="55555555-5555-4555-8555-555555555555";
const createdAt="2026-09-06T12:00:00.000Z";
type PrototypeFixture={prototypeClaimInput():{bundle:VerificationBundle;artifacts:readonly {artifactId:string;content:string|Uint8Array}[]};runtimePrincipals:RuntimePrincipalBinding};
const fixtureUrl=new URL("../../../packages/verification/src/deterministic/testing/prototype-parity.fixture.js",import.meta.url).href;

function handle(id:string,bytes:Uint8Array,parents:readonly string[]=[]):VerificationArtifactHandle{return{artifactId:id,tenantId,digest:sha256Digest(bytes),mediaType:"application/json",byteLength:bytes.byteLength,objectKey:`fixture/${id}`,createdAt,producerActivityId:"fixture",producerVersion:"fixture.v1",encryptionClass:"managed",retentionClass:"test",dataClassification:"restricted",parentArtifactIds:[...parents],...(parents.length?{transformationSignature:sha256Digest("fixture-transform")}:{})};}
class Repository implements VerificationMetricAuditSealerRepository{
 readonly artifacts=new Map<string,{handle:VerificationArtifactHandle;bytes:Uint8Array}>();readonly registrations:RegisterContentAddressedVerificationArtifactInput[]=[];readonly records:unknown[]=[];recovery?:VerificationAuditBundle;
 add(h:VerificationArtifactHandle,b:Uint8Array){this.artifacts.set(h.artifactId,{handle:h,bytes:b});}
 createTrustedArtifactResolver(){let ticket:string|undefined;return{authorizeArtifact:async({artifactId}:{artifactId:string})=>{ticket=artifactId;},hydrateRegisteredArtifact:async({artifactId}:{artifactId:string})=>{if(ticket!==artifactId)throw new Error("UNAUTHORIZED_HYDRATION");ticket=undefined;const item=this.artifacts.get(artifactId);if(!item)throw new Error("ARTIFACT_NOT_FOUND");return{registration:structuredClone(item.handle),bytes:Uint8Array.from(item.bytes)};}};}
 async registerContentAddressedArtifact(input:RegisterContentAddressedVerificationArtifactInput){this.registrations.push(input);const artifactId=deterministicUuid("claims-sealer-artifact",`${input.tenantId}:${input.artifactType}:${sha256Digest(input.bytes)}`);const prior=this.artifacts.get(artifactId);if(prior)return prior.handle;const h={...handle(artifactId,input.bytes,input.parentArtifactIds),mediaType:input.mediaType};this.add(h,Uint8Array.from(input.bytes));return h;}
 async recordVerificationRun(input:unknown){this.records.push(input);} async loadAuditBundleForOperationRecovery(){return this.recovery;}
 async loadAuditBundleArtifactForOperationRecovery(){if(!this.recovery)return undefined;return{auditBundle:this.recovery,manifestArtifact:this.artifacts.get(deterministicUuid("claims-sealer-artifact",`${tenantId}:verification_run_manifest:${sha256Digest(this.registrations.at(-1)!.bytes)}`))!.handle};}
}
const context=():OperationContext=>({contractVersion:"v1",tenantId,operationId,missionId,workItemId,attemptId:verifierAttemptId,correlationId:"claims-sealer",actor:{kind:"service",id:"66666666-6666-4666-8666-666666666666",serviceIdentity:"knowledge_worker"},capabilityVersion:"verification.v1",idempotencyKey:"claims-sealer-key",reason:"test"});
const lease={stepId:"77777777-7777-4777-8777-777777777777",leaseToken:"lease",fencingToken:9,holderIdentity:"claims-worker"};

async function fixture(mechanicallyValid=false){const {prototypeClaimInput,runtimePrincipals}=await import(fixtureUrl) as PrototypeFixture;const prototype=prototypeClaimInput();const bundle=structuredClone(prototype.bundle);bundle.assertions[0]!.kind="claim";bundle.assertions[0]!.claimType="other";bundle.metricObservations=[];
 const sourceBytes=new TextEncoder().encode(String(prototype.artifacts[0]!.content)),source=handle("88888888-8888-4888-8888-888888888888",sourceBytes);bundle.captures[0]!.contentArtifact=source;if(mechanicallyValid)bundle.assertions[0]!.evidence[0]!.fragment.representationArtifactId=source.artifactId;
 const claimsBytes=new TextEncoder().encode(canonicalizeJson({schemaVersion:"verification-claims-artifact.v1",bundle})),claims=handle("99999999-9999-4999-8999-999999999999",claimsBytes);
 const policy:VerificationPolicyDefinition={schemaVersion:"verification-policy.v1",policyVersion:bundle.policyVersion,definitionId:"claims-policy",criticalDownstreamUses:[],requireCrossFamilyForRisk:[],requireIndependentAuthorityForScopes:[],mixedEvidenceOutcome:"review",unknownCriticalOutcome:"review",authorityWithheldOutcome:"review",reviewAvailable:true};
 const policyBytes=new TextEncoder().encode(canonicalizeJson(policy)),policyArtifact=handle("aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",policyBytes);const repository=new Repository();repository.add(source,sourceBytes);repository.add(claims,claimsBytes);repository.add(policyArtifact,policyBytes);
 const deterministicResult=verifyDeterministicBundle({bundle,artifacts:[{artifactId:source.artifactId,content:sourceBytes}],runtimePrincipals});const verified:ClaimsVerificationResult={mode:"deterministic_only",deterministicResult,assertionsArtifact:claims,runtimePrincipals,producerAttemptId:bundle.producer.attemptId,sourceArtifacts:[source]};
 const policyCatalog=new VerificationSealPolicyCatalog([{tenantId,policyVersion:bundle.policyVersion,policyArtifact:{artifactId:policyArtifact.artifactId,digest:policyArtifact.digest}}]);
 const options:ClaimsSealerOptions={repository,policyCatalog,storageBucket:"test",runtime:{code:{gitSha:"fixture-sha",dirty:false,normalizerVersion:"RFC8785.v1"},platform:"test",deploymentId:bundle.verifier.deploymentId},now:()=>"2026-09-06T12:00:02.000Z"};
 return{bundle,repository,verified,runtimePrincipals,options,sealer:createVerificationClaimsAuditSealer(options)};}

async function reportFixture(){const base=await fixture(),reportBytes=new TextEncoder().encode("The exact report assertion."),report=handle("bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb",reportBytes);const bundle=structuredClone(base.bundle);bundle.assertions[0]!.kind="report_assertion";bundle.assertions[0]!.outputArtifactId=report.artifactId;bundle.assertions[0]!.outputRange={start:0,end:reportBytes.byteLength};const ledgerBytes=new TextEncoder().encode(canonicalizeJson({schemaVersion:"verification-report-ledger.v1",reportArtifact:report,bundle,assertions:[{assertion:bundle.assertions[0],exactText:"The exact report assertion.",start:0,end:reportBytes.byteLength,citationRequired:true,claimWeight:1,severity:"low",citations:[{citationId:"citation-1",evidenceId:bundle.assertions[0]!.evidence[0]!.evidenceId}],requiredQualifiers:["qualifier absent"]}]})),ledger=handle("cccccccc-cccc-4ccc-8ccc-cccccccccccc",ledgerBytes);base.repository.add(report,reportBytes);base.repository.add(ledger,ledgerBytes);const source=base.verified.sourceArtifacts[0]!,runtime=(await import(fixtureUrl) as PrototypeFixture).runtimePrincipals;const deterministicResult=verifyDeterministicBundle({bundle,artifacts:[{artifactId:source.artifactId,content:base.repository.artifacts.get(source.artifactId)!.bytes}],runtimePrincipals:runtime});const reportWide=verifyReportWideFromLedger("The exact report assertion.",VerificationReportLedgerSchema.parse(JSON.parse(new TextDecoder().decode(ledgerBytes))),deterministicResult);const verified:ReportVerificationResult={mode:"deterministic_only",deterministicResult,assertionsArtifact:ledger,reportArtifact:report,claimLedgerArtifact:ledger,reportWide,coverageScope:"producer_declared_assertions_only",runtimePrincipals:base.verified.runtimePrincipals,producerAttemptId:base.verified.producerAttemptId,sourceArtifacts:[source]};return{...base,bundle,verified};}

describe("VerificationClaimsAuditSealer",()=>{
 it("uses the native audit envelope, complete custody and distinct trusted attempts",async()=>{const test=await fixture();const sealed=await test.sealer.seal({verified:test.verified,context:context(),claim:lease,startedAt:createdAt});expect(["review","fail"]).toContain(sealed.policyOutcome);
  expect(test.repository.registrations.map(item=>item.artifactType)).toEqual(["verification_runtime_principal_binding","verification_bundle","deterministic_verification_result","verification_policy_inputs","verification_policy_decision","verification_run_manifest"]);
  const principalBinding=test.repository.registrations.find(item=>item.artifactType==="verification_runtime_principal_binding")!;
  expect(JSON.parse(new TextDecoder().decode(principalBinding.bytes))).toEqual(expect.objectContaining({schemaVersion:"verification-runtime-principal-binding.v1",tenantId,operationId,operationStepId:lease.stepId,producerAttemptId:test.verified.producerAttemptId,verifierAttemptId,assertionsArtifact:test.verified.assertionsArtifact,runtimePrincipals:test.runtimePrincipals}));
  expect(principalBinding.parentArtifactIds).toEqual([test.verified.assertionsArtifact.artifactId]);
  expect(test.repository.records[0]).toMatchObject({producerAttemptId:test.bundle.producer.attemptId,verifierAttemptId,operationId,lease});
  const audit=JSON.parse(new TextDecoder().decode(test.repository.registrations.at(-1)!.bytes)) as VerificationAuditBundle;expect((await inspectAuditBundle(audit)).valid).toBe(true);expect(audit.manifest.inputArtifacts.map(item=>item.artifactId)).toEqual(expect.arrayContaining([test.verified.assertionsArtifact.artifactId,test.verified.sourceArtifacts[0]!.artifactId]));
  const inputs=JSON.parse(new TextDecoder().decode(test.repository.registrations.find(item=>item.artifactType==="verification_policy_inputs")!.bytes));expect(inputs.assertions).toEqual([expect.objectContaining({assertionId:test.bundle.assertions[0]!.assertionId,authorityStatus:"unknown",criticalFactsKnown:false})]);
 });
 it("seals an authenticated runtime binding even when deterministic separation fails",async()=>{const test=await fixture();const selfBinding={...test.runtimePrincipals,verifierPrincipalDigest:test.runtimePrincipals.producerPrincipalDigest};const source=test.verified.sourceArtifacts[0]!,sourceBytes=test.repository.artifacts.get(source.artifactId)!.bytes;const deterministicResult=verifyDeterministicBundle({bundle:test.bundle,artifacts:[{artifactId:source.artifactId,content:sourceBytes}],runtimePrincipals:selfBinding});expect(deterministicResult.deploymentSeparation.status).toBe("not_established");const sealed=await test.sealer.seal({verified:{...test.verified,deterministicResult,runtimePrincipals:selfBinding},context:context(),claim:lease,startedAt:createdAt});expect(sealed.policyOutcome).not.toBe("pass");const binding=test.repository.registrations.find(item=>item.artifactType==="verification_runtime_principal_binding")!;expect(JSON.parse(new TextDecoder().decode(binding.bytes)).runtimePrincipals).toEqual(selfBinding);});
  it("recovers an exact sealed run without writes and rejects changed source custody",async()=>{const test=await fixture();const first=await test.sealer.seal({verified:test.verified,context:context(),claim:lease,startedAt:createdAt});test.repository.recovery=JSON.parse(new TextDecoder().decode(test.repository.registrations.at(-1)!.bytes));const count=test.repository.registrations.length;await expect(test.sealer.seal({verified:test.verified,context:context(),claim:lease,startedAt:"2026-09-06T13:00:00.000Z"})).resolves.toEqual(first);expect(test.repository.registrations).toHaveLength(count);
  await expect(test.sealer.seal({verified:{...test.verified,runtimePrincipals:{...test.runtimePrincipals,producerPrincipalDigest:sha256Digest("tampered-principal")}},context:context(),claim:lease,startedAt:createdAt})).rejects.toThrow("RECOVERY_DRIFT");
  const legacy=structuredClone(test.repository.recovery)!;legacy.manifest.inputArtifacts=legacy.manifest.inputArtifacts.filter(item=>item.mediaType!=="application/vnd.aiengineer.verification-runtime-principal-binding+json");test.repository.recovery=legacy;
  await expect(test.sealer.seal({verified:test.verified,context:context(),claim:lease,startedAt:createdAt})).resolves.toEqual(first);
  const replacementBytes=new TextEncoder().encode("changed"),replacement=handle(test.verified.sourceArtifacts[0]!.artifactId,replacementBytes);test.repository.add(replacement,replacementBytes);await expect(test.sealer.seal({verified:{...test.verified,sourceArtifacts:[replacement]},context:context(),claim:lease,startedAt:createdAt})).rejects.toThrow("RECOVERY_DRIFT");
 });
 it("makes missing report qualifiers a monotonic mechanical policy failure and replays the exact retained gate",async()=>{const test=await reportFixture();const sealed=await test.sealer.seal({verified:test.verified,context:context(),claim:lease,startedAt:createdAt});expect(sealed.policyOutcome).toBe("fail");const inputs=JSON.parse(new TextDecoder().decode(test.repository.registrations.find(item=>item.artifactType==="verification_policy_inputs")!.bytes));expect(inputs.deterministicResult).toMatchObject({status:"failed",semanticEligibility:false,summary:{failedCheckCodes:expect.arrayContaining(["REPORT_REQUIRED_QUALIFIERS_PRESERVED"])}});const result=test.repository.registrations.find(item=>item.artifactType==="deterministic_verification_result")!,gate=test.repository.registrations.find(item=>item.artifactType==="verification_report_result")!;expect(sha256Digest(result.bytes)).toBe(inputs.deterministicResult?digestCanonicalJson(inputs.deterministicResult):"");const gateBody=JSON.parse(new TextDecoder().decode(gate.bytes));expect(gateBody).toMatchObject({coverageScope:"producer_declared_assertions_only",deterministicResultDigest:sha256Digest(result.bytes)});const audit=JSON.parse(new TextDecoder().decode(test.repository.registrations.at(-1)!.bytes)) as VerificationAuditBundle;expect(audit.manifest.gateDigest).toBe(sha256Digest(gate.bytes));const replay=await replayVerificationAudit(audit,{artifactResolver:test.repository.createTrustedArtifactResolver(),runtimePrincipals:test.runtimePrincipals});expect(replay.deterministicResult).toMatchObject({status:"failed",summary:{failedCheckCodes:expect.arrayContaining(["REPORT_REQUIRED_QUALIFIERS_PRESERVED"])}});expect(replay.replayedArtifactIds).toContain(audit.manifest.outputArtifacts.find(item=>item.digest===audit.manifest.gateDigest)!.artifactId);});
 it("rejects retained report gate byte tampering before policy replay",async()=>{const test=await reportFixture();await test.sealer.seal({verified:test.verified,context:context(),claim:lease,startedAt:createdAt});const audit=JSON.parse(new TextDecoder().decode(test.repository.registrations.at(-1)!.bytes)) as VerificationAuditBundle;const gate=audit.manifest.outputArtifacts.find(item=>item.digest===audit.manifest.gateDigest)!;test.repository.artifacts.set(gate.artifactId,{handle:gate,bytes:new TextEncoder().encode("{\"tampered\":true}")});await expect(replayVerificationAudit(audit,{artifactResolver:test.repository.createTrustedArtifactResolver(),runtimePrincipals:test.runtimePrincipals})).rejects.toThrow(/ARTIFACT_(BYTE_LENGTH|DIGEST)_MISMATCH/u);});
 it("recovers the exact signed report gate and rejects incoming or stored gate drift",async()=>{const test=await reportFixture();const first=await test.sealer.seal({verified:test.verified,context:context(),claim:lease,startedAt:createdAt}),audit=JSON.parse(new TextDecoder().decode(test.repository.registrations.at(-1)!.bytes)) as VerificationAuditBundle;test.repository.recovery=structuredClone(audit);await expect(test.sealer.seal({verified:test.verified,context:context(),claim:lease,startedAt:createdAt})).resolves.toEqual(first);const changed={...test.verified,reportWide:{...test.verified.reportWide,distinctSourceFamilyCount:2}};await expect(test.sealer.seal({verified:changed,context:context(),claim:lease,startedAt:createdAt})).rejects.toThrow("RECOVERY_DRIFT");test.repository.recovery=structuredClone(audit);const gate=test.repository.recovery.manifest.outputArtifacts.find(item=>item.digest===test.repository.recovery!.manifest.gateDigest)!;gate.digest=sha256Digest("stored-gate-drift");await expect(test.sealer.seal({verified:test.verified,context:context(),claim:lease,startedAt:createdAt})).rejects.toThrow("RECOVERY_DRIFT");});
});


it("records semantic assessments and evidence lineage only after the mechanical gate",async()=>{
 const test=await fixture(true);expect(test.verified.deterministicResult.status).toBe("passed");
 const evidenceBytes=new TextEncoder().encode("retained judge fixture"),evidence=handle("dddddddd-dddd-4ddd-8ddd-dddddddddddd",evidenceBytes);test.repository.add(evidence,evidenceBytes);
 const assessment={assertionId:test.bundle.assertions[0]!.assertionId,verdict:"insufficient_evidence" as const,disposition:"review" as const,evidenceSupport:"unknown" as const,worldCorrectness:"not_assessed" as const,attributionFaithfulness:"not_assessed" as const,sourceAuthority:"not_assessed" as const,provenanceIntegrity:"satisfied" as const,judgeIdentities:[],supportingFragmentIds:[],contradictingFragmentIds:[],unsupportedFacets:["support"],reasonCodes:[],crossFamilySecondJudge:false,rawProviderConfidences:[]};
 let calls=0;const semanticStage={async grade(){calls++;return {assessments:[assessment],evidenceArtifacts:[evidence]};}};
 const sealer=createVerificationClaimsAuditSealer({...test.options,semanticStage});await sealer.seal({verified:test.verified,context:context(),claim:lease,startedAt:createdAt});expect(calls).toBe(1);
 const policyInput=test.repository.registrations.find(item=>item.artifactType==="verification_policy_inputs")!;expect(JSON.parse(new TextDecoder().decode(policyInput.bytes)).assertions[0].semantic).toEqual(assessment);expect(policyInput.parentArtifactIds).toContain(evidence.artifactId);
 const audit=JSON.parse(new TextDecoder().decode(test.repository.registrations.at(-1)!.bytes)) as VerificationAuditBundle;expect(audit.manifest.inputArtifacts).toContainEqual(evidence);
 const failed=await fixture();await createVerificationClaimsAuditSealer({...failed.options,semanticStage:{async grade(){throw new Error("MUST_NOT_GRADE_FAILED_MECHANICS");}}}).seal({verified:failed.verified,context:context(),claim:lease,startedAt:createdAt});
});

it("rejects a semantic profile outside the independently pinned source-authority receipt", async () => {
  const test = await fixture(true), assertionId = test.bundle.assertions[0]!.assertionId;
  const identity = { deploymentId: "independent-judge", provider: "fixture", family: "fixture", model: "fixture",
    capability: "llm_evidence_rubric" as const, graderVersion: "v1", promptDigest: digestCanonicalJson("prompt"),
    outputSchemaDigest: digestCanonicalJson("schema"), configurationDigest: digestCanonicalJson("configuration") };
  const semantic = { assertionId, verdict: "directly_supported" as const, disposition: "admit" as const,
    evidenceSupport: "satisfied" as const, worldCorrectness: "not_assessed" as const, attributionFaithfulness: "satisfied" as const,
    sourceAuthority: "not_assessed" as const, provenanceIntegrity: "satisfied" as const, judgeIdentities: [identity],
    supportingFragmentIds: [test.bundle.assertions[0]!.evidence[0]!.fragment.fragmentId], contradictingFragmentIds: [],
    unsupportedFacets: [], reasonCodes: [], crossFamilySecondJudge: false, rawProviderConfidences: [] };
  const sealer = createVerificationClaimsAuditSealer({ ...test.options,
    semanticStage: { async grade() { return { assessments: [semantic], evidenceArtifacts: test.verified.sourceArtifacts }; } },
    sourceAuthorityStage: { async assess() { return { sourceAssessments: [], assertions: new Map(),
      semanticProfileDigests: new Map([[assertionId, digestCanonicalJson("different-profile")]]), evidenceArtifacts: test.verified.sourceArtifacts }; } },
  });
  await expect(sealer.seal({ verified: test.verified, context: context(), claim: lease, startedAt: createdAt }))
    .rejects.toThrow("SOURCE_AUTHORITY_SEMANTIC_PROFILE_MISMATCH");
});

