import { z } from "zod";
import { A2AOperationBindingSchema } from "./a2a.js";
import { AuthorizationDecisionSchema } from "./identity.js";
import {
  ArtifactReferenceSchema,
  CanonicalRecordReferenceSchema,
  ImmutableResourceSchema,
  NonEmptyStringSchema,
  Sha256DigestSchema,
  SourceLocatorSchema,
  UuidSchema,
} from "./primitives.js";
import { VectorSpaceSchema } from "./spaces.js";

export const RetrievalIntentSchema = z.enum([
  "entity_discovery",
  "knowledge_evidence",
  "decision_support",
  "implementation_support",
  "tool_selection",
  "implementation_lookup",
]);
const FilterSchema = z.strictObject({
  field: NonEmptyStringSchema,
  op: z.enum(["eq", "neq", "in", "contains", "gte", "lte"]),
  value: z.union([
    z.string(),
    z.number(),
    z.boolean(),
    z.array(z.union([z.string(), z.number(), z.boolean()])),
  ]),
});
export const RetrievalPlanSchema = z
  .strictObject({
    policyVersion: UuidSchema,
    query: z.string().trim().min(1).max(4_000),
    intents: z.array(RetrievalIntentSchema).min(1),
    subqueries: z
      .array(
        z.strictObject({
          id: z.string().regex(/^[a-zA-Z0-9_-]+$/),
          text: z.string().trim().min(1).max(2_000),
          coverageRole: z.enum(["required", "supporting", "optional"]),
        }),
      )
      .min(1)
      .max(16),
    spaces: z.array(VectorSpaceSchema).min(1),
    anchors: z.strictObject({
      entities: z.array(UuidSchema),
      concepts: z.array(UuidSchema),
      useCases: z.array(NonEmptyStringSchema),
    }),
    hardFilters: z.array(FilterSchema).max(32),
    softBoosts: z.array(FilterSchema).max(32),
    temporalScope: z.strictObject({
      effectiveAfter: z.iso.datetime({ offset: true }).optional(),
      effectiveBefore: z.iso.datetime({ offset: true }).optional(),
      observedBefore: z.iso.datetime({ offset: true }).optional(),
    }),
    candidateK: z.int().min(1).max(1_000),
    finalK: z.int().min(1).max(100),
    graph: z.strictObject({
      maxDepth: z.int().min(0).max(3),
      allowedEdges: z.array(NonEmptyStringSchema).max(32),
    }),
    rerankerVersion: UuidSchema.optional(),
    abstention: z.strictObject({ minimumCoverage: z.number().min(0).max(1) }),
  })
  .superRefine((plan, context) => {
    if (plan.finalK > plan.candidateK)
      context.addIssue({
        code: "custom",
        message: "finalK cannot exceed candidateK",
        path: ["finalK"],
      });
    if (new Set(plan.spaces).size !== plan.spaces.length)
      context.addIssue({
        code: "custom",
        message: "spaces must be unique",
        path: ["spaces"],
      });
    if (
      new Set(plan.subqueries.map(({ id }) => id)).size !==
      plan.subqueries.length
    )
      context.addIssue({
        code: "custom",
        message: "subquery ids must be unique",
        path: ["subqueries"],
      });
  });
export type RetrievalPlan = z.infer<typeof RetrievalPlanSchema>;

/** The only accepted production retrieval mutation input. Query embeddings are generated by the service. */
export const RetrievalRunInputSchema = z.strictObject({
  plan: RetrievalPlanSchema,
  a2a: A2AOperationBindingSchema.optional(),
});
export type RetrievalRunInput = z.infer<typeof RetrievalRunInputSchema>;

export const ScoreComponentsSchema = z.strictObject({
  lexical: z.number().optional(),
  semantic: z.number().optional(),
  fusion: z.number().optional(),
  graph: z.number().optional(),
  reranker: z.number().optional(),
  final: z.number(),
});
export const RetrievalResultSchema = z.strictObject({
  resultType: NonEmptyStringSchema,
  canonicalRecord: CanonicalRecordReferenceSchema,
  searchProjectionId: UuidSchema,
  projectionVersionId: UuidSchema,
  matchExplanation: NonEmptyStringSchema,
  scores: ScoreComponentsSchema,
  matchedConstraints: z.array(NonEmptyStringSchema),
  evidenceLocators: z.array(SourceLocatorSchema).min(1),
  artifactHandles: z.array(ArtifactReferenceSchema),
  authority: z.enum(["canonical", "exploratory", "user_managed"]),
  verification: z.enum(["verified", "supported", "unverified", "contradicted"]),
  freshnessAt: z.iso.datetime({ offset: true }),
  temporalApplicability: NonEmptyStringSchema.optional(),
  flags: z.strictObject({
    contradicted: z.boolean(),
    corrected: z.boolean(),
    retracted: z.boolean(),
    deprecated: z.boolean(),
    superseded: z.boolean(),
  }),
  relatedRecords: z.array(CanonicalRecordReferenceSchema),
  retrievalRunId: UuidSchema,
  evidencePacketId: UuidSchema,
});
export type RetrievalResult = z.infer<typeof RetrievalResultSchema>;

export const EvidencePacketMemberSchema = z
  .strictObject({
    memberId: UuidSchema,
    canonicalRecord: CanonicalRecordReferenceSchema.optional(),
    faithfulSectionRepresentationId: UuidSchema.optional(),
    matchedProjectionId: UuidSchema,
    locators: z.array(SourceLocatorSchema).min(1),
    scores: ScoreComponentsSchema,
    channelExplanations: z.array(NonEmptyStringSchema),
    graphPaths: z.array(z.array(NonEmptyStringSchema)),
    authority: z.enum(["canonical", "exploratory", "user_managed"]),
    assurance: z.enum(["high", "medium", "low"]),
    freshAt: z.iso.datetime({ offset: true }),
    contradictionIds: z.array(UuidSchema),
    supersedesIds: z.array(UuidSchema),
    coveredSubqueryIds: z.array(NonEmptyStringSchema),
    artifactReferences: z.array(ArtifactReferenceSchema),
  })
  .refine(
    (member) =>
      member.canonicalRecord !== undefined ||
      member.faithfulSectionRepresentationId !== undefined,
    { message: "member requires a canonical record or faithful section" },
  );

export const EvidencePacketSchema = ImmutableResourceSchema.extend({
  retrievalRunId: UuidSchema,
  normalizedQuery: NonEmptyStringSchema,
  plan: RetrievalPlanSchema,
  authorization: AuthorizationDecisionSchema,
  procedureVersionIds: z.array(UuidSchema),
  members: z.array(EvidencePacketMemberSchema),
  omittedResults: z.array(
    z.strictObject({
      recordId: UuidSchema.optional(),
      reason: NonEmptyStringSchema,
    }),
  ),
  coverage: z.array(
    z.strictObject({
      subqueryId: NonEmptyStringSchema,
      coverage: z.number().min(0).max(1),
    }),
  ),
  abstention: z.strictObject({
    recommended: z.boolean(),
    reason: NonEmptyStringSchema.optional(),
  }),
  eventIds: z.array(UuidSchema),
  artifactIds: z.array(UuidSchema),
  receiptIds: z.array(UuidSchema),
});
export type EvidencePacket = z.infer<typeof EvidencePacketSchema>;
