// Stage 0 — primitives.
export {
  ZERO_SHA256_DIGEST,
  canonicalizeJson,
  digestCanonicalJson,
  fromPrototypeSha256,
  isSha256Digest,
  sha256Digest,
  toPrototypeSha256,
  type Sha256Digest,
} from "./canonical/index.js";
export {
  compareFractions,
  formatRoundedDecimal,
  parseDecimal,
  replayDecimalOperation,
  withinTolerance,
  type DecimalFraction,
} from "./decimal/index.js";
export {
  CLAIM_DECOMPOSITION_SCHEMA_VERSION,
  CORE_RESOLVER_VERSION,
  CROSS_FIELD_TOTAL_SCHEMA_VERSION,
  EXTRACTION_FIELD_EVIDENCE_SCHEMA_VERSION,
  EXTRACTION_FIELD_FRAGMENT_SCHEMA_VERSION,
  EXTRACTION_SCHEMA_GATE_VERSION,
  PROJECTION_RESOLVER_VERSION,
  REPORT_RESULT_SCHEMA_VERSION,
  SEMANTIC_JUDGE_SCHEMA_VERSION,
  SEMANTIC_RESPONSE_OBSERVATION_SCHEMA_VERSION,
  SEMANTIC_RUBRIC_VERSION,
  VERIFICATION_CONTRACT_VERSION,
} from "./versions.js";

// Stage 1 — capture integrity.
export {
  verifyDeterministicBundle,
  type DeterministicVerificationInput,
  type DeterministicVerificationOptions,
  type HydratedVerificationArtifact,
  type RuntimePrincipalBinding,
} from "./deterministic/index.js";

// Stage 2 — selector integrity.
export {
  ProjectionSelectorResolver,
  parseCanonicalProjection,
  projectionSelectorResolver,
  resolveEvidenceSelector,
  type CanonicalProjection,
  type DatasetProjection,
  type DomNode,
  type EvidenceSelection,
  type EvidenceSelectionRequest,
  type EvidenceSelectorResolver,
  type GeometryProjection,
  type HtmlDomProjection,
  type PaginatedApiProjection,
  type PdfTextProjection,
  type ProjectionAdmissionContext,
  type RepositoryProjection,
  type TableProjection,
  type TranscriptProjection,
} from "./evidence-selection/index.js";

// Stage 3 — mechanical correctness.
export {
  DEFAULT_EXTRACTION_SCHEMA_LIMITS,
  admitExtractionSchema,
  validateExtractionCandidate,
  verifyExtractionFields,
  verifyExtractionFieldsWithEvidence,
  type AcceptedExtractionLeaf,
  type AdmittedExtractionSchema,
  type CandidateValidationCheck,
  type CandidateValidationResult,
  type CrossFieldTotalRule,
  type DuplicateRecordRule,
  type ExtractionEvidence,
  type ExtractionEvidenceJsonScalar,
  type ExtractionFieldEvidenceResult,
  type ExtractionFieldRule,
  type ExtractionFieldVerificationInput,
  type ExtractionFieldVerificationResult,
  type ExtractionLeafDerivation,
  type ExtractionNormalizationOperation,
  type ExtractionNormalizationRule,
  type ExtractionSchemaAdmission,
  type ExtractionSchemaAdmissionLimits,
  type ExtractionSchemaCheck,
  type ExtractionVerificationCheck,
  type FieldComparison,
  type ImmutableExtractionRepresentation,
} from "./extraction/index.js";
export {
  acceptClaimDecomposition,
  applyReportWideMechanicalGates,
  claimClassifications,
  evaluateDecompositionProposal,
  verifyReportWide,
  verifyReportWideFromLedger,
  type AcceptedClaimDecomposition,
  type ClaimClassification,
  type ClaimDecompositionProposal,
  type DecompositionAnnotationCase,
  type DecompositionSegmentProposal,
  type ReportAssertionAssessment,
  type ReportCitationAssessment,
  type ReportVerificationSummary,
} from "./report/index.js";
export {
  assessSourceAuthority,
  type AuthorityDecision,
} from "./authority/index.js";

// Stage 4 — semantic support.
export {
  authorizeSemanticCase,
  mechanicalSemanticClosure,
  observeSemanticModelDrift,
  proposeUncitedEvidenceRescue,
  semanticCalibrationStatus,
  semanticJudgeInput,
  summarizeAttributionPerturbations,
  verifyAssertionSemantics,
  verifySemanticCase,
  type AssertionSemanticsInput,
  type AttributionPerturbationObservation,
  type AuthorizedSemanticCase,
  type AuthorizedSemanticFragment,
  type BoundedEvidenceRescuePort,
  type MechanicallySelectedFragment,
  type RescueBudget,
  type RescueCandidate,
  type SemanticCaseAuthorizationInput,
  type SemanticDriftObservation,
  type SemanticJudgeAdapter,
  type SemanticJudgeAdapters,
  type SemanticJudgeExecution,
  type SemanticJudgeInput,
  type SemanticJudgePort,
} from "./semantic/index.js";
export {
  GatewaySemanticJudgeAdapter,
  GatewayStructuredExtractionProvider,
  INTERFAZE_ENDPOINT,
  INTERFAZE_MODEL,
  InterfazeStructuredExtractionProvider,
  ProviderFailure,
  RecordedSemanticJudgeAdapter,
  ThreeWayNliSemanticJudgeAdapter,
  admitOutputSchema,
  boundedResponseBytes,
  gatewaySemanticConfigurationDigest,
  gatewaySemanticOutputSchemaDigest,
  gatewaySemanticPromptDigest,
  interfazeConfigurationDigest,
  interpretCapturedGatewaySemanticResponse,
  preflightJson,
  prepareGatewaySemanticRequest,
  providerDigest,
  providerRegistry,
  registeredProvider,
  requestSignal,
  requireActive,
  validateOutputAgainstSchema,
  type GatewaySemanticResponseObservation,
  type InterfazeCallRecord,
  type InterfazeExtractionResult,
  type InterfazeTask,
  type JsonObject,
  type JsonPreflightLimits,
  type JsonSchema,
  type NliClassifier,
  type ProviderArtifactSink,
  type ProviderExecution,
  type ProviderFailureCode,
  type ProviderModality,
  type ProviderModalityRegistration,
  type ProviderPromotionState,
  type ProviderRegistration,
} from "./providers/index.js";

// Stage 5 — provenance.
export {
  IN_TOTO_STATEMENT_TYPE,
  SLSA_PROVENANCE_V1_PREDICATE_TYPE,
  VERIFICATION_AUDIT_BUNDLE_BUILD_TYPE,
  VERIFICATION_DSSE_PAYLOAD_TYPE,
  auditBundleSignablePayload,
  createEd25519Signer,
  createEd25519Verifier,
  createVerificationDsseSlsaAttestation,
  inspectAuditBundle,
  inspectVerificationDsseSlsaAttestation,
  isLiteralExtractionAssertion,
  replayAuditBundle,
  sealAuditBundle,
  sealVerificationBenchmarkComparisonPublication,
  sealVerificationBenchmarkPublication,
  validateRecordedPolicyInputsArtifact,
  verificationDssePae,
  verificationManifestDigest,
  verificationManifestSignablePayload,
  verifyVerificationBenchmarkComparisonPublication,
  verifyVerificationBenchmarkPublication,
  type AuditBundleInspection,
  type AuditBundleSignatureVerifier,
  type AuditBundleSigner,
  type AuthorizedArtifactHydration,
  type DetachedAuditSeal,
  type TrustedArtifactResolver,
  type VerificationAuditBundle,
  type VerificationDsseEnvelope,
  type VerificationDsseSignature,
  type VerificationDsseSlsaAttestation,
  type VerificationDsseSlsaInspection,
  type VerificationDsseSlsaStatement,
  type VerificationDsseTrustedBinding,
  type VerificationPolicyBinding,
  type VerificationPolicyReplayPort,
  type VerificationReplayResult,
  type VerificationSemanticReplayPort,
} from "./provenance/index.js";

// Frozen prototype behavior; moves to a subpath export next.
export {
  prototypeSha256,
  resolvePrototypeJsonPointer,
  resolvePrototypeTextLocator,
  type PrototypeResolvedJsonPointer,
  type PrototypeResolvedTextLocator,
  type PrototypeTextLocator,
  type PrototypeTextOffsetBasis,
} from "./prototype-compat.js";
export {
  replayPrototypeArithmetic,
  verifyPrototypeBundle,
  type PrototypeArithmeticExpression,
} from "./prototype-bundle-compat.js";

// Contract types some consumers still reach through this package. Prefer
// importing them from `@aiengineer/knowledge-contracts` directly.
export type {
  Assertion,
  DeterministicVerificationResult,
  EvidenceEdge,
  Judgment,
  ResolvedSelector,
  VerificationArtifactHandle,
  VerificationBundle,
  VerificationMetricObservation,
  VerificationOperationContext,
  VerificationPolicyDecision,
  VerificationPolicyDefinition,
  VerificationRecordedPolicyInputs,
  VerificationRunManifest,
  VerificationSelector,
  VerificationSource,
  VerificationSourceCapture,
} from "@aiengineer/knowledge-contracts";
