import { describe,expect,it,vi } from "vitest";
import { KnowledgeClient } from "./client.js";

const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const digest=(value:string)=>`sha256:${value.repeat(64)}`;
const tenant=id(1),operationId=id(2);
const claims={verificationContractVersion:"verification.v1",tenantId:tenant,operationId,useCase:"verifyClaims",requestDigest:digest("a"),resultArtifact:{artifactId:id(3),digest:digest("b")},sealedRun:{runId:id(4),manifestDigest:digest("c"),manifestArtifact:{artifactId:id(5),digest:digest("d")},policyOutcome:"review",policy:{availability:"unavailable"}},output:{mode:"deterministic_only",deterministic:{status:"review_required",semanticEligibility:false,capturesTotal:1,capturesPassed:1,assertionsTotal:1,assertionsPassed:1,metricsTotal:0,metricsPassed:0,failedCheckCodes:[],reviewReasons:["POLICY_REVIEW"]},assertionsArtifact:{artifactId:id(6),digest:digest("e")}}};
const report={...claims,useCase:"verifyReport",output:{...claims.output,reportArtifact:{artifactId:id(7),digest:digest("f")},claimLedgerArtifact:claims.output.assertionsArtifact,reportWide:{claimWeightedCitationCompleteness:1,citationCorrectness:1,validPointerConditionalCitationCorrectness:1,pointerFailureCount:0,misplacedCitationCount:0,duplicateAssertionGroupCount:0,conflictAssertionGroupCount:0,missingQualifierCount:0,consistencyMismatchGroupCount:0,crossSectionMismatchCount:0,independentSourceFamilyCount:1,distinctSourceFamilyCount:1,unsupportedHighSeverityCount:0},coverageScope:"producer_declared_assertions_only",reportGateArtifact:{artifactId:id(8),digest:digest("1")}}};

describe("claims/report terminal client reads",()=>{
  it("uses family-specific GET routes and strict response schemas",async()=>{const urls:string[]=[];const fetch=vi.fn<typeof globalThis.fetch>(async input=>{const url=String(input);urls.push(url);return new Response(JSON.stringify(url.includes("/reports/")?report:claims),{status:200});});const client=new KnowledgeClient({baseUrl:"https://knowledge.example",fetch}),context={tenantId:tenant,correlationId:"terminal-read"};await expect(client.getVerificationClaimsResult(operationId,context)).resolves.toMatchObject({useCase:"verifyClaims"});await expect(client.getVerificationReportResult(operationId,context)).resolves.toMatchObject({useCase:"verifyReport"});expect(urls).toEqual([`https://knowledge.example/v1/verification/claims/${operationId}`,`https://knowledge.example/v1/verification/reports/${operationId}`]);});
  it("rejects raw evidence fields returned by a compromised transport",async()=>{const client=new KnowledgeClient({baseUrl:"https://knowledge.example",fetch:async()=>new Response(JSON.stringify({...claims,rawBundle:{secret:true}}),{status:200})});await expect(client.getVerificationClaimsResult(operationId,{tenantId:tenant,correlationId:"strict"})).rejects.toThrow();});
});
