import { generateKeyPairSync, randomUUID } from "node:crypto";
import { describe, expect, it } from "vitest";

import { createEveRuntimeAttestation, parseEveRuntimeAttestation, verifyEveRuntimeAttestation } from "./eve-runtime-attestation.js";

const id = () => randomUUID();
const payload = (now = 1_800_000_000) => ({ schemaVersion: "eve-runtime-attestation.v1" as const, issuer: "eve.host", keyId: "eve-1", jti: id(), issuedAt: now - 1, expiresAt: now + 60, audience: "knowledge-services:verification" as const, grantId: "grant-1", tenantId: id(), principal: { kind: "service" as const, id: id(), serviceIdentity: "mission_control_client" as const }, missionId: id(), workItemId: id(), attemptId: id(), operationId: id(), agentDeploymentId: "eve-verifier", capabilityVersion: "verification.v1", useCase: "verifyClaims" as const, requestDigest: `sha256:${"a".repeat(64)}` as const, idempotencyKey: "eve-host-key", externalExecution: { runtime: "eve" as const, sessionId: "session", turnId: "turn", toolCallId: "call", rootRunId: "root", runId: "session:turn" } });
const keys = generateKeyPairSync("ed25519");
const privateKeyPem = keys.privateKey.export({ type: "pkcs8", format: "pem" }).toString();
const publicKeyPem = keys.publicKey.export({ type: "spki", format: "pem" }).toString();

describe("Eve runtime attestation", () => {
  it("round-trips a canonical signed Eve lineage", async () => { const header = await createEveRuntimeAttestation(payload(), privateKeyPem); await expect(verifyEveRuntimeAttestation(header, { issuer: "eve.host", keyId: "eve-1", publicKeyPem, nowSeconds: 1_800_000_000 })).resolves.toMatchObject({ externalExecution: { runId: "session:turn" } }); });
  it("rejects a tampered signature, wrong key and expired header", async () => { const header = await createEveRuntimeAttestation(payload(), privateKeyPem); const decoded = parseEveRuntimeAttestation(header); const altered = Buffer.from(JSON.stringify({ ...decoded, payload: { ...decoded.payload, grantId: "other" } }), "utf8").toString("base64url"); await expect(verifyEveRuntimeAttestation(altered, { issuer: "eve.host", keyId: "eve-1", publicKeyPem, nowSeconds: 1_800_000_000 })).rejects.toThrow(); await expect(verifyEveRuntimeAttestation(header, { issuer: "wrong", keyId: "eve-1", publicKeyPem, nowSeconds: 1_800_000_000 })).rejects.toThrow("TRUST"); await expect(verifyEveRuntimeAttestation(header, { issuer: "eve.host", keyId: "eve-1", publicKeyPem, nowSeconds: 1_800_000_100 })).rejects.toThrow("TIME"); });
  it("rejects noncanonical and duplicate-key encodings before authority verification", async () => { const header = await createEveRuntimeAttestation(payload(), privateKeyPem); const decoded = Buffer.from(header, "base64url").toString("utf8"); expect(() => parseEveRuntimeAttestation(Buffer.from(decoded.replace(",", ", "), "utf8").toString("base64url"))).toThrow("NON_CANONICAL"); expect(() => parseEveRuntimeAttestation(Buffer.from('{"payload":{},"payload":{}}', "utf8").toString("base64url"))).toThrow(); });
  it("rejects non-Ed25519 signing and verification keys", async () => { const rsa = generateKeyPairSync("rsa", { modulusLength: 2048 }); const rsaPrivate = rsa.privateKey.export({ type: "pkcs8", format: "pem" }).toString(), rsaPublic = rsa.publicKey.export({ type: "spki", format: "pem" }).toString(); await expect(createEveRuntimeAttestation(payload(), rsaPrivate)).rejects.toThrow("PRIVATE_KEY_ALGORITHM"); const header = await createEveRuntimeAttestation(payload(), privateKeyPem); await expect(verifyEveRuntimeAttestation(header, { issuer: "eve.host", keyId: "eve-1", publicKeyPem: rsaPublic, nowSeconds: 1_800_000_000 })).rejects.toThrow("PUBLIC_KEY_ALGORITHM"); });
});
