import { access, copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { canonicalJson, sha256Digest } from "@aiengineer/knowledge-domain";

export const EMBEDDING_BUNDLE_SCHEMA_VERSION = "ai-engineer-embedding-bundle/0.1.0" as const;
export const EMBEDDING_BUNDLE_FIXTURE_VERSION = "embedding-bundle-seed-2026-09-01" as const;
export const EMBEDDING_BUNDLE_VIDEO_IDS = ["kTnfJszFxCg", "bk0TmxoZlUY", "rmvDxxNubIg"] as const;
export const EMBEDDING_BUNDLE_TENANT_ID = "00000000-0000-7000-8000-000000000001";
export type EmbeddingBundleVideoId = (typeof EMBEDDING_BUNDLE_VIDEO_IDS)[number];
export interface BundleEntity { slug: string; display_name: string }
export interface SelectedBundleDocument { id: string; document_kind: string; title: string; canonical_url: string; source_role: "official" | "primary" | "authoritative_secondary"; publisher: string; source_class: string; target_vector_spaces: string[]; text: string; entity_slugs: string[] }
export interface BundleClaim { id: string; statement: string; claim_role: string; problem?: string; mechanism?: string; applicability?: string; limitations?: string; attribution: string; locator_excerpt: string; related_entities: string[] }
export interface EmbeddingBundle { schema_version: typeof EMBEDDING_BUNDLE_SCHEMA_VERSION; store_class: "internal_exploratory"; video_id: string; title: string; research_as_of: string; primary: { engineer: BundleEntity; organization: BundleEntity }; selected_documents: SelectedBundleDocument[]; engineering_claims: BundleClaim[] }
export interface LoadedEmbeddingBundle { bundle: EmbeddingBundle; digest: string; sourcePath: string; fixtureVersion: typeof EMBEDDING_BUNDLE_FIXTURE_VERSION }
const DOCUMENT_KINDS = new Set(["talk_transcript", "research_summary", "entity_profile", "official_homepage", "official_docs", "official_repository", "official_blog", "paper_abstract", "case_study"]);
function requireString(value: unknown, path: string): asserts value is string { if (typeof value !== "string" || !value.trim()) throw new Error(`Invalid ${path}`); }
export function validateEmbeddingBundle(value: unknown): EmbeddingBundle { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("Bundle must be an object"); const bundle = value as Record<string, unknown>; if (bundle.schema_version !== EMBEDDING_BUNDLE_SCHEMA_VERSION) throw new Error("Unsupported embedding bundle schema"); if (bundle.store_class !== "internal_exploratory") throw new Error("Fixture must remain internal_exploratory"); requireString(bundle.video_id, "video_id"); requireString(bundle.title, "title"); requireString(bundle.research_as_of, "research_as_of"); if (!bundle.primary || typeof bundle.primary !== "object") throw new Error("Invalid primary"); for (const role of ["engineer", "organization"] as const) { const entity = (bundle.primary as Record<string, unknown>)[role] as Record<string, unknown>; requireString(entity?.slug, `primary.${role}.slug`); requireString(entity?.display_name, `primary.${role}.display_name`); } if (!Array.isArray(bundle.selected_documents) || bundle.selected_documents.length === 0) throw new Error("selected_documents must be non-empty"); for (const [index, item] of bundle.selected_documents.entries()) { const document = item as Record<string, unknown>; for (const field of ["id", "document_kind", "title", "canonical_url", "source_role", "publisher", "source_class", "text"] as const) requireString(document[field], `selected_documents.${index}.${field}`); if (!DOCUMENT_KINDS.has(document.document_kind as string)) throw new Error(`Invalid document kind ${String(document.document_kind)}`); if (!Array.isArray(document.target_vector_spaces) || !Array.isArray(document.entity_slugs)) throw new Error(`Invalid document arrays at ${index}`); new URL(document.canonical_url as string); } if (!Array.isArray(bundle.engineering_claims)) throw new Error("engineering_claims must be an array"); for (const [index, item] of bundle.engineering_claims.entries()) { const claim = item as Record<string, unknown>; for (const field of ["id", "statement", "claim_role", "attribution", "locator_excerpt"] as const) requireString(claim[field], `engineering_claims.${index}.${field}`); if (!Array.isArray(claim.related_entities)) throw new Error(`Invalid claim related_entities at ${index}`); } return structuredClone(value) as EmbeddingBundle; }
async function exists(path: string) { return access(path).then(() => true, () => false); }
export async function findEmbeddingBundleSeed(start = dirname(fileURLToPath(import.meta.url))): Promise<string> { let cursor = resolve(start); for (let depth = 0; depth < 10; depth++) { for (const candidate of [join(cursor, "fixtures", EMBEDDING_BUNDLE_FIXTURE_VERSION), join(cursor, "research_starter_pre_research_agent", "experiments", EMBEDDING_BUNDLE_FIXTURE_VERSION)]) if (await exists(join(candidate, "outputs", "catalog.json"))) return candidate; const parent = dirname(cursor); if (parent === cursor) break; cursor = parent; } throw new Error(`Could not find ${EMBEDDING_BUNDLE_FIXTURE_VERSION}`); }
export async function loadEmbeddingBundles(seedRoot?: string): Promise<readonly LoadedEmbeddingBundle[]> { const root = seedRoot ?? await findEmbeddingBundleSeed(); const loaded: LoadedEmbeddingBundle[] = []; for (const videoId of EMBEDDING_BUNDLE_VIDEO_IDS) { const originalPath = join(root, "videos", videoId, "outputs", "embedding-bundle.json"); const importedPath = join(root, "videos", videoId, "embedding-bundle.json"); const sourcePath = await exists(originalPath) ? originalPath : importedPath; const parsed: unknown = JSON.parse(await readFile(sourcePath, "utf8")); const bundle = validateEmbeddingBundle(parsed); if (bundle.video_id !== videoId) throw new Error(`Fixture video mismatch for ${videoId}`); loaded.push({ bundle, digest: sha256Digest(JSON.parse(canonicalJson(JSON.parse(JSON.stringify(bundle))))), sourcePath, fixtureVersion: EMBEDDING_BUNDLE_FIXTURE_VERSION }); } return loaded; }
export async function importEmbeddingBundleFixtures(destination: string, seedRoot?: string) { const root = seedRoot ?? await findEmbeddingBundleSeed(); const loaded = await loadEmbeddingBundles(root); const manifest = { fixtureVersion: EMBEDDING_BUNDLE_FIXTURE_VERSION, schemaVersion: EMBEDDING_BUNDLE_SCHEMA_VERSION, sourceRoot: root, importedAtPolicy: "not-recorded-for-determinism", bundles: loaded.map((item) => ({ videoId: item.bundle.video_id, digest: item.digest, relativePath: `videos/${item.bundle.video_id}/embedding-bundle.json` })) }; for (const item of loaded) { const target = join(destination, "videos", item.bundle.video_id, "embedding-bundle.json"); await mkdir(dirname(target), { recursive: true }); await copyFile(item.sourcePath, target); } await mkdir(destination, { recursive: true }); await writeFile(join(destination, "manifest.json"), `${canonicalJson(manifest)}\n`, "utf8"); return manifest; }
