import { describe, expect, it } from "vitest";
import { digestBytes, InMemoryArtifactStore } from "@aiengineer/knowledge-runtime";
import { BoundedManualUploadAdapter, FirecrawlAcquisitionAdapter, IdentityBoundPaperAcquisitionAdapter, ImmutableRepositoryAcquisitionAdapter, normalizePaperIdentifier, type AcquisitionRequest, type ManualUploadRecord, type PaperResolution } from "./index.js";

const bytes = (value: string) => new TextEncoder().encode(value);
const resolver = { resolve: async () => ["93.184.216.34"] };
const targetPolicy = { allowedProtocols: ["https:"] as const, allowedPorts: [443], maximumRedirects: 2, timeoutMs: 1000, maximumBytes: 10_000, maximumDecompressionRatio: 10 };
function request(target: AcquisitionRequest["target"], maximumBytes = 10_000): AcquisitionRequest { return { tenantId: "tenant-1", purpose: "test", target, expectedSourceClass: "official", preferredMediaTypes: ["text/markdown"], egressProfile: "public-web", maximumBytes, renderingPolicy: "allowed", interactionPolicy: "none", classification: "public", expectedOutputs: ["source_native"] }; }

describe("FirecrawlAcquisitionAdapter", () => {
  const config = { endpoint: "https://api.firecrawl.dev/v2/scrape", authenticationReference: "secret://firecrawl", apiVersion: "v2", timeoutMs: 1000, maximumResponseBytes: 1_000, maximumDecompressionRatio: 2, allowedApiHosts: ["api.firecrawl.dev"], targetPolicy };
  it("uses referenced auth, redacts it, and replays idempotently", async () => { const store = new InMemoryArtifactStore(); const secret = "fc-secret-value"; let observed: RequestInit | undefined; const adapter = new FirecrawlAcquisitionAdapter(store, config, { resolve: async () => secret }, resolver, async (_url, init) => { observed = init; return Response.json({ success: true, id: "job-1", creditsUsed: 2, data: { markdown: "# Page", metadata: { authorization: secret, nested: secret } } }); }); const plan = await adapter.plan({ ...request({ kind: "http", url: "https://example.com/docs" }), authenticationReference: "secret://firecrawl" }); const admitted = { ...plan, admissionId: "fc-1" }; const first = await adapter.execute(admitted); const second = await adapter.execute(admitted); expect(new Headers(observed?.headers).get("authorization")).toBe(`Bearer ${secret}`); expect(observed?.redirect).toBe("manual"); expect(first.artifacts.map((x) => x.artifactId)).toEqual(second.artifacts.map((x) => x.artifactId)); expect(first.observations).toContainEqual({ key: "provider_job_id", value: "job-1" }); const native = await store.get("tenant-1", first.artifacts[0]!.digest); expect(new TextDecoder().decode(native)).not.toContain(secret); expect((await adapter.verify(first)).accepted).toBe(true); });
  it("rejects SSRF targets, provider redirects, size excess, and decompression bombs", async () => { const make = (response: Response) => new FirecrawlAcquisitionAdapter(new InMemoryArtifactStore(), { ...config, maximumResponseBytes: 50 }, { resolve: async () => "secret" }, resolver, async () => response); await expect(make(Response.json({})).plan(request({ kind: "http", url: "https://127.0.0.1/x" }))).rejects.toThrow("ADDRESS_DENIED"); const execute = async (response: Response, id: string) => { const adapter = make(response); const plan = await adapter.plan(request({ kind: "http", url: "https://example.com" })); return adapter.execute({ ...plan, admissionId: id }); }; await expect(execute(new Response(null, { status: 307, headers: { location: "https://evil.example" } }), "r")).rejects.toThrow("PROVIDER_REDIRECT_DENIED"); await expect(execute(new Response("x".repeat(51)), "s")).rejects.toThrow("BYTE_LIMIT_EXCEEDED"); await expect(execute(new Response("x".repeat(30), { headers: { "content-encoding": "gzip", "content-length": "10" } }), "z")).rejects.toThrow("DECOMPRESSION_RATIO_EXCEEDED"); });
});

describe("BoundedManualUploadAdapter", () => {
  const attestation = { uploadId: "upload-1", origin: "console", method: "signed upload", acquiredAt: "2026-09-03T12:00:00Z", accessAndRightsContext: "owner supplied", automaticFailureReason: "" };
  function make(record: ManualUploadRecord, maximumBytes = 20) { return new BoundedManualUploadAdapter(new InMemoryArtifactStore(), { get: async () => record }, { maximumBytes, maximumPathLength: 80, allowedMediaTypes: ["text/plain"] }); }
  async function execute(adapter: BoundedManualUploadAdapter, origin = "console", id = "u") { const plan = await adapter.plan(request({ kind: "upload", uploadId: "upload-1", declaredOrigin: origin })); return adapter.execute({ ...plan, admissionId: id }); }
  it("bounds, attests, hashes, and stores uploads idempotently", async () => { const content = bytes("bounded"); const adapter = make({ uploadId: "upload-1", relativePath: "notes/source.txt", mediaType: "text/plain", bytes: content, declaredDigest: digestBytes(content), attestation }); const first = await execute(adapter); const second = await execute(adapter); expect(first.artifacts[0]?.artifactId).toBe(second.artifacts[0]?.artifactId); expect((await adapter.verify(first)).accepted).toBe(true); });
  it("rejects traversal, oversize, digest mismatch, and false origin", async () => { const base = { uploadId: "upload-1", relativePath: "safe.txt", mediaType: "text/plain", bytes: bytes("small"), attestation }; await expect(execute(make({ ...base, relativePath: "../secret.txt" }))).rejects.toThrow("UPLOAD_PATH_TRAVERSAL"); await expect(execute(make({ ...base, bytes: bytes("large") }, 2))).rejects.toThrow("BYTE_LIMIT_EXCEEDED"); await expect(execute(make({ ...base, declaredDigest: "sha256:bad" }))).rejects.toThrow("UPLOAD_DIGEST_MISMATCH"); await expect(execute(make(base), "email")).rejects.toThrow("UPLOAD_ATTESTATION_INVALID"); });
});

describe("ImmutableRepositoryAcquisitionAdapter", () => {
  const sha = "a".repeat(40); const archiveBytes = bytes("archive"); const entries = [{ path: "LICENSE", bytes: bytes("MIT") }, { path: "src/index.ts", bytes: bytes("const apiKey = \"super-secret-value\";") }, { path: "pnpm-lock.yaml", bytes: bytes("lock") }]; const policy = { maximumArchiveBytes: 100, maximumExpandedBytes: 100, maximumEntries: 10, maximumFileBytes: 80 };
  const target = { kind: "repository", host: "github.com", owner: "org", repository: "repo", commitSha: sha } as const;
  it("binds the archive to a SHA and records license and redacted secret findings", async () => { const adapter = new ImmutableRepositoryAcquisitionAdapter(new InMemoryArtifactStore(), { fetchArchive: async () => ({ resolvedCommitSha: sha, archiveBytes, entries }) }, policy); const plan = await adapter.plan(request(target)); const admitted = { ...plan, admissionId: "repo" }; const first = await adapter.execute(admitted); const second = await adapter.execute(admitted); const manifest = await adapter.inspectManifest(admitted); expect(manifest.licenseFiles).toEqual(["LICENSE"]); expect(manifest.secretLikeFindings).toEqual([{ path: "src/index.ts", kind: "generic_assignment" }]); expect(JSON.stringify(manifest)).not.toContain("super-secret-value"); expect(first.artifacts.map((x) => x.artifactId)).toEqual(second.artifacts.map((x) => x.artifactId)); });
  it("rejects mutable identity, substitution, traversal, symlinks, and expansion", async () => { const adapterFor = (override: object, expanded = 100) => new ImmutableRepositoryAcquisitionAdapter(new InMemoryArtifactStore(), { fetchArchive: async () => ({ resolvedCommitSha: sha, archiveBytes, entries, ...override }) }, { ...policy, maximumExpandedBytes: expanded }); const invalid = adapterFor({}); await expect(invalid.plan(request({ ...target, commitSha: "main" }))).rejects.toThrow("IMMUTABLE_COMMIT_SHA_REQUIRED"); async function run(adapter: ImmutableRepositoryAcquisitionAdapter, id: string) { const plan = await adapter.plan(request(target)); return adapter.execute({ ...plan, admissionId: id }); } await expect(run(adapterFor({ resolvedCommitSha: "b".repeat(40) }), "a")).rejects.toThrow("COMMIT_IDENTITY_MISMATCH"); await expect(run(adapterFor({ entries: [{ path: "../x", bytes: bytes("x") }] }), "b")).rejects.toThrow("ARCHIVE_PATH_TRAVERSAL"); await expect(run(adapterFor({ entries: [{ path: "x", bytes: bytes("x"), kind: "symlink" }] }), "c")).rejects.toThrow("ARCHIVE_SYMLINK_DENIED"); await expect(run(adapterFor({ entries: [{ path: "x", bytes: bytes("123") }] }, 2), "d")).rejects.toThrow("ARCHIVE_EXPANSION_LIMIT_EXCEEDED"); });
});

describe("IdentityBoundPaperAcquisitionAdapter", () => {
  const resolution = (kind: "doi" | "arxiv" | "openreview", identifier: string): PaperResolution => ({ identifierKind: kind, identifier, title: "Paper", authors: ["Author"], revision: "v1", publicationState: "published", correctionState: "none", representations: [{ mediaType: "application/pdf", url: "https://papers.example/p.pdf" }] });
  it("normalizes all identities and requires matching provider identity", async () => { expect(normalizePaperIdentifier("doi", "https://doi.org/10.1234/ABC")).toBe("10.1234/abc"); expect(normalizePaperIdentifier("arxiv", "arXiv:2401.12345v2")).toBe("2401.12345v2"); expect(normalizePaperIdentifier("openreview", "https://openreview.net/forum?id=abcdef_12")).toBe("abcdef_12"); const adapter = new IdentityBoundPaperAcquisitionAdapter(new InMemoryArtifactStore(), { resolve: async (kind, identifier) => ({ resolution: resolution(kind, identifier), representations: [{ mediaType: "application/pdf", url: "https://papers.example/p.pdf", bytes: bytes("pdf") }] }) }); const plan = await adapter.plan(request({ kind: "paper", identifierKind: "doi", identifier: "DOI:10.1234/ABC" })); const result = await adapter.execute({ ...plan, admissionId: "paper" }); expect(result.discoveredCanonicalIdentifiers).toEqual(["doi:10.1234/abc"]); expect((await adapter.verify(result)).accepted).toBe(true); });
  it("rejects malformed and substituted identities", async () => { const adapter = new IdentityBoundPaperAcquisitionAdapter(new InMemoryArtifactStore(), { resolve: async () => ({ resolution: resolution("doi", "10.9999/wrong"), representations: [{ mediaType: "application/pdf", url: "https://papers.example/p.pdf", bytes: bytes("pdf") }] }) }); await expect(adapter.plan(request({ kind: "paper", identifierKind: "doi", identifier: "not-doi" }))).rejects.toThrow("DOI_IDENTITY_INVALID"); const plan = await adapter.plan(request({ kind: "paper", identifierKind: "doi", identifier: "10.1234/right" })); await expect(adapter.execute({ ...plan, admissionId: "wrong" })).rejects.toThrow("PAPER_IDENTITY_MISMATCH"); });
});
