import { createHash } from "node:crypto";
export const verificationDriftDimensions=["provider","model","parser","grader","policy"] as const;
export type DriftDimension=typeof verificationDriftDimensions[number]; export type DriftDisposition="revalidate"|"review_required";
export interface DriftObservation { readonly tenantId:string; readonly observationArtifactId:string; readonly observationDigest:`sha256:${string}`; readonly dimensions:readonly DriftDimension[]; readonly sourceOperationId:string; readonly disposition:DriftDisposition; readonly reviewReason?:string; }
export interface DurableDriftPlan extends DriftObservation { readonly idempotencyKey:string; }
/** Atomic persistence: a durable plan and exactly one action outbox message are committed together. */
export interface DriftPlannerPort { persistPlan(input:DurableDriftPlan):Promise<"planned"|"already_planned">; }
const isDimension=(value:unknown):value is DriftDimension=>typeof value==="string"&&(verificationDriftDimensions as readonly string[]).includes(value);
export function semanticObservationDrift(value:{readonly tenantId:string;readonly observationArtifact:{readonly artifactId:string;readonly digest:`sha256:${string}`};readonly context:{readonly operationId:string};readonly revalidationRequired:boolean;readonly modelStatus:"matched"|"missing"|"mismatch";readonly disposition:DriftDisposition;readonly reviewReason?:string;}):DriftObservation|undefined { if(!value.revalidationRequired)return undefined; return {tenantId:value.tenantId,observationArtifactId:value.observationArtifact.artifactId,observationDigest:value.observationArtifact.digest,sourceOperationId:value.context.operationId,dimensions:["model"],disposition:value.disposition,...(value.reviewReason?{reviewReason:value.reviewReason}:{})}; }
export class VerificationDriftRevalidationPlanner { constructor(private readonly port:DriftPlannerPort){} async plan(value:DriftObservation):Promise<"planned"|"already_planned"> { const dimensions=[...new Set(value.dimensions)].sort(); if(!value.tenantId||!value.observationArtifactId||!value.sourceOperationId||!/^sha256:[a-f0-9]{64}$/.test(value.observationDigest)||dimensions.length<1||!dimensions.every(isDimension)||(value.disposition!=="revalidate"&&value.disposition!=="review_required")||(value.disposition==="review_required"&&(!value.reviewReason||value.reviewReason.length>256)))throw new Error("DRIFT_REVALIDATION_INPUT_INVALID"); const idempotencyKey="vr031:"+createHash("sha256").update([value.tenantId,value.observationArtifactId,value.observationDigest,dimensions.join(","),value.disposition,value.reviewReason??""].join(":")) .digest("hex"); return this.port.persistPlan({...value,dimensions:dimensions as DriftDimension[],idempotencyKey}); } }
