import { UuidSchema, VerificationClaimsOperationResultSchema, VerificationClaimsReportTerminalResourceSchema, VerificationReportOperationResultSchema, type VerificationArtifactHandle, type VerificationClaimsReportTerminalResource } from "@aiengineer/knowledge-contracts";
import { deepFreeze } from "@aiengineer/knowledge-domain";
export type VerificationClaimsReportReadState = "pending" | "failed" | "cancelled" | "succeeded";
export interface VerifiedClaimsReportReadPort { loadVerifiedClaimsReport(tenantId:string,operationId:string):Promise<{readonly state:VerificationClaimsReportReadState;readonly result?:unknown;readonly reportGateArtifact?:VerificationArtifactHandle;readonly policyDecision?:{readonly outcome:"pass"|"pass_with_warnings"|"review"|"abstain"|"fail";readonly reasonCodes:readonly string[]}}>; }
export type VerificationClaimsReportReadErrorCode="INVALID"|"NOT_FOUND"|"PENDING"|"FAILED"|"CANCELLED"|"INTEGRITY";
export class VerificationClaimsReportReadError extends Error { constructor(readonly code:VerificationClaimsReportReadErrorCode){super(`VERIFICATION_CLAIMS_REPORT_READ_${code}`);} }
const ref=(artifact:{artifactId:string;digest:string})=>({artifactId:artifact.artifactId,digest:artifact.digest});
const reportSummary=(value:{claimWeightedCitationCompleteness:number;citationCorrectness:number|null;validPointerConditionalCitationCorrectness:number|null;pointerFailures:unknown[];misplacedCitationIds:unknown[];duplicateAssertionGroups:unknown[];conflictAssertionGroups:unknown[];missingQualifierAssertionIds:unknown[];consistencyMismatchGroups:unknown[];crossSectionMismatches:unknown[];independentSourceFamilyCount:number;distinctSourceFamilyCount:number;unsupportedHighSeverityAssertionIds:unknown[]})=>({claimWeightedCitationCompleteness:value.claimWeightedCitationCompleteness,citationCorrectness:value.citationCorrectness,validPointerConditionalCitationCorrectness:value.validPointerConditionalCitationCorrectness,pointerFailureCount:value.pointerFailures.length,misplacedCitationCount:value.misplacedCitationIds.length,duplicateAssertionGroupCount:value.duplicateAssertionGroups.length,conflictAssertionGroupCount:value.conflictAssertionGroups.length,missingQualifierCount:value.missingQualifierAssertionIds.length,consistencyMismatchGroupCount:value.consistencyMismatchGroups.length,crossSectionMismatchCount:value.crossSectionMismatches.length,independentSourceFamilyCount:value.independentSourceFamilyCount,distinctSourceFamilyCount:value.distinctSourceFamilyCount,unsupportedHighSeverityCount:value.unsupportedHighSeverityAssertionIds.length});
const summary=(result:{status:"passed"|"failed"|"review_required";semanticEligibility:boolean;summary:{capturesTotal:number;capturesPassed:number;assertionsTotal:number;assertionsPassed:number;metricsTotal:number;metricsPassed:number;failedCheckCodes:string[];reviewReasons:string[]}})=>({status:result.status,semanticEligibility:result.semanticEligibility,...result.summary});
export class VerificationClaimsReportReadService {
 constructor(private readonly repository:VerifiedClaimsReportReadPort) {}
 async getTerminal(input:{tenantId:unknown;operationId:unknown}):Promise<VerificationClaimsReportTerminalResource>{
  const tenant=UuidSchema.safeParse(input.tenantId),operation=UuidSchema.safeParse(input.operationId); if(!tenant.success||!operation.success)throw new VerificationClaimsReportReadError("INVALID");
  const snapshot=await this.repository.loadVerifiedClaimsReport(tenant.data,operation.data);if(snapshot.state!=="succeeded")throw new VerificationClaimsReportReadError(snapshot.state==="pending"?"PENDING":snapshot.state==="cancelled"?"CANCELLED":"FAILED");
  try { const claims=VerificationClaimsOperationResultSchema.safeParse(snapshot.result); const report=VerificationReportOperationResultSchema.safeParse(snapshot.result);
   if(claims.success){const result=claims.data;if(result.operationId!==operation.data||result.resultArtifact.tenantId!==tenant.data||result.output.sealedRun.manifestArtifact.tenantId!==tenant.data)throw new Error("BINDING");const policy=policySummary(snapshot.policyDecision,result.output.sealedRun.policyOutcome);return deepFreeze(VerificationClaimsReportTerminalResourceSchema.parse({verificationContractVersion:"verification.v1",tenantId:tenant.data,operationId:operation.data,useCase:"verifyClaims",requestDigest:result.requestDigest,resultArtifact:ref(result.resultArtifact),sealedRun:{runId:result.output.sealedRun.runId,manifestDigest:result.output.sealedRun.manifestDigest,manifestArtifact:ref(result.output.sealedRun.manifestArtifact),policyOutcome:result.output.sealedRun.policyOutcome,policy},output:{mode:result.output.verified.mode,deterministic:summary(result.output.verified.deterministicResult),assertionsArtifact:ref(result.output.verified.assertionsArtifact)}}));}
   if(!report.success)throw new Error("RESULT"); const result=report.data;const gate=snapshot.reportGateArtifact;if(!gate||gate.tenantId!==tenant.data||result.operationId!==operation.data||result.resultArtifact.tenantId!==tenant.data||result.output.sealedRun.manifestArtifact.tenantId!==tenant.data)throw new Error("BINDING");const policy=policySummary(snapshot.policyDecision,result.output.sealedRun.policyOutcome);return deepFreeze(VerificationClaimsReportTerminalResourceSchema.parse({verificationContractVersion:"verification.v1",tenantId:tenant.data,operationId:operation.data,useCase:"verifyReport",requestDigest:result.requestDigest,resultArtifact:ref(result.resultArtifact),sealedRun:{runId:result.output.sealedRun.runId,manifestDigest:result.output.sealedRun.manifestDigest,manifestArtifact:ref(result.output.sealedRun.manifestArtifact),policyOutcome:result.output.sealedRun.policyOutcome,policy},output:{mode:result.output.verified.mode,deterministic:summary(result.output.verified.deterministicResult),assertionsArtifact:ref(result.output.verified.assertionsArtifact),reportArtifact:ref(result.output.verified.reportArtifact),claimLedgerArtifact:ref(result.output.verified.claimLedgerArtifact),reportWide:reportSummary(result.output.verified.reportWide),coverageScope:result.output.verified.coverageScope,reportGateArtifact:ref(gate)}}));
  }catch(error){if(error instanceof VerificationClaimsReportReadError)throw error;throw new VerificationClaimsReportReadError("INTEGRITY");}
 }
}

function policySummary(value:{readonly outcome:"pass"|"pass_with_warnings"|"review"|"abstain"|"fail";readonly reasonCodes:readonly string[]}|undefined, expected:string){
 if(value===undefined)return {availability:"unavailable" as const};
 if(value.outcome!==expected)throw new Error("POLICY_OUTCOME_BINDING");
 return {availability:"verified" as const,outcome:value.outcome,reasonCodes:[...value.reasonCodes]};
}


