import {VerificationProviderArtifactComposer} from "./verification-provider.js";
import {providerDigest} from "@aiengineer/knowledge-verification";
import {describe,expect,it,vi} from "vitest";
import {SemanticGatewayObservationRecorder,SemanticProviderComposerBinding} from "./verification-semantic-observation-recorder.js";
const id = (suffix: string) => `00000000-0000-4000-8000-${suffix.padStart(12, "0")}`;
const digest = (character: string) => `sha256:${character.repeat(64)}`;
const handle = (suffix: string, character: string, parents: readonly string[] = []) => ({ artifactId: id(suffix), digest: digest(character), tenantId: id("1"), byteLength: 1, mediaType: "application/json", objectKey: `restricted/${suffix}`, createdAt: "2026-09-07T00:00:00.000Z", producerActivityId: "semantic-worker", producerVersion: "v1", encryptionClass: "managed", retentionClass: "verification-audit", dataClassification: "restricted" as const, parentArtifactIds: [...parents], transformationSignature: digest("f") });
const blinded = handle("3", "c"), request = handle("4", "d", [blinded.artifactId]), raw = handle("5", "e"), envelope = handle("6", "f", [request.artifactId, raw.artifactId]), profile = handle("2", "b");
const body = () => ({ schemaVersion: "verification-semantic-response-observation.v1" as const, verificationContractVersion: "verification.v1" as const, context: { tenantId: id("1"), operationId: id("8"), operationStepId: id("9"), leaseToken: id("10"), fencingToken: 2, holderIdentity: "verification-worker", producerAttemptId: id("12"), providerAttemptId: id("11"), host: { operationKind: "verification_claims" as const, stepKey: "verify_claims_and_register" as const, useCase: "verifyClaims" as const } }, profileArtifact: profile, blindedInputArtifact: blinded, requestArtifact: request, rawResponseArtifact: raw, responseEnvelopeArtifact: envelope, judgeIdentity: { deploymentId: "gateway-luna", provider: "vercel-ai-gateway", family: "openai", model: "openai/gpt-5.6-luna", capability: "llm_evidence_rubric" as const, graderVersion: "evidence-only.v1", promptDigest: digest("2"), outputSchemaDigest: digest("3"), configurationDigest: digest("4") }, inputArtifactDigest: blinded.digest, requestDigest: request.digest, rawResponseDigest: raw.digest, requestedModel: "openai/gpt-5.6-luna", observedModel: "openai/gpt-5.6-luna", modelStatus: "matched" as const, revalidationRequired: false, usage: { totalTokens: 0 }, costStatus: "unknown" as const });

const event=()=>({schemaVersion:"verification-semantic-response-observation.v1" as const,requestDigest:request.digest as `sha256:${string}`,rawResponseDigest:raw.digest as `sha256:${string}`,inputArtifactDigest:blinded.digest as `sha256:${string}`,deploymentId:"gateway-luna",requestedModel:"openai/gpt-5.6-luna",observedModel:"openai/gpt-5.6-luna",modelStatus:"matched" as const,revalidationRequired:false,usage:{}});
function setup(change:Record<string,unknown>={}){const compose=vi.fn(async(value:unknown)=>value as never),store=vi.fn(async()=>{}),loadCapturedBinding=vi.fn(async()=>({...body(),...change}) as never);const recorder=new SemanticGatewayObservationRecorder({tenantId:id("1"),operationId:id("8"),operationStepId:id("9"),deploymentId:"gateway-luna"},{loadCapturedBinding},{compose},{store});return{compose,store,loadCapturedBinding,recorder};}
describe("gateway observation recorder",()=>{
 it("validates captured bindings and preserves unknown usage before storing",async()=>{const f=setup();await f.recorder.record(event());expect(f.loadCapturedBinding).toHaveBeenCalledWith(request.digest,raw.digest);expect(f.compose.mock.calls[0]?.[0]).toMatchObject({costStatus:"unknown",usage:{},context:{producerAttemptId:id("12"),providerAttemptId:id("11")}});expect(f.store).toHaveBeenCalledOnce();});
 it("rejects a gateway identity mismatch before custody lookup",async()=>{const f=setup();await expect(f.recorder.record({...event(),deploymentId:"forged"})).rejects.toThrow("SEMANTIC_GATEWAY_OBSERVATION_IDENTITY_MISMATCH");expect(f.loadCapturedBinding).not.toHaveBeenCalled();});
 it("rejects wrong operation and raw digest before composing",async()=>{const f=setup({context:{...body().context,operationId:id("99")}});await expect(f.recorder.record(event())).rejects.toThrow("SEMANTIC_GATEWAY_OBSERVATION_CUSTODY_MISMATCH");expect(f.compose).not.toHaveBeenCalled();const second=setup();await expect(second.recorder.record({...event(),rawResponseDigest:`sha256:${"0".repeat(64)}`})).rejects.toThrow();expect(second.compose).not.toHaveBeenCalled();});
 it("records valid model drift without rewriting judge identity",async()=>{const f=setup();await f.recorder.record({...event(),observedModel:"other-model",modelStatus:"mismatch",revalidationRequired:true});expect(f.compose.mock.calls[0]?.[0]).toMatchObject({requestedModel:"openai/gpt-5.6-luna",observedModel:"other-model",revalidationRequired:true,judgeIdentity:{model:"openai/gpt-5.6-luna"}});});
 it("withholds binding until durable transport capture is available",async()=>{const composer={requestArtifact:()=>request as never,rawResponseArtifact:()=>raw as never,responseEnvelopeArtifact:()=>envelope as never,transportResponseArtifact:()=>undefined};const binding=new SemanticProviderComposerBinding(body() as never,composer);await expect(binding.loadCapturedBinding(request.digest,raw.digest)).rejects.toThrow("SEMANTIC_CAPTURE_BINDING_UNAVAILABLE");const complete=new SemanticProviderComposerBinding(body() as never,{...composer,transportResponseArtifact:()=>handle("90","a",[envelope.artifactId,profile.artifactId]) as never});expect((await complete.loadCapturedBinding(request.digest,raw.digest)).responseEnvelopeArtifact.artifactId).toBe(envelope.artifactId);});
 it("registers a single blinded input as the semantic artifact type",async()=>{const register=vi.fn(async(input:any)=>({...handle("91","a"),digest:providerDigest(JSON.parse(new TextDecoder().decode(input.bytes))),byteLength:input.bytes.byteLength,mediaType:input.mediaType} as never));const composer=new VerificationProviderArtifactComposer({registerContentAddressedArtifact:register},{tenantId:id("1"),storageBucket:"ai-engineer-cloud-bucket",producerActivityId:"semantic-worker",producerVersion:"v1",encryptionClass:"managed",retentionClass:"verification-audit",now:()=>"2026-09-07T00:00:00.000Z",externalProcessingGrant:{providerId:"gateway",dataClassification:"synthetic",modalities:["text"]}});const input={rubricVersion:"evidence-only.v1" as const,assertionId:"claim-1",proposition:"A",qualifiers:[],entityBindings:[],fragments:[{fragmentId:"fragment-1",exactText:"A"}]};await composer.registerSemanticInput(input);expect(register.mock.calls[0]?.[0]).toMatchObject({artifactType:"verification_semantic_blinded_input",bucketClass:"ledger"});await expect(composer.registerInput(new Uint8Array([1]),"text/plain")).rejects.toThrow("PROVIDER_SEMANTIC_INPUT_ALREADY_BOUND");await expect(composer.registerSemanticInput(input)).rejects.toThrow("PROVIDER_SEMANTIC_INPUT_ALREADY_BOUND");expect(register).toHaveBeenCalledOnce();});

});
