import {generateKeyPairSync,randomUUID,sign,verify} from "node:crypto";
import {describe,expect,it} from "vitest";
import {canonicalizeJson,digestCanonicalJson,prepareGatewaySemanticRequest,sha256Digest,gatewaySemanticPromptDigest,gatewaySemanticOutputSchemaDigest,gatewaySemanticConfigurationDigest} from "@aiengineer/knowledge-verification";
import type {VerificationArtifactHandle,VerificationSemanticProviderReconciliation} from "@aiengineer/knowledge-contracts";
import {SemanticProviderReconciliationAdmission,semanticProviderReconciliationParents,semanticProviderReconciliationTransformationSignature,semanticReconciliationOriginalBinding} from "./verification-semantic-provider-reconciliation.js";

function fixture(custody:"none"|"capture"|"observation"="none") {
  const tenantId=randomUUID(),operationId=randomUUID(),providerAttemptId=randomUUID(),now="2026-09-07T12:00:00.000Z",model="openai/gpt-5.6-luna";
  const artifacts=new Map<string,{registration:VerificationArtifactHandle;bytes:Uint8Array}>();
  function add(value:unknown,parents:string[]=[],activity="fixture",transformationSignature?:string) {
    const bytes=new TextEncoder().encode(canonicalizeJson(value));
    const handle:VerificationArtifactHandle={artifactId:randomUUID(),tenantId,digest:sha256Digest(bytes),byteLength:bytes.length,mediaType:"application/json",objectKey:"fixture/"+randomUUID(),createdAt:now,producerActivityId:activity,producerVersion:"v1",encryptionClass:"managed",retentionClass:"audit",dataClassification:"public",parentArtifactIds:parents,...(transformationSignature?{transformationSignature}: {})};
    artifacts.set(handle.artifactId,{registration:handle,bytes});return handle;
  }
  const profile=add({schemaVersion:"verification-semantic-judge-profile.v1",identity:{deploymentId:"judge",provider:"vercel-ai-gateway",family:"openai",model,capability:"llm_evidence_rubric",graderVersion:"evidence-only.v1",promptDigest:gatewaySemanticPromptDigest,outputSchemaDigest:gatewaySemanticOutputSchemaDigest,configurationDigest:gatewaySemanticConfigurationDigest(model)}});
  const blinded={rubricVersion:"evidence-only.v1" as const,assertionId:"claim-1",proposition:"A",qualifiers:[],entityBindings:[],fragments:[{fragmentId:"fragment-1",exactText:"A"}]};
  const input=add(blinded),request=prepareGatewaySemanticRequest({...blinded,inputArtifactDigest:input.digest as `sha256:${string}`},model);
  const requestArtifact=add(JSON.parse(new TextDecoder().decode(request.requestBytes)),[input.artifactId]),billing=add({supplierCostMicros:0});
  const raw=add({response:"fixture"}),envelope=add({envelope:true},[requestArtifact.artifactId,raw.artifactId]),transport=add({transport:true},[envelope.artifactId,profile.artifactId]),observation=add({observation:true},[transport.artifactId]);
  const body={schemaVersion:"verification-semantic-provider-reconciliation.v1" as const,tenantId,operationId,operationStepId:randomUUID(),providerAttemptId,budgetId:randomUUID(),host:"claims" as const,providerId:"gateway" as const,model,dispatchFence:randomUUID(),dispatchLeaseToken:randomUUID(),dispatchHolderIdentity:"worker",dispatchFencingToken:2,requestDigest:request.requestDigest,profileArtifact:profile,blindedInputArtifact:input,requestArtifact,billingEvidenceArtifact:billing,
    ...(custody!=="none"?{capture:{transportArtifact:transport,responseEnvelopeArtifact:envelope,rawResponseArtifact:raw}}:{}),...(custody==="observation"?{observationArtifact:observation}:{}),
    originalState:"uncertain" as const,reservationCostMicros:100,decision:{action:"settle_original_attempt" as const,actualCostMicros:0,basis:"supplier_statement" as const,redispatchAuthorized:false as const},operatorId:"operator",ticketId:"ticket",issuedAt:now,expiresAt:"2026-09-07T13:00:00.000Z"};
  const keys=generateKeyPairSync("ed25519"),signatureBase64=sign(null,Buffer.from(canonicalizeJson(body)),keys.privateKey).toString("base64");
  const receipt:VerificationSemanticProviderReconciliation={...body,seal:{purpose:"provider_accounting_only",payloadDigest:digestCanonicalJson(body),signature:{algorithm:"Ed25519",keyId:"key",signatureBase64}}};
  const artifact=add(receipt,semanticProviderReconciliationParents(receipt),"verification-service:semantic-provider-reconciliation",semanticProviderReconciliationTransformationSignature(receipt));
  const state={binding:semanticReconciliationOriginalBinding(receipt),time:new Date(now)};
  const deps={grants:[{tenantId,operationId,providerAttemptId,keyId:"key",operatorId:"operator",executionMode:"live_provider" as const,billingEvidenceArtifact:billing}],createResolver:()=>{let authorized="";return {authorizeArtifact:async({artifactId}:{artifactId:string})=>{authorized=artifactId;},hydrateRegisteredArtifact:async({artifactId}:{artifactId:string})=>{if(authorized!==artifactId)throw new Error("UNAUTHORIZED");authorized="";return artifacts.get(artifactId)!;}};},verifier:{verify:async(value:{payload:Uint8Array;signatureBase64:string})=>verify(null,value.payload,keys.publicKey,Buffer.from(value.signatureBase64,"base64"))},loadOriginalBinding:async()=>state.binding,now:()=>state.time};
  return {deps,state,receipt,artifact,artifacts,admission:new SemanticProviderReconciliationAdmission(deps)};
}
describe("semantic accounting-only admission",()=>{
  it.each(["none","capture","observation"] as const)("admits signed exact %s custody including evidenced zero cost",async custody=>{const f=fixture(custody);const permit=await f.admission.admit({tenantId:f.receipt.tenantId,artifact:f.artifact});expect(permit.receipt.decision.actualCostMicros).toBe(0);expect(f.admission.assertPermit(permit)).toBe(permit);expect(()=>f.admission.assertPermit(structuredClone(permit))).toThrow("ISSUER_REQUIRED");f.state.time=new Date(f.receipt.expiresAt);expect(()=>f.admission.assertPermit(permit)).toThrow("EXPIRED_OR_FUTURE");});
  it("rejects changed native dispatch binding and changed retained bytes",async()=>{const f=fixture();f.state.binding={...f.state.binding,dispatchFencingToken:3};await expect(f.admission.admit({tenantId:f.receipt.tenantId,artifact:f.artifact})).rejects.toThrow("ADMISSION_DENIED");f.state.binding=semanticReconciliationOriginalBinding(f.receipt);f.artifacts.get(f.receipt.requestArtifact.artifactId)!.bytes[0]=0;await expect(f.admission.admit({tenantId:f.receipt.tenantId,artifact:f.artifact})).rejects.toThrow("ADMISSION_DENIED");});
  it("requires server-authorized execution mode and exact billing evidence",async()=>{const f=fixture();for(const patch of [{executionMode:"synthetic_transport" as const},{billingEvidenceArtifact:f.receipt.requestArtifact}]){const admission=new SemanticProviderReconciliationAdmission({...f.deps,grants:[{...f.deps.grants[0]!,...patch}]});await expect(admission.admit({tenantId:f.receipt.tenantId,artifact:f.artifact})).rejects.toThrow("ADMISSION_DENIED");}});
  it("rejects invalid signatures and cancellation",async()=>{const f=fixture();const admission=new SemanticProviderReconciliationAdmission({...f.deps,verifier:{verify:async()=>false}});await expect(admission.admit({tenantId:f.receipt.tenantId,artifact:f.artifact})).rejects.toThrow("ADMISSION_DENIED");await expect(f.admission.admit({tenantId:f.receipt.tenantId,artifact:f.artifact,signal:AbortSignal.abort()})).rejects.toThrow("ADMISSION_DENIED");});
  it("verifies historical evidence after expiry without creating a mutation permit",async()=>{const f=fixture();f.state.time=new Date("2026-09-08T00:00:00.000Z");const historical=await f.admission.verifyEvidenceAt({tenantId:f.receipt.tenantId,artifact:f.artifact,appliedAt:"2026-09-07T12:30:00.000Z"});expect(historical.receipt).toEqual(f.receipt);expect(()=>f.admission.assertPermit(historical)).toThrow("ISSUER_REQUIRED");await expect(f.admission.verifyEvidenceAt({tenantId:f.receipt.tenantId,artifact:f.artifact,appliedAt:"2026-09-09T00:00:00.000Z"})).rejects.toThrow("APPLICATION_TIME_INVALID");});
});
