import { KnowledgeIntegrationService } from "@aiengineer/knowledge-application";
import { describe,expect,it } from "vitest";
import { buildServer } from "./server.js";
import type { LocalApiIdentity } from "./auth.js";

const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`,tenant=id(1),operationId=id(2),token="audit-route-token",actor={kind:"service" as const,id:id(3),serviceIdentity:"mission_control_client" as const};
const identity:LocalApiIdentity={actor,grants:[{tenantId:tenant,roles:["knowledge_operator"],scopes:[]}]};
const headers={authorization:`Bearer ${token}`,"x-tenant-id":tenant,"x-correlation-id":"audit-route","idempotency-key":"audit-route-key"};
const request={verificationContractVersion:"verification.v1",auditBundle:{artifactId:id(4),digest:`sha256:${"a".repeat(64)}`}};
const base=(operations:KnowledgeIntegrationService)=>({verificationOperationService:operations,resolveIdentity:()=>identity,resolveVerificationContext:({tenantId,identity,correlationId,idempotencyKey}:any)=>({tenantId,operationId,attemptId:id(5),correlationId,actor:identity.actor,capabilityVersion:"verification-service.v1",idempotencyKey,reason:"audit route test",contractVersion:"v1" as const})});
describe("audit inspection HTTP routes",()=>{
  it("fails before enqueue without an exact configured claims/report grant",async()=>{for(const admission of [undefined,async()=>false]){const operations=new KnowledgeIntegrationService(),server=buildServer({...base(operations),...(admission?{isAuditInspectionRequestAdmitted:admission}:{})});try{const response=await server.inject({method:"POST",url:"/v1/verification/audit-bundles:inspect",headers,payload:request});expect(response.statusCode).toBe(admission?403:503);expect(operations.get(operationId,tenant)).toBeUndefined();}finally{await server.close();}}});
  it("enqueues only the strict request and exposes a separate typed terminal read",async()=>{const operations=new KnowledgeIntegrationService(),server=buildServer({...base(operations),isAuditInspectionRequestAdmitted:async(t,r)=>t===tenant&&r.auditBundle.artifactId===request.auditBundle.artifactId,verificationAuditInspectionReads:{getInspection:async()=>({verificationContractVersion:"verification.v1",tenantId:tenant,operationId,requestDigest:`sha256:${"b".repeat(64)}`,resultArtifact:{artifactId:id(6),digest:`sha256:${"c".repeat(64)}`},output:{schemaVersion:"verification-audit-inspection.v1",verificationContractVersion:"verification.v1",auditArtifact:{...request.auditBundle,mediaType:"application/vnd.aiengineer.verification-run-manifest+json",sizeBytes:10},run:{runId:id(7),manifestId:id(8),manifestDigest:`sha256:${"d".repeat(64)}`,deterministicResultDigest:`sha256:${"e".repeat(64)}`,policyDecisionDigest:`sha256:${"f".repeat(64)}`,policyOutcome:"review",startedAt:"2026-09-07T00:00:00.000Z",completedAt:"2026-09-07T00:00:00.000Z"},proof:{payloadDigest:`sha256:${"1".repeat(64)}`,signatureStatus:"verified",deterministicReplay:"exact",policyReplay:"exact",replayedArtifactCount:2,inputArtifactCount:1,outputArtifactCount:2}}})}});try{const accepted=await server.inject({method:"POST",url:"/v1/verification/audit-bundles:inspect",headers,payload:request});expect(accepted.statusCode,accepted.body).toBe(202);expect(operations.input(operationId,tenant)).toMatchObject({useCase:"inspectAuditBundle",request});expect((await server.inject({method:"GET",url:`/v1/verification/audit-inspections/${operationId}`,headers})).json()).toMatchObject({operationId,resultArtifact:{artifactId:id(6)}});expect((await server.inject({method:"POST",url:"/v1/verification/audit-bundles:inspect",headers,payload:{...request,publicKey:"caller"}})).statusCode).toBe(400);}finally{await server.close();}});
  it("rejects malformed runtime projections before they cross the public route",async()=>{const operations=new KnowledgeIntegrationService(),server=buildServer({...base(operations),verificationAuditInspectionReads:{getInspection:async()=>({objectKey:"private-storage-coordinate"} as any)}});try{const response=await server.inject({method:"GET",url:`/v1/verification/audit-inspections/${operationId}`,headers});expect(response.statusCode).toBe(503);expect(response.body).not.toContain("private-storage-coordinate");}finally{await server.close();}});

});
