import { CanonicalRetrievalExecutor } from "../apps/api/src/retrieval-executor.js";
import { buildServer } from "../apps/api/src/server.js";
import { PostgresKnowledgeOperationService, PostgresCanonicalRepository } from "@aiengineer/knowledge-persistence";
import { DeterministicFakeEmbeddingAdapter } from "@aiengineer/knowledge-embeddings";
import { deterministicUuid } from "@aiengineer/knowledge-runtime";
import { FIXTURE_NAMESPACE, FIXTURE_TENANT_ID } from "./canonical-fixture.js";

const postgresUrl=process.env.POSTGRES_URL?.trim();if(!postgresUrl)throw new Error("POSTGRES_URL_REQUIRED");
const database=new PostgresCanonicalRepository({connectionString:postgresUrl,localOnly:true});
const token="canonical-retrieval-proof-token";const actor={kind:"service" as const,id:deterministicUuid("canonical-retrieval-proof","actor"),serviceIdentity:"mission_control_client" as const};
const otherTenant="00000000-0000-7000-8000-000000000002";
const executor=new CanonicalRetrievalExecutor(database,new DeterministicFakeEmbeddingAdapter(),{now:()=>new Date("2026-09-04T12:00:00.000Z")});
const api=buildServer({operationService:new PostgresKnowledgeOperationService(database),resourceReader:database,getEvidencePacket:async(tenant,id)=>await database.getEvidencePacket(tenant,id) as never,
  canonicalRetrievalExecutor:executor,publicOrigin:"http://127.0.0.1:4190",
  resolveIdentity:candidate=>candidate===token?{actor,grants:[{tenantId:FIXTURE_TENANT_ID,roles:["knowledge_operator","knowledge_reader"],scopes:[]},{tenantId:otherTenant,roles:["knowledge_reader"],scopes:[]}]}:undefined});
const operationId=deterministicUuid("canonical-retrieval-proof",`${FIXTURE_NAMESPACE}:operation`),attemptId=deterministicUuid("canonical-retrieval-proof",`${FIXTURE_NAMESPACE}:attempt`),correlationId="canonical-retrieval-live-proof";
const policyVersion=deterministicUuid("canonical-exploratory-fixture",`${FIXTURE_NAMESPACE}:retrieval-policy-version:1`);
const plan={policyVersion,query:"durable agent state",intents:["knowledge_evidence" as const],subqueries:[{id:"durable-state",text:"durable agent state",coverageRole:"required" as const}],spaces:["engineering_claims" as const],anchors:{entities:[],concepts:[],useCases:[]},hardFilters:[{field:"visibility",op:"eq" as const,value:"internal"}],softBoosts:[],temporalScope:{},candidateK:20,finalK:5,graph:{maxDepth:0,allowedEdges:[]},abstention:{minimumCoverage:1}};
const context={tenantId:FIXTURE_TENANT_ID,operationId,attemptId,correlationId,actor,capabilityVersion:"retrieval/v1",idempotencyKey:`${FIXTURE_NAMESPACE}:api-retrieval`,reason:"prove canonical API-owned hybrid retrieval",contractVersion:"v1" as const};
const request={method:"POST" as const,url:"/v1/retrieval-runs",headers:{authorization:`Bearer ${token}`,"x-tenant-id":FIXTURE_TENANT_ID,"x-correlation-id":correlationId},payload:{context,input:{plan},expectedVersions:{api:"v1",retrieval:"v1"}}};
try{
  const first=await api.inject(request),replay=await api.inject(request);if(first.statusCode!==202||replay.statusCode!==202)throw new Error(`API_RETRIEVAL_FAILED:${first.statusCode}:${first.body}:${replay.statusCode}:${replay.body}`);
  const status=await api.inject({method:"GET",url:`/v1/operations/${operationId}`,headers:request.headers});if(status.statusCode!==200||status.json().state!=="succeeded")throw new Error(`RETRIEVAL_OPERATION_NOT_SUCCEEDED:${status.body}`);
  const run=await api.inject({method:"GET",url:`/v1/retrieval-runs/${operationId}`,headers:request.headers});const runBody=run.json();if(run.statusCode!==200||runBody.evidencePacketIds.length!==1)throw new Error(`RETRIEVAL_RUN_NOT_DURABLE:${run.body}`);
  const packet=await api.inject({method:"GET",url:`/v1/evidence-packets/${runBody.evidencePacketIds[0]}`,headers:request.headers});const packetBody=packet.json();if(packet.statusCode!==200||packetBody.members.length<1||packetBody.members.some((member:{locators:unknown[]})=>member.locators.length<1))throw new Error(`PACKET_NOT_LOCATOR_BOUND:${packet.body}`);
  const explanation=await api.inject({method:"GET",url:`/v1/retrieval-runs/${operationId}/explanation`,headers:request.headers});if(explanation.statusCode!==200||explanation.json().candidates.length!==packetBody.members.length)throw new Error(`EXPLANATION_NOT_DURABLE:${explanation.body}`);
  const persisted=await database.transaction(FIXTURE_TENANT_ID,async(client)=>({run:(await client.query<Record<string,unknown>>("select plan_id,request_sha256,stage_timings,fusion_params,reranker_id from retrieval.retrieval_run where tenant_id=$1 and id=$2",[FIXTURE_TENANT_ID,operationId])).rows[0]!,policy:(await client.query<{policy_version:number}>("select policy_version from retrieval.retrieval_plan where tenant_id=$1 and id=$2",[FIXTURE_TENANT_ID,runBody.plan.id])).rows[0]!,candidates:(await client.query<Record<string,unknown>>("select id,vector_item_id,stage_scores,final_score,rank from retrieval.retrieval_candidate where tenant_id=$1 and run_id=$2 order by rank,id",[FIXTURE_TENANT_ID,operationId])).rows,sources:(await client.query<Record<string,unknown>>("select id,retrieval_candidate_id,channel,search_projection_id,source_rank,score,explanation from retrieval.retrieval_candidate_source where tenant_id=$1 and retrieval_candidate_id in(select id from retrieval.retrieval_candidate where tenant_id=$1 and run_id=$2) order by id",[FIXTURE_TENANT_ID,operationId])).rows}));
  const resolved=await database.resolveRetrievalPolicy(FIXTURE_TENANT_ID,policyVersion,plan.spaces);
  const durableInput={operationId,requestSha256:String(persisted.run.request_sha256),planId:String(persisted.run.plan_id),policyVersionNumber:Number(persisted.policy.policy_version),activeVectorSpaceVersionIds:resolved.targets.map(target=>target.vectorSpaceVersionId),packet:packetBody,stageTimings:persisted.run.stage_timings,fusionParameters:persisted.run.fusion_params,...(persisted.run.reranker_id?{rerankerId:String(persisted.run.reranker_id)}:{}),candidates:persisted.candidates.map(candidate=>({id:String(candidate.id),vectorItemId:String(candidate.vector_item_id),stageScores:candidate.stage_scores,finalScore:Number(candidate.final_score),rank:Number(candidate.rank),sources:persisted.sources.filter(source=>String(source.retrieval_candidate_id)===String(candidate.id)).map(source=>({id:String(source.id),channel:String(source.channel) as "vector"|"lexical"|"exact"|"graph"|"rerank",...(source.search_projection_id?{searchProjectionId:String(source.search_projection_id)}:{}),sourceRank:Number(source.source_rank),score:Number(source.score),explanation:source.explanation}))}))};
  await database.storeRetrievalExecution(FIXTURE_TENANT_ID,durableInput);const conflicting={...durableInput,candidates:durableInput.candidates.map((candidate,index)=>index?candidate:{...candidate,sources:candidate.sources.map((source,sourceIndex)=>sourceIndex?source:{...source,explanation:{tampered:true}})})};let sourceConflict="";try{await database.storeRetrievalExecution(FIXTURE_TENANT_ID,conflicting);}catch(error){sourceConflict=error instanceof Error?error.message:String(error);}if(sourceConflict!=="IDEMPOTENCY_CONFLICT")throw new Error(`SOURCE_REPLAY_CONFLICT_NOT_DETECTED:${sourceConflict}`);
  const crossTenant=await api.inject({method:"GET",url:`/v1/retrieval-runs/${operationId}`,headers:{...request.headers,"x-tenant-id":otherTenant}});if(crossTenant.statusCode!==404)throw new Error(`TENANT_ISOLATION_FAILED:${crossTenant.statusCode}`);
  const tampered=await api.inject({...request,payload:{...request.payload,input:{plan:{...plan,query:"tampered replay query"}}}});if(tampered.statusCode!==409)throw new Error(`TAMPER_REPLAY_NOT_REJECTED:${tampered.statusCode}:${tampered.body}`);
  const missingOperationId=deterministicUuid("canonical-retrieval-proof",`${FIXTURE_NAMESPACE}:missing-space`),missingContext={...context,operationId:missingOperationId,attemptId:deterministicUuid("canonical-retrieval-proof",`${FIXTURE_NAMESPACE}:missing-space-attempt`),idempotencyKey:`${FIXTURE_NAMESPACE}:missing-space`};
  const missing=await api.inject({...request,payload:{...request.payload,context:missingContext,input:{plan:{...plan,spaces:[...plan.spaces,"implementation_examples" as const]}}}});if(missing.statusCode!==202)throw new Error(`MISSING_SPACE_EXECUTION_FAILED:${missing.statusCode}:${missing.body}`);
  const missingRun=(await database.getRetrievalRunResource(FIXTURE_TENANT_ID,missingOperationId))!,missingPacket=await database.getEvidencePacket(FIXTURE_TENANT_ID,missingRun.evidencePacketIds[0]!) as {abstention:{recommended:boolean;reason?:string}};if(!missingPacket.abstention.recommended||!missingPacket.abstention.reason?.includes("implementation_examples"))throw new Error("MISSING_SPACE_DID_NOT_FORCE_ABSTENTION");
  const graphOperationId=deterministicUuid("canonical-retrieval-proof",`${FIXTURE_NAMESPACE}:graph-not-backed`),graphContext={...context,operationId:graphOperationId,attemptId:deterministicUuid("canonical-retrieval-proof",`${FIXTURE_NAMESPACE}:graph-attempt`),idempotencyKey:`${FIXTURE_NAMESPACE}:graph-not-backed`};
  const graph=await api.inject({...request,payload:{...request.payload,context:graphContext,input:{plan:{...plan,graph:{maxDepth:1,allowedEdges:["supports"]}}}}});const graphStatus=await database.getOperation(FIXTURE_TENANT_ID,graphOperationId);if(graph.statusCode!==409||graphStatus?.status!=="failed")throw new Error(`UNBACKED_GRAPH_NOT_FAILED_CLOSED:${graph.statusCode}:${graphStatus?.status}`);
  process.stdout.write(`${JSON.stringify({phase:"canonical_retrieval_api_proof",operationId,state:status.json().state,evidencePacketId:packetBody.id,members:packetBody.members.length,channels:[...new Set(explanation.json().candidates.flatMap((candidate:{sources:{channel:string}[]})=>candidate.sources.map(source=>source.channel)))],abstention:packetBody.abstention,replayOperationId:replay.json().operationId,crossTenantStatus:crossTenant.statusCode,tamperStatus:tampered.statusCode,immutableSourceReplayConflict:sourceConflict,missingSpaceAbstention:missingPacket.abstention,unbackedGraph:{httpStatus:graph.statusCode,operationStatus:graphStatus?.status}})}\n`);
}finally{await api.close();await database.close();}
