import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { createApiRuntime } from "../apps/api/src/index.js";
import { startWorker } from "../apps/worker/src/index.js";
import { deterministicUuid } from "@aiengineer/knowledge-runtime";
import { PostgresCanonicalRepository } from "@aiengineer/knowledge-persistence";

const local = await (await import("../../internal/verification-local-direct-config.mjs")).loadVerifiedLocalDevelopmentConfig();
const namespace=randomUUID(), tenantId="3c05e46f-aebb-4dfe-8e2d-9aad5483f85f", missionId="3467f138-237a-4f83-a276-0e87dc8b0ce3", workItemId="51b183f1-9dd2-4ea3-a32f-6f23a1a932f7";
const sourceRunId="68458fde-efc9-5b99-acc7-4cdd97048508", sourceBundle={artifactId:"63f1fd95-e9a6-5917-a621-38b94b47165e",digest:"sha256:5b3a0a545467065d2f70057b5410e0ffa9dbf013559c60decef051840f312784"};
const sourceProfile={artifactId:"d74cea32-e3ba-5892-a3fc-3c2bea1e3acf",digest:"sha256:906a3877a54a04992b30598b9c61d392404acd254b44786b80599af95c17f190"};
const policy={artifactId:"f95401cb-556c-5104-a225-7f77c4b75d85",digest:"sha256:5ff535b443c55907f47dd1bb9572a01f9511b093f4f7c3457270297107f57878"};
const attemptId=randomUUID(), actor={kind:"service" as const,id:randomUUID(),serviceIdentity:"knowledge_worker" as const}, deploymentId="metric-verifier", token=`dashboard-replay-${randomUUID()}`;
const subject=`replay-operator-${namespace}`, sessionSecret="r".repeat(32), operatorToken="o".repeat(32), idempotencyKey="dashboard-replay:"+createHash("sha256").update([subject,tenantId,missionId,sourceRunId,"deterministic_only"].join("\n")).digest("hex");
const operationId=deterministicUuid("verification-http-operation",`${tenantId}:replayRun:${idempotencyKey}`), receiptPath=resolve("../internal",`verification-dashboard-native-replay-${namespace}.json`);
const database=new PostgresCanonicalRepository({connectionString:local.DB_URL,localOnly:true}); let runtime:Awaited<ReturnType<typeof createApiRuntime>>|undefined,worker:Awaited<ReturnType<typeof startWorker>>|undefined;
const saved=Object.fromEntries(["DASHBOARD_SESSION_SECRET","DASHBOARD_OPERATOR_TOKEN_DIGESTS_JSON","KNOWLEDGE_API_URL","KNOWLEDGE_API_TOKEN","MISSION_CONTROL_API_URL","MISSION_CONTROL_API_TOKEN","DASHBOARD_VERIFICATION_REPLAY_KNOWLEDGE_TOKENS_JSON"].map(k=>[k,process.env[k]]));
try {
 await database.transaction(tenantId,async c=>{const next=(await c.query<{next:number}>("select coalesce(max(attempt_no),0)::int+1 next from orchestration.attempt where tenant_id=$1 and work_item_id=$2",[tenantId,workItemId])).rows[0]!.next;await c.query("insert into orchestration.attempt(id,tenant_id,work_item_id,attempt_no,agent_deployment_id,started_at) values($1,$2,$3,$4,$5,clock_timestamp())",[attemptId,tenantId,workItemId,next,deploymentId]);});
 const ownership=[{tenantId,actor,missionId,agentDeploymentId:deploymentId,capabilityVersion:"verification-metric-proof.v1"}];
 const env={NODE_ENV:"test",POSTGRES_URL:local.DB_URL,SUPABASE_URL:local.API_URL,SUPABASE_SECRET_KEY:local.SECRET_KEY,CANONICAL_LOCAL_ONLY:"1",KNOWLEDGE_PERSISTENCE_MODE:"postgres",WORKER_TENANT_ID:tenantId,WORKER_OPERATION_ID:operationId,WORKER_POLL_MS:"25",VERIFICATION_PARSER_IMAGE_DIGEST:"sha256:1669a3f9674b2e0a70ba1c8686c1cb3647492b8268bdfa7a9a4452fb0530fb37",VERIFICATION_STORAGE_BUCKET:"ai-engineer-cloud-bucket",VERIFICATION_METRIC_ENABLED:"1",VERIFICATION_METRIC_PROFILE_GRANTS_JSON:JSON.stringify([{profileArtifact:sourceProfile,observations:sourceBundle}]),VERIFICATION_SEAL_POLICY_GRANTS_JSON:JSON.stringify([{tenantId,policyVersion:"metric-proof-policy.v1",policyArtifact:policy}]),VERIFICATION_READS_ENABLED:"1",VERIFICATION_CODE_GIT_SHA:"dashboard-native-replay-proof",VERIFICATION_CODE_DIRTY:"1",VERIFICATION_RUNTIME_PLATFORM:"node24-windows",VERIFICATION_RUNTIME_DEPLOYMENT_ID:deploymentId,KNOWLEDGE_API_IDENTITIES:JSON.stringify([{token,actor,grants:[{tenantId,roles:["knowledge_operator"],scopes:[]}]}]),VERIFICATION_SERVICE_OWNERSHIP_GRANTS_JSON:JSON.stringify(ownership)};
 runtime=await createApiRuntime(env); const baseUrl=await runtime.server.listen({host:"127.0.0.1",port:0});
 process.env.DASHBOARD_SESSION_SECRET=sessionSecret;process.env.DASHBOARD_OPERATOR_TOKEN_DIGESTS_JSON=JSON.stringify([{tokenDigest:"sha256:"+createHash("sha256").update(operatorToken).digest("hex"),subject,tenantId,missionId,role:"operator"}]);process.env.KNOWLEDGE_API_URL=baseUrl;process.env.KNOWLEDGE_API_TOKEN="unused";process.env.MISSION_CONTROL_API_URL="http://127.0.0.1";process.env.MISSION_CONTROL_API_TOKEN="unused";process.env.DASHBOARD_VERIFICATION_REPLAY_KNOWLEDGE_TOKENS_JSON=JSON.stringify([{subject,tenantId,missionId,workItemId,attemptId,runId:sourceRunId,knowledgeToken:token}]);
 const {signDashboardSessionForTest}=await import(pathToFileURL(resolve("../ai-engineer-mission-control/apps/dashboard/src/server/config.ts")).href); const {forwardDashboardRequest}=await import(pathToFileURL(resolve("../ai-engineer-mission-control/apps/dashboard/src/server/proxy.ts")).href);
 const cookie=signDashboardSessionForTest({subject,tenantId,missionId,role:"operator",csrfToken:"c".repeat(24),expiresAt:Math.floor(Date.now()/1000)+60},sessionSecret);
 const invoke=()=>forwardDashboardRequest(new Request(`https://dashboard.example/api/knowledge/verification/runs/${sourceRunId}:replay`,{method:"POST",headers:{cookie:`mc_dashboard_session=${cookie}`,origin:"https://dashboard.example","x-dashboard-csrf":"c".repeat(24),"content-type":"application/json"},body:JSON.stringify({replayMode:"deterministic_only"})}),"knowledge",["verification","runs",`${sourceRunId}:replay`]);
 const first=await invoke();assert.equal(first.status,202);assert.equal((await first.json()).operationId,operationId); const second=await invoke();assert.equal(second.status,202);assert.equal((await second.json()).operationId,operationId); worker=await startWorker(env);
 const deadline=Date.now()+20_000;let record;do{record=await database.getOperationRecord(tenantId,operationId);if(record?.status==="succeeded")break;await new Promise(r=>setTimeout(r,50));}while(Date.now()<deadline);assert.equal(record?.status,"succeeded","REPLAY_TERMINAL_TIMEOUT"); const receipts=await database.listReceipts(tenantId,operationId);assert.equal(receipts.length,1);
 await writeFile(receiptPath,JSON.stringify({schemaVersion:"verification-dashboard-native-replay-proof.v1",namespace,tenantId,missionId,workItemId,attemptId,sourceRunId,operationId,checks:{signedDashboardBffToKsApi:true,exactServerOwnedReplayGrant:true,ownershipResolverAccepted:true,scopedWorkerOnly:true,terminalSucceeded:true,repeatedIdempotencyStable:true,oneReceipt:receipts.length===1},sourceOperation:"fcda7cf8-78ff-5755-aa89-9e764357e905",noProviderCalls:true,createdAt:new Date().toISOString()},null,2)+"\n",{flag:"wx"});console.log(JSON.stringify({passed:true,receiptPath,operationId}));
} finally {for(const [k,v] of Object.entries(saved)){if(v===undefined)delete process.env[k];else process.env[k]=v;} await worker?.stop("dashboard-native-replay-proof");await runtime?.server.close();await runtime?.database?.close();await database.close();}
