import assert from "node:assert/strict";
import {randomUUID,createHash,generateKeyPairSync} from "node:crypto";
import {readFile,writeFile} from "node:fs/promises";
import {resolve} from "node:path";
import {StructuredExtractionProfileAdmission,type StructuredExtractionRuntimeGrant} from "../packages/application/src/verification-structured-extraction-profile.js";
import {StructuredExtractionCapturedReplayService} from "../packages/application/src/verification-structured-extraction-replay.js";
import {StructuredExtractionCandidateBuilder} from "../packages/application/src/verification-structured-extraction-candidate.js";
import {VerificationAdmissionService} from "../packages/application/src/verification-admission.js";
import {AccountedVerificationProviderSink,VerificationProviderArtifactComposer} from "../packages/application/src/verification-provider.js";
import {type TenantSqlClient,PostgresCanonicalRepository,PostgresVerificationRepository,PostgresKnowledgeOperationService} from "../packages/persistence/src/index.js";
import {PostgresVerificationProviderResponseCaptureStore} from "../packages/persistence/src/verification-provider-response-capture.js";
import {PostgresVerificationProviderAccounting} from "../packages/persistence/src/verification-provider-accounting.js";
import {PostgresStructuredExtractionLifecycleStore,type StructuredExtractionLifecycleIdentity} from "../packages/persistence/src/verification-structured-extraction-lifecycle.js";
import {SupabaseArtifactStore} from "@aiengineer/knowledge-runtime";
import {SandboxedVerificationParser,VERIFICATION_PARSER_LIMITS} from "@aiengineer/knowledge-conversion";
import {GatewayStructuredExtractionProvider,InterfazeStructuredExtractionProvider} from "@aiengineer/knowledge-verification";

import {StructuredExtractionExecutionArtifactBuilder} from "../packages/application/src/verification-structured-extraction-publication.js";
import {StructuredExtractionFailureArtifactBuilder} from "../packages/application/src/verification-structured-extraction-failure.js";
import {PostgresStructuredExtractionExecutionStore} from "../packages/persistence/src/verification-structured-extraction-execution.js";
import {PostgresStructuredExtractionFailureStore} from "../packages/persistence/src/verification-structured-extraction-failure.js";
import {StructuredExtractionFailureLifecycleSnapshotSchema,type StructuredExtractionProviderCallSnapshot} from "@aiengineer/knowledge-contracts";
import {createEd25519Signer,createEd25519Verifier,canonicalizeJson} from "@aiengineer/knowledge-verification";

import {createStructuredExtractionOperationResult} from "../packages/application/src/verification-structured-extraction-result.js";
import {digestCanonicalJson} from "@aiengineer/knowledge-verification";

import {createStructuredExtractionFailureOperationResult} from "../packages/application/src/verification-structured-extraction-failure-result.js";
import {PostgresStructuredExtractionRecoveryStore} from "../packages/persistence/src/verification-structured-extraction-recovery.js";
const pgUrl=process.env.POSTGRES_URL!,storageUrl=process.env.SUPABASE_URL!;
for(const[value,port]of [[pgUrl,"54322"],[storageUrl,"54321"]]){const url=new URL(value!);if(!["localhost","127.0.0.1"].includes(url.hostname)||url.port!==port)throw new Error("LOCAL_ONLY_PROOF_REQUIRED");}
const fixtureName="verification-structured-extraction-preparation-c6085a8a-8c56-4923-a9ed-dd09666d223d.json";
const fixture=JSON.parse(await readFile(resolve("../internal",fixtureName),"utf8")) as {tenantId:string;attemptId:string;missionId:string;workItemId:string;createdAt:string;imageDigest:`sha256:${string}`;profiles:{providerId:string;grant:StructuredExtractionRuntimeGrant;request:unknown}[]};
const tenantId=fixture.tenantId,namespace=randomUUID(),operations:string[]=[],results:unknown[]=[],checks:Record<string,boolean>={};let syntheticFetches=0;
const database=new PostgresCanonicalRepository({connectionString:pgUrl,localOnly:true}),store=new PostgresStructuredExtractionLifecycleStore(database),captures=new PostgresVerificationProviderResponseCaptureStore(database);
const operationService=new PostgresKnowledgeOperationService(database,{admittedOperationKinds:["verification_structured_extraction"]});
const repository=new PostgresVerificationRepository(database,new SupabaseArtifactStore({projectUrl:storageUrl,serviceRoleKey:process.env.SUPABASE_SECRET_KEY!,bucket:"ai-engineer-cloud-bucket",maximumBytes:8_000_000}),{async authorize(v){assert.equal(v.tenantId,tenantId);assert.ok(["verification_admission","verification_replay"].includes(v.purpose));}});
const native=new VerificationAdmissionService(repository,new SandboxedVerificationParser(fixture.imageDigest),{parserVersion:"verification-native-parser.v1",imageDigest:fixture.imageDigest,limits:VERIFICATION_PARSER_LIMITS},{storageBucket:"ai-engineer-cloud-bucket",producerVersion:"structured-extraction-proof.v1",encryptionClass:"supabase-managed",retentionClass:"verification-audit",now:()=>fixture.createdAt});
const keyPair=generateKeyPairSync("ed25519"),publicKeyPem=keyPair.publicKey.export({type:"spki",format:"pem"}).toString();
const signer=createEd25519Signer(keyPair.privateKey.export({type:"pkcs8",format:"pem"}).toString(),"local-structured-custody"),verifier=createEd25519Verifier({"local-structured-custody":publicKeyPem});
const executionStore=new PostgresStructuredExtractionExecutionStore(database),failureStore=new PostgresStructuredExtractionFailureStore(database,verifier);
const publicationPort={async register(input:Parameters<ConstructorParameters<typeof StructuredExtractionExecutionArtifactBuilder>[0]["artifacts"]["register"]>[0]|Parameters<ConstructorParameters<typeof StructuredExtractionFailureArtifactBuilder>[1]["artifacts"]["register"]>[0]){return repository.registerContentAddressedArtifact({...input,producerActivityId:"structured-publication-proof",producerVersion:"v1",mediaType:"application/json",encryptionClass:"supabase-managed",retentionClass:"verification-audit",dataClassification:"restricted",bucketClass:"candidate",storageBucket:"ai-engineer-cloud-bucket"});}};
const executionBuilder=new StructuredExtractionExecutionArtifactBuilder({artifacts:publicationPort,createResolver:()=>repository.createTrustedArtifactResolver()});
const custodyPaths=["packages/contracts/src/verification/structured-extraction-failure.ts", "packages/application/src/verification-structured-extraction-failure.ts", "packages/application/src/verification-structured-extraction-profile.ts", "packages/application/src/verification-structured-extraction-replay.ts", "packages/application/src/verification-structured-extraction-publication.ts", "packages/persistence/src/verification-structured-extraction-execution.ts", "packages/persistence/src/verification-structured-extraction-failure.ts", "packages/persistence/src/verification-structured-extraction-lifecycle.ts", "../ai-engineer-db-contract/supabase/migrations/20260906032500_verification_structured_extraction_failure.sql", "packages/contracts/src/verification/structured-extraction-failure-result.ts","packages/application/src/verification-structured-extraction-failure-result.ts","packages/persistence/src/postgres.ts","../ai-engineer-db-contract/supabase/migrations/20260906032600_verification_structured_extraction_failure_terminal.sql","packages/persistence/src/verification-structured-extraction-recovery.ts","scripts/prove-verification-structured-extraction-failure-recovery.ts"];
const sourceFiles=await Promise.all(custodyPaths.map(async path=>{const bytes=await readFile(path);return {path,sha256:createHash("sha256").update(bytes).digest("hex"),byteLength:bytes.byteLength,bytesBase64:bytes.toString("base64")};}));
const dirtyStateArtifact=await repository.registerContentAddressedArtifact({tenantId,producerAttemptId:fixture.attemptId,artifactType:"verification_structured_extraction_source_custody",bytes:new TextEncoder().encode(canonicalizeJson({schemaVersion:"verification-structured-extraction-source-custody.v1",tenantId,scope:"listed_files",totalByteLength:sourceFiles.reduce((sum,f)=>sum+f.byteLength,0),files:sourceFiles.map(f=>({...f,path:f.path.startsWith("../ai-engineer-db-contract/")?"DB/"+f.path.slice("../ai-engineer-db-contract/".length):"KS/"+f.path,sha256:`sha256:${f.sha256}`}))})),createdAt:new Date().toISOString(),parentArtifactIds:[],producerActivityId:"structured-publication-proof",producerVersion:"v1",mediaType:"application/json",encryptionClass:"supabase-managed",retentionClass:"verification-audit",dataClassification:"restricted",bucketClass:"candidate",storageBucket:"ai-engineer-cloud-bucket"});
try{
 await assert.rejects(new PostgresKnowledgeOperationService(database).submit("verification_structured_extraction",{},"http://localhost"),/CAPABILITY_NOT_ADMITTED/);checks.default_admission_still_closed=true;
 for(const selected of fixture.profiles)for(const failureKind of ["http","schema"] as const){
  const admission=new StructuredExtractionProfileAdmission([selected.grant],()=>repository.createTrustedArtifactResolver(),native),preparation=await admission.prepare({tenantId,request:selected.request});
  const operationId=randomUUID(),providerAttemptId=randomUUID();operations.push(operationId);
  const context={tenantId,operationId,attemptId:fixture.attemptId,missionId:fixture.missionId,workItemId:fixture.workItemId,correlationId:namespace,actor:{kind:"service",id:namespace,serviceIdentity:"knowledge_worker"},capabilityVersion:"verification-service.v1",idempotencyKey:`${namespace}-${operationId}`,reason:"Synthetic local lifecycle proof",contractVersion:"v1"};
  await operationService.submit("verification_structured_extraction",{context,input:{schemaVersion:"verification-service-request.v1",useCase:"extractStructuredData",request:selected.request},expectedVersions:{verification:"verification.v1",service:"verification-service-request.v1"}},"http://localhost");
  const operation=await database.getOperation(tenantId,operationId),lease=await database.claimOperation(tenantId,operationId,namespace,300_000);assert.ok(operation&&lease);
  const identity:StructuredExtractionLifecycleIdentity={tenantId,operationId,operationStepId:lease.id,producerAttemptId:fixture.attemptId,requestDigest:`sha256:${operation.requestSha256}`,stepInputDigest:`sha256:${lease.inputSha256}`,captureId:preparation.captureId,profileArtifact:preparation.artifacts.producerProfile,schemaArtifact:preparation.artifacts.extractionSchema,sourceArtifact:preparation.artifacts.source,representationArtifact:preparation.representation,transformationArtifact:preparation.artifacts.transformation,promptDigest:preparation.promptDigest,schemaDigest:preparation.schema.schemaDigest};
  assert.notEqual(identity.requestDigest,identity.stepInputDigest);
  const executionInput={identity:{tenantId,operationId,operationStepId:lease.id,producerAttemptId:fixture.attemptId,requestDigest:identity.requestDigest as `sha256:${string}`,stepInputDigest:identity.stepInputDigest as `sha256:${string}`},profileArtifact:identity.profileArtifact,runtime:{deploymentId:"local-structured-publication-proof",capabilityVersion:"verification-service.v1",platform:"node24-windows",code:{gitSha:"uncommitted",dirty:true,dirtyStateArtifact}},execution:{mode:"synthetic_transport" as const,networkPolicy:"disabled" as const},versions:{parser:"verification-native-parser.v1",extractor:"structured-extraction.v1",canonicalization:"verification-canonical-json.v1"},createdAt:operation.createdAt};
  const execution=await executionBuilder.prepare(executionInput);
  const boundExecution=await executionStore.bind({lease,...execution});
  const initialized=await store.initialize({identity,lease});
  const gateway=selected.providerId==="gateway-structured-extraction.v1";
  const composer=new VerificationProviderArtifactComposer(repository,{tenantId,storageBucket:"ai-engineer-cloud-bucket",producerActivityId:"structured-replay-provider",producerVersion:"v1",encryptionClass:"managed",retentionClass:"proof",now:()=>fixture.createdAt,externalProcessingGrant:{providerId:gateway?"gateway":"interfaze",dataClassification:"synthetic",modalities:["text"],...(gateway?{}:{zdrPolicy:"required" as const})},transportResponse:{binding:{tenantId,operationId,operationStepId:lease.id,providerAttemptId,profileArtifactId:identity.profileArtifact.artifactId,profileDigest:identity.profileArtifact.digest,dispatchFencingToken:lease.fencingToken},async record(input){await captures.store({lease,...input});}}});
  await composer.registerInput(new TextEncoder().encode(preparation.prompt),"text/plain");
  const accounting=new PostgresVerificationProviderAccounting(database,{lease,profileArtifactId:identity.profileArtifact.artifactId,profileDigest:identity.profileArtifact.digest as `sha256:${string}`});
  const sink=new AccountedVerificationProviderSink(composer,accounting,{tenantId,...preparation.producerProfile.budget},{attemptId:providerAttemptId,providerId:selected.providerId,model:preparation.provider.model,reservationCostMicros:100});
  const raw=JSON.stringify(failureKind==="http"?{error:{message:"Synthetic unavailable"}}:{model:preparation.provider.model,choices:[{message:{content:JSON.stringify({value:42})}}],usage:{prompt_tokens:10,completion_tokens:5,total_tokens:15}});
  const options={apiKey:"synthetic",artifactSink:sink,fetch:async()=>{syntheticFetches++;return new Response(raw,{status:failureKind==="http"?503:200});}},adapter=gateway?new GatewayStructuredExtractionProvider(options):new InterfazeStructuredExtractionProvider(options);
  const expectedCode=failureKind==="http"?"PROVIDER_HTTP_FAILURE":"PROVIDER_RESPONSE_SCHEMA_INVALID";
  await assert.rejects(adapter.extract({prompt:preparation.prompt,schemaName:"structured_extraction",schema:preparation.schema.canonicalSchema,execution:{}}),(error:unknown)=>typeof error==="object"&&error!==null&&"code" in error&&error.code===expectedCode);
  const capture=await captures.readForRecovery({lease,providerAttemptId});assert.ok(capture);
  const retaining=await store.beginRetention({lifecycle:initialized,lease,capture});
  const lifecycle=StructuredExtractionFailureLifecycleSnapshotSchema.parse(retaining);
  const replayService=new StructuredExtractionCapturedReplayService(admission,()=>repository.createTrustedArtifactResolver()),replay=await replayService.replay({tenantId,request:selected.request,preparation,capture});
  assert.equal(replay.kind,"failed");assert.ok(replay.kind==="failed");assert.equal(replay.code,expectedCode);assert.equal(replay.automaticRetry,false);assert.equal(replay.precontextBytes,null);
  const prefix=`${selected.providerId}_${failureKind}`;
  checks[`${prefix}_original_failure_captured_and_replayed`]=true;
  const candidateBuilder=new StructuredExtractionCandidateBuilder(replayService,{async register(){throw new Error("FAILURE_MUST_NOT_REGISTER_CANDIDATE");}});
  await assert.rejects(candidateBuilder.retain({tenantId,operationId,providerAttemptId,producerAttemptId:fixture.attemptId,createdAt:lifecycle.retentionStartedAt,preparation,replay}));
  const checkpoint=await failureStore.initialize({lease,lifecycle,code:expectedCode});assert.equal(checkpoint.status,"preparing");assert.equal(checkpoint.failureArtifactId,null);
  assert.deepEqual(await failureStore.initialize({lease,lifecycle,code:expectedCode}),checkpoint);
  await assert.rejects(failureStore.initialize({lease,lifecycle:{...lifecycle,identityDigest:`sha256:${"f".repeat(64)}`},code:expectedCode}),/IDENTITY_DIGEST_INVALID/);
  await assert.rejects(failureStore.initialize({lease,lifecycle,code:failureKind==="http"?"PROVIDER_RESPONSE_SCHEMA_INVALID":"PROVIDER_HTTP_FAILURE"}),/CLASSIFICATION_INVALID/);
  const sqlClaim=JSON.stringify({stepId:lease.id,leaseToken:lease.leaseToken,fencingToken:lease.fencingToken,holderIdentity:lease.holderIdentity});
  const claim=async(c:TenantSqlClient)=>{await c.query("select set_config('verification.structured_extraction_claim',$1,true)",[sqlClaim]);};
  await assert.rejects(database.transaction(tenantId,async c=>{await claim(c);await c.query("update orchestration.verification_structured_extraction set status='retained' where tenant_id=$1 and operation_id=$2",[tenantId,operationId]);}),/forbids candidate retention/);
  await assert.rejects(database.transaction(tenantId,async c=>{await claim(c);await c.query("update orchestration.verification_structured_extraction_failure set completed_at=completed_at+interval '1 second' where tenant_id=$1 and operation_id=$2",[tenantId,operationId]);}),/immutable/);
  checks[`${prefix}_checkpoint_time_identity_and_candidate_exclusion`]=true;
  const providerRow=await database.transaction(tenantId,async c=>(await c.query("select * from orchestration.verification_provider_attempt where tenant_id=$1 and id=$2",[tenantId,providerAttemptId])).rows[0]);assert.ok(providerRow);assert.equal(providerRow.state,"dispatched");
  const providerCall:StructuredExtractionProviderCallSnapshot={providerAttemptId,budgetId:String(providerRow.budget_id),providerId:preparation.producerProfile.providerId,model:String(providerRow.model),configurationDigest:preparation.provider.configurationDigest,attemptOrdinal:Number(providerRow.attempt_ordinal),reservationCostMicros:Number(providerRow.reservation_cost_micros),state:"dispatched",actualCostMicros:null,pricingBasis:"synthetic_transport",costEvidenceArtifact:lifecycle.rawResponseArtifact,supplierBillingVerified:false};
  const builder=new StructuredExtractionFailureArtifactBuilder(replayService,{artifacts:publicationPort,createResolver:()=>repository.createTrustedArtifactResolver(),signer});
  const publicationInput={tenantId,operationId,providerAttemptId,preparation,replay,lifecycle,completedAt:checkpoint.completedAt,executionArtifact:execution.artifact,providerCall};
  const stale=await builder.publish(publicationInput);
  await sink.settleOrRetain({});
  await assert.rejects(failureStore.publish({lease,lifecycle,checkpoint,...stale}),/accounting drift/);
  publicationInput.providerCall={...providerCall,state:"uncertain"};
  const publication=await builder.publish(publicationInput);
  assert.equal(publication.manifest.failure.candidateArtifact,null);assert.equal(publication.manifest.providerCall.actualCostMicros,null);
  const forged=structuredClone(publication.manifest);forged.seal.signature.signatureBase64=Buffer.alloc(64).toString("base64");
  await assert.rejects(failureStore.publish({lease,lifecycle,checkpoint,manifest:forged,artifact:publication.artifact}));
  await assert.rejects(new PostgresStructuredExtractionFailureStore(database,createEd25519Verifier({})).publish({lease,lifecycle,checkpoint,...publication}),/SIGNATURE_INVALID/);
  await assert.rejects(failureStore.publish({lease,lifecycle,checkpoint:{...checkpoint,completedAt:new Date(Date.parse(checkpoint.completedAt)+1).toISOString()},...publication}),/CHECKPOINT_DRIFT/);
  const bound=await failureStore.publish({lease,lifecycle,checkpoint,...publication});assert.equal(bound.status,"published");assert.deepEqual(await failureStore.publish({lease,lifecycle,checkpoint,...publication}),bound);
  checks[`${prefix}_signed_failure_and_actual_accounting_drift`]=true;
  await database.heartbeat(tenantId,lease,600);await new Promise(resolve=>setTimeout(resolve,800));
  const replacement=await database.claimOperation(tenantId,operationId,`${namespace}-replacement`,300_000);assert.ok(replacement&&replacement.fencingToken>lease.fencingToken);
  assert.deepEqual(await failureStore.initialize({lease:replacement,lifecycle,code:expectedCode}),bound);
  assert.deepEqual(await builder.publish(publicationInput),publication);
  assert.deepEqual(await failureStore.publish({lease:replacement,lifecycle,checkpoint,...publication}),bound);
  assert.deepEqual(await executionStore.readForRecovery({lease:replacement}),boundExecution);
  await assert.rejects(failureStore.publish({lease,lifecycle,checkpoint,...publication}),/STALE_LEASE/);
  const recoveryAccounting=new PostgresVerificationProviderAccounting(database,{lease:replacement,profileArtifactId:identity.profileArtifact.artifactId,profileDigest:identity.profileArtifact.digest as `sha256:${string}`});
  assert.equal((await recoveryAccounting.claimDispatch({tenantId,attemptId:providerAttemptId,dispatchFence:randomUUID()})).claimed,false);
  await assert.rejects(database.transaction(tenantId,async c=>{await c.query("delete from orchestration.verification_structured_extraction_failure where tenant_id=$1 and operation_id=$2",[tenantId,operationId]);}));
  checks[`${prefix}_replacement_fence_reuses_without_dispatch`]=true;
  const state=await database.transaction(tenantId,async c=>(await c.query("select p.state,p.actual_cost_micros,p.reservation_cost_micros,l.candidate_artifact_id,l.provenance_artifact_id from orchestration.verification_provider_attempt p join orchestration.verification_structured_extraction l on l.tenant_id=p.tenant_id and l.operation_id=p.operation_id where p.tenant_id=$1 and p.id=$2",[tenantId,providerAttemptId])).rows[0]);
  assert.equal(state?.state,"uncertain");assert.equal(state.actual_cost_micros,null);assert.equal(Number(state.reservation_cost_micros),100);assert.equal(state.candidate_artifact_id,null);assert.equal(state.provenance_artifact_id,null);
  const recoveryStore=new PostgresStructuredExtractionRecoveryStore(database,()=>repository.createTrustedArtifactResolver(),verifier);
  const recovered=await recoveryStore.readPublished({lease:replacement});assert.ok(recovered);assert.equal(recovered.kind,"failed");assert.deepEqual(recovered.manifest,publication.manifest);assert.deepEqual(recovered.artifact,publication.artifact);
  await assert.rejects(recoveryStore.readPublished({lease}),/STALE_LEASE/);
  await assert.rejects(recoveryStore.readPublished({lease:{...replacement,holderIdentity:'wrong-holder'}}),/STALE_LEASE/);
  await assert.rejects(new PostgresStructuredExtractionRecoveryStore(database,()=>repository.createTrustedArtifactResolver(),createEd25519Verifier({})).readPublished({lease:replacement}),/SIGNATURE_INVALID/);
  const aborted=new AbortController();aborted.abort();await assert.rejects(recoveryStore.readPublished({lease:replacement,signal:aborted.signal}),/RECOVERY_CANCELLED/);
  const corrupt=()=>{const resolver=repository.createTrustedArtifactResolver();return {authorizeArtifact:resolver.authorizeArtifact.bind(resolver),async hydrateRegisteredArtifact(input:Parameters<typeof resolver.hydrateRegisteredArtifact>[0]){const loaded=await resolver.hydrateRegisteredArtifact(input);const bytes=loaded.bytes.slice();bytes[0]=bytes[0]!^1;return {...loaded,bytes};}};};
  await assert.rejects(new PostgresStructuredExtractionRecoveryStore(database,corrupt,verifier).readPublished({lease:replacement}),/ARTIFACT_INVALID/);
  checks[`${prefix}_recovery`]=true;
  const terminalOutput=await createStructuredExtractionFailureOperationResult({...publication,verifier});
  assert.deepEqual(recovered.result,terminalOutput);
  const terminalInput={id:randomUUID(),idempotencyKey:`${namespace}-${operationId}-failed`,executorIdentity:namespace,output:terminalOutput};
  const nativeBody=await database.transaction(tenantId,async c=>(await c.query("select orchestration.structured_extraction_failure_result_body($1,$2) body,orchestration.structured_extraction_receipt_json(orchestration.structured_extraction_failure_result_body($1,$2)) canonical",[tenantId,operationId])).rows[0]);assert.deepEqual(nativeBody?.body,terminalOutput);assert.equal(nativeBody.canonical,canonicalizeJson(terminalOutput));
  await assert.rejects(database.failStep(tenantId,replacement,{id:randomUUID(),idempotencyKey:randomUUID(),executorIdentity:namespace,errorClass:expectedCode,retryable:true}),/CAPTURED_FAILURE_REQUIRES_TERMINAL/);
  await assert.rejects(database.failStep(tenantId,replacement,{id:randomUUID(),idempotencyKey:randomUUID(),executorIdentity:namespace,errorClass:expectedCode,retryable:false}),/CAPTURED_FAILURE_REQUIRES_TERMINAL/);
  await assert.rejects(database.failStructuredExtractionStep(tenantId,{...replacement,holderIdentity:'wrong-holder'},terminalInput),/CLAIM_MISMATCH/);
  await assert.rejects(database.failStructuredExtractionStep(tenantId,{...replacement,inputSha256:'f'.repeat(64)},terminalInput),/CLAIM_MISMATCH/);
  for(const output of [{...terminalOutput,extra:true},{...terminalOutput,output:{...terminalOutput.output,automaticRetry:true}},{...terminalOutput,output:{...terminalOutput.output,candidateArtifact:{artifactId:publication.artifact.artifactId,digest:publication.artifact.digest}}},{...terminalOutput,resultArtifact:{...terminalOutput.resultArtifact,byteLength:1}}])await assert.rejects(database.failStructuredExtractionStep(tenantId,replacement,{...terminalInput,output}),/OUTPUT_MISMATCH/);
  await assert.rejects(database.transaction(tenantId,async c=>{await c.query("update knowledge_service.operation_step set status='failed' where tenant_id=$1 and id=$2",[tenantId,lease.id]);}),/requires published custody and active claim/);
  await assert.rejects(database.transaction(tenantId,async c=>{await c.query("update knowledge_service.operation set status='queued' where tenant_id=$1 and id=$2",[tenantId,operationId]);}),/cannot requeue/);
  const terminalClaim={operationId,stepId:replacement.id,leaseToken:replacement.leaseToken,fencingToken:replacement.fencingToken,holderIdentity:replacement.holderIdentity,receiptId:terminalInput.id,idempotencyKey:terminalInput.idempotencyKey,executorIdentity:namespace,outputSha256:digestCanonicalJson(terminalOutput).slice(7)};
  await assert.rejects(database.transaction(tenantId,async c=>{await c.query("select set_config('verification.structured_extraction_failure_terminal_claim',$1,true)",[JSON.stringify(terminalClaim)]);await c.query("update knowledge_service.operation_step set status='failed' where tenant_id=$1 and id=$2",[tenantId,lease.id]);}),/requires exact receipt and operation/);
  checks[`${prefix}_exact_native_result_and_terminal_negatives`]=true;
  const terminalReceipt=await database.failStructuredExtractionStep(tenantId,replacement,terminalInput);
  assert.equal(terminalReceipt.outcome,'failed');assert.equal(terminalReceipt.receiptKind,'extract_and_register.failed');assert.deepEqual(await database.failStructuredExtractionStep(tenantId,replacement,terminalInput),terminalReceipt);
  await assert.rejects(database.failStructuredExtractionStep(tenantId,replacement,{...terminalInput,executorIdentity:'different-executor'}),/IDEMPOTENCY_CONFLICT/);
  const finalOperation=await database.getOperation(tenantId,operationId);assert.equal(finalOperation?.status,'failed');assert.equal((await database.listSteps(tenantId,operationId))[0]?.status,'failed');assert.equal((await database.listReceipts(tenantId,operationId)).length,1);
  checks[`${prefix}_canonical_failed_receipt_and_exact_reuse`]=true;
  results.push({recovered,terminalOutput,terminalReceipt,replacementLease:replacement,providerId:selected.providerId,failureKind,operationId,providerAttemptId,identity,lifecycle,checkpoint,bound,execution,boundExecution,publication,staleArtifact:stale.artifact,originalFencingToken:lease.fencingToken,replacementFencingToken:replacement.fencingToken});
 }
 assert.equal(syntheticFetches,4);
 const report={schemaVersion:"verification-structured-extraction-failure-terminal-proof.v1",namespace,tenantId,fixtureName,createdAt:new Date().toISOString(),executionMode:"synthetic_transport",supplierRequests:0,syntheticFetches,checks,publicKeyPem,dirtyStateArtifact,sourceFiles:sourceFiles.map(({bytesBase64,...file})=>file),results,limitations:["Captured HTTP/schema failures only; no supplier calls or billing verification","Configured worker and live public transports remain unfinished","Unknown provider costs retain 100 micros liability for each of four original calls","Runtime custody is limited to listed files"]};
 const output=resolve("../internal",`verification-structured-extraction-failure-terminal-${namespace}.json`);await writeFile(output,JSON.stringify(report,null,2)+"\n");console.log(JSON.stringify({output,checks:Object.keys(checks).length,syntheticFetches}));
}finally{
 for(const operationId of operations){const operation=await database.getOperation(tenantId,operationId);if(operation&&!['succeeded','failed','cancelled'].includes(operation.status))await database.cancelOperation(tenantId,operationId,{actorIdentity:namespace,correlationId:namespace});}
 await database.close();
}
