import assert from "node:assert/strict";
import {randomUUID,createHash} from "node:crypto";
import {readFile,writeFile} from "node:fs/promises";
import {resolve} from "node:path";
import {StructuredExtractionProfileAdmission,type StructuredExtractionRuntimeGrant} from "../packages/application/src/verification/operations/verification-structured-extraction-profile.js";
import {StructuredExtractionCapturedReplayService} from "../packages/application/src/verification/operations/verification-structured-extraction-replay.js";
import {StructuredExtractionCandidateBuilder} from "../packages/application/src/verification/operations/verification-structured-extraction-candidate.js";
import {VerificationAdmissionService} from "../packages/application/src/verification/admission/verification-admission.js";
import {AccountedVerificationProviderSink,VerificationProviderArtifactComposer} from "../packages/application/src/verification/operations/verification-provider.js";
import {PostgresCanonicalRepository,PostgresVerificationRepository,PostgresKnowledgeOperationService} from "../packages/persistence/src/index.js";
import {PostgresVerificationProviderResponseCaptureStore} from "../packages/persistence/src/verification-provider-response-capture.js";
import {PostgresVerificationProviderAccounting} from "../packages/persistence/src/verification-provider-accounting.js";
import {PostgresStructuredExtractionLifecycleStore,type StructuredExtractionLifecycleIdentity} from "../packages/persistence/src/verification-structured-extraction-lifecycle.js";
import {SupabaseArtifactStore} from "@aiengineer/knowledge-runtime";
import {SandboxedVerificationParser,VERIFICATION_PARSER_LIMITS} from "@aiengineer/knowledge-conversion";
import {GatewayStructuredExtractionProvider,InterfazeStructuredExtractionProvider} from "@aiengineer/knowledge-verification";

const pgUrl=process.env.POSTGRES_URL!,storageUrl=process.env.SUPABASE_URL!;
for(const[value,port]of [[pgUrl,"54322"],[storageUrl,"54321"]]){const url=new URL(value!);if(!["localhost","127.0.0.1"].includes(url.hostname)||url.port!==port)throw new Error("LOCAL_ONLY_PROOF_REQUIRED");}
const fixtureName="verification-structured-extraction-preparation-c6085a8a-8c56-4923-a9ed-dd09666d223d.json";
const fixture=JSON.parse(await readFile(resolve("../internal",fixtureName),"utf8")) as {tenantId:string;attemptId:string;missionId:string;workItemId:string;createdAt:string;imageDigest:`sha256:${string}`;profiles:{providerId:string;grant:StructuredExtractionRuntimeGrant;request:unknown}[]};
const tenantId=fixture.tenantId,namespace=randomUUID(),operations:string[]=[],results:unknown[]=[],checks:Record<string,boolean>={};let syntheticFetches=0;
const database=new PostgresCanonicalRepository({connectionString:pgUrl,localOnly:true}),store=new PostgresStructuredExtractionLifecycleStore(database),captures=new PostgresVerificationProviderResponseCaptureStore(database);
const operationService=new PostgresKnowledgeOperationService(database,{admittedOperationKinds:["verification_structured_extraction"]});
const repository=new PostgresVerificationRepository(database,new SupabaseArtifactStore({projectUrl:storageUrl,serviceRoleKey:process.env.SUPABASE_SECRET_KEY!,bucket:"ai-engineer-cloud-bucket",maximumBytes:8_000_000}),{async authorize(v){assert.equal(v.tenantId,tenantId);assert.equal(v.purpose,"verification_admission");}});
const native=new VerificationAdmissionService(repository,new SandboxedVerificationParser(fixture.imageDigest),{parserVersion:"verification-native-parser.v1",imageDigest:fixture.imageDigest,limits:VERIFICATION_PARSER_LIMITS},{storageBucket:"ai-engineer-cloud-bucket",producerVersion:"structured-extraction-proof.v1",encryptionClass:"supabase-managed",retentionClass:"verification-audit",now:()=>fixture.createdAt});
try{
 await assert.rejects(new PostgresKnowledgeOperationService(database).submit("verification_structured_extraction",{},"http://localhost"),/CAPABILITY_NOT_ADMITTED/);checks.default_admission_still_closed=true;
 for(const selected of fixture.profiles){
  const admission=new StructuredExtractionProfileAdmission([selected.grant],()=>repository.createTrustedArtifactResolver(),native),preparation=await admission.prepare({tenantId,request:selected.request});
  const operationId=randomUUID(),providerAttemptId=randomUUID();operations.push(operationId);
  const context={tenantId,operationId,attemptId:fixture.attemptId,missionId:fixture.missionId,workItemId:fixture.workItemId,correlationId:namespace,actor:{kind:"service",id:namespace,serviceIdentity:"knowledge_worker"},capabilityVersion:"verification-service.v1",idempotencyKey:`${namespace}-${operationId}`,reason:"Synthetic local lifecycle proof",contractVersion:"v1"};
  await operationService.submit("verification_structured_extraction",{context,input:{schemaVersion:"verification-service-request.v1",useCase:"extractStructuredData",request:selected.request},expectedVersions:{verification:"verification.v1",service:"verification-service-request.v1"}},"http://localhost");
  const operation=await database.getOperation(tenantId,operationId),lease=await database.claimOperation(tenantId,operationId,namespace,300_000);assert.ok(operation&&lease);
  const identity:StructuredExtractionLifecycleIdentity={tenantId,operationId,operationStepId:lease.id,producerAttemptId:fixture.attemptId,requestDigest:`sha256:${operation.requestSha256}`,stepInputDigest:`sha256:${lease.inputSha256}`,captureId:preparation.captureId,profileArtifact:preparation.artifacts.producerProfile,schemaArtifact:preparation.artifacts.extractionSchema,sourceArtifact:preparation.artifacts.source,representationArtifact:preparation.representation,transformationArtifact:preparation.artifacts.transformation,promptDigest:preparation.promptDigest,schemaDigest:preparation.schema.schemaDigest};
  assert.notEqual(identity.requestDigest,identity.stepInputDigest);
  const initialized=await store.initialize({identity,lease});assert.equal(initialized.status,"running");assert.deepEqual(await store.initialize({identity,lease}),initialized);
  await assert.rejects(store.initialize({identity:{...identity,requestDigest:`sha256:${"f".repeat(64)}`},lease}));
  await assert.rejects(store.initialize({identity:{...identity,stepInputDigest:`sha256:${"f".repeat(64)}`},lease}));
  checks[`${selected.providerId}_canonical_identity_and_two_digest_bindings`]=true;
  const gateway=selected.providerId==="gateway-structured-extraction.v1";
  const composer=new VerificationProviderArtifactComposer(repository,{tenantId,storageBucket:"ai-engineer-cloud-bucket",producerActivityId:"structured-replay-provider",producerVersion:"v1",encryptionClass:"managed",retentionClass:"proof",now:()=>fixture.createdAt,externalProcessingGrant:{providerId:gateway?"gateway":"interfaze",dataClassification:"synthetic",modalities:["text"],...(gateway?{}:{zdrPolicy:"required" as const})},transportResponse:{binding:{tenantId,operationId,operationStepId:lease.id,providerAttemptId,profileArtifactId:identity.profileArtifact.artifactId,profileDigest:identity.profileArtifact.digest,dispatchFencingToken:lease.fencingToken},async record(input){await captures.store({lease,...input});}}});
  await composer.registerInput(new TextEncoder().encode(preparation.prompt),"text/plain");
  const accounting=new PostgresVerificationProviderAccounting(database,{lease,profileArtifactId:identity.profileArtifact.artifactId,profileDigest:identity.profileArtifact.digest as `sha256:${string}`});
  const sink=new AccountedVerificationProviderSink(composer,accounting,{tenantId,...preparation.producerProfile.budget},{attemptId:providerAttemptId,providerId:selected.providerId,model:preparation.provider.model,reservationCostMicros:100});
  const raw=JSON.stringify({model:preparation.provider.model,choices:[{message:{content:JSON.stringify({value:"Exact value 42"})}}],precontext:gateway?[]:[{name:"scraper",result:{selected:"Exact value 42"}}],usage:{prompt_tokens:10,completion_tokens:5,total_tokens:15,cost:0.00001}});
  const options={apiKey:"synthetic",artifactSink:sink,fetch:async()=>{syntheticFetches++;return new Response(raw,{status:200});}},adapter=gateway?new GatewayStructuredExtractionProvider(options):new InterfazeStructuredExtractionProvider(options);
  await adapter.extract({prompt:preparation.prompt,schemaName:"structured_extraction",schema:preparation.schema.canonicalSchema,execution:{}});
  const capture=await captures.readForRecovery({lease,providerAttemptId});assert.ok(capture);
  const unsettled=await database.transaction(tenantId,async c=>(await c.query("select state,response_artifact_id from orchestration.verification_provider_attempt where tenant_id=$1 and id=$2",[tenantId,providerAttemptId])).rows[0]);assert.equal(unsettled?.state,"dispatched");assert.equal(unsettled?.response_artifact_id,null);
  const retaining=await store.beginRetention({lifecycle:initialized,lease,capture});assert.equal(retaining.status,"retaining");assert.ok(retaining.retentionStartedAt);assert.ok(Date.parse(retaining.retentionStartedAt)>=Date.parse(capture.capturedAt));assert.deepEqual(await store.beginRetention({lifecycle:initialized,lease,capture}),retaining);
  await sink.settleOrRetain({costMicros:10});checks[`${selected.providerId}_capture_checkpoint_before_accounting_settlement`]=true;
  const replayService=new StructuredExtractionCapturedReplayService(admission,()=>repository.createTrustedArtifactResolver()),replay=await replayService.replay({tenantId,request:selected.request,preparation,capture});assert.equal(replay.kind,"accepted");
  const builder=new StructuredExtractionCandidateBuilder(replayService,{async register(input){return repository.registerContentAddressedArtifact({...input,producerActivityId:"structured-lifecycle-proof",producerVersion:"v1",mediaType:"application/json",encryptionClass:"supabase-managed",retentionClass:"verification-audit",dataClassification:"restricted",bucketClass:"candidate",storageBucket:"ai-engineer-cloud-bucket"});}});
  const candidateInput={tenantId,operationId,providerAttemptId,producerAttemptId:fixture.attemptId,createdAt:retaining.retentionStartedAt,preparation,replay};
  const candidate=await builder.retain(candidateInput);
  await assert.rejects(store.completeRetention({lifecycle:retaining,lease,candidate:{...candidate,provenance:{...candidate.provenance,operationId:randomUUID()}}}));
  await assert.rejects(store.completeRetention({lifecycle:retaining,lease:{...lease,fencingToken:lease.fencingToken+1},candidate}));
  const sqlClaim=JSON.stringify({stepId:lease.id,leaseToken:lease.leaseToken,fencingToken:lease.fencingToken,holderIdentity:lease.holderIdentity});
  await assert.rejects(database.transaction(tenantId,async c=>{await c.query("select set_config('verification.structured_extraction_claim',$1,true)",[sqlClaim]);await c.query("update orchestration.verification_structured_extraction set status='retained',candidate_artifact_id=$3,candidate_sha256=$4,provenance_artifact_id=$5,provenance_sha256=$6 where tenant_id=$1 and operation_id=$2",[tenantId,operationId,identity.sourceArtifact.artifactId,identity.sourceArtifact.digest.slice(7),candidate.provenanceArtifact.artifactId,candidate.provenanceArtifact.digest.slice(7)]);}),/candidate semantic binding mismatch/);
  await assert.rejects(database.transaction(tenantId,async c=>{await c.query("select set_config('verification.structured_extraction_claim',$1,true)",[sqlClaim]);await c.query("update orchestration.verification_structured_extraction set prompt_sha256=$3 where tenant_id=$1 and operation_id=$2",[tenantId,operationId,"f".repeat(64)]);}),/immutable identity/);
  checks[`${selected.providerId}_direct_sql_artifact_and_identity_substitution_denied`]=true;
  const completed=await store.completeRetention({lifecycle:retaining,lease,candidate});assert.equal(completed.status,"retained");assert.ok(completed.completedAt);assert.deepEqual(await store.completeRetention({lifecycle:retaining,lease,candidate}),completed);
  checks[`${selected.providerId}_fenced_candidate_and_original_times`]=true;
  await assert.rejects(database.transaction(tenantId,async c=>{await c.query("update orchestration.verification_structured_extraction set status=status where tenant_id=$1 and operation_id=$2",[tenantId,operationId]);}));
  await assert.rejects(database.transaction(tenantId,async c=>{await c.query("delete from orchestration.verification_structured_extraction where tenant_id=$1 and operation_id=$2",[tenantId,operationId]);}));
  await database.heartbeat(tenantId,lease,600);await new Promise(resolve=>setTimeout(resolve,800));
  const replacement=await database.claimOperation(tenantId,operationId,`${namespace}-replacement`,300_000);assert.ok(replacement&&replacement.fencingToken>lease.fencingToken);
  assert.deepEqual(await store.initialize({identity,lease:replacement}),completed);
  await assert.rejects(store.completeRetention({lifecycle:retaining,lease,candidate}));
  assert.deepEqual(await builder.retain(candidateInput),candidate);
  assert.deepEqual(await store.completeRetention({lifecycle:retaining,lease:replacement,candidate}),completed);
  const recoveryAccounting=new PostgresVerificationProviderAccounting(database,{lease:replacement,profileArtifactId:identity.profileArtifact.artifactId,profileDigest:identity.profileArtifact.digest as `sha256:${string}`});assert.equal((await recoveryAccounting.claimDispatch({tenantId,attemptId:providerAttemptId,dispatchFence:randomUUID()})).claimed,false);
  checks[`${selected.providerId}_replacement_reuses_retained_without_dispatch`]=true;
  await assert.rejects(database.transaction(tenantId,async c=>{await c.query("update knowledge_service.operation set status='succeeded' where tenant_id=$1 and id=$2",[tenantId,operationId]);}),/terminal lifecycle not configured/);
  await database.cancelOperation(tenantId,operationId,{actorIdentity:namespace,correlationId:namespace});
  await assert.rejects(store.completeRetention({lifecycle:retaining,lease:replacement,candidate}));checks[`${selected.providerId}_cancellation_and_unpublished_terminal_guard`]=true;
  results.push({providerId:selected.providerId,identity,capture,initialized,retaining,completed,candidate,originalFence:lease.fencingToken,replacementFence:replacement.fencingToken});
 }
 assert.equal(syntheticFetches,2);
 const paths=["packages/persistence/src/verification-structured-extraction-lifecycle.ts","packages/application/src/verification/operations/verification-structured-extraction-candidate.ts","packages/application/src/verification/operations/verification-service.ts","../ai-engineer-db-contract/supabase/migrations/20260906031700_verification_structured_extraction_lifecycle.sql","scripts/prove-verification-structured-extraction-lifecycle.ts"];
 const sources=await Promise.all(paths.map(async path=>({path,sha256:createHash("sha256").update(await readFile(path)).digest("hex")})));
 const output=resolve("../internal",`verification-structured-extraction-lifecycle-${namespace}.json`);await writeFile(output,JSON.stringify({passed:true,scope:"actual local canonical lifecycle/candidate checkpoint with actual adapters and injected synthetic transport; no terminal publication or supplier calls",tenantId,fixture:fixtureName,syntheticFetches,externalProviderRequests:0,checks,results,sources},null,2),{flag:"wx"});console.log(JSON.stringify({passed:true,output,checks:Object.keys(checks).length}));
}finally{for(const operationId of operations)await database.cancelOperation(tenantId,operationId,{actorIdentity:namespace,correlationId:namespace});await database.close();}
