import assert from "node:assert/strict";
import { createHash,randomUUID } from "node:crypto";
import { readFile,writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { VerificationAdjudicationOperationResultSchema,VerificationAdjudicationPacketSchema,VerificationClaimsOperationResultSchema,VerificationReportOperationResultSchema,type OperationContext,type VerificationArtifactHandle } from "@aiengineer/knowledge-contracts";
import { VerificationAdmissionService,VerificationAuditInspectionGrantCatalog,VerificationClaimsProjectionGrantCatalog } from "@aiengineer/knowledge-application";
import { VERIFICATION_PARSER_LIMITS } from "@aiengineer/knowledge-conversion";
import { PostgresCanonicalRepository,PostgresVerificationAdjudicationRepository,PostgresKnowledgeOperationService,PostgresVerificationRepository,type LeasedStep } from "@aiengineer/knowledge-persistence";
import { deterministicUuid,SupabaseArtifactStore } from "@aiengineer/knowledge-runtime";
import { canonicalizeJson,digestCanonicalJson } from "@aiengineer/knowledge-verification";
import { KnowledgeClient } from "@aiengineer/knowledge-client";
import { buildServer } from "../apps/api/src/server.js";
import { createVerificationOwnershipResolver } from "../apps/api/src/verification-ownership.js";
import { dispatchCliCommand,resolveCommand } from "../apps/cli/src/commands.js";
import { createVerificationMcpToolExecutor } from "../apps/mcp/src/index.js";
import { CanonicalActivityRegistry,createCanonicalActivityExecutor } from "../apps/worker/src/activity-registry.js";
import { CanonicalDurableKnowledgeWorker } from "../apps/worker/src/canonical-worker.js";
import { createVerificationAdjudicationRequestHandler } from "../apps/worker/src/verification-adjudication-runtime.js";

if(process.env.VERIFICATION_ADJUDICATION_NATIVE_PROOF!=="1")throw new Error("ADJUDICATION_LOCAL_PROOF_OPT_IN_REQUIRED");
const proofPath=resolve(process.argv[2]??"../internal/verification-claims-report-worker-22c6b3e4-b5d6-4d34-923b-4846e37fdfaa.json");
const proof=JSON.parse(await readFile(proofPath,"utf8")) as {namespace:string;tenantId:string;publicKeyPem:string;projection:{captureId:string;projectionArtifact:VerificationArtifactHandle;transformationArtifact:VerificationArtifactHandle};results:{claimsRecovery:{operationId:string;runId:string;manifestArtifact:VerificationArtifactHandle};reportRecovery:{operationId:string;runId:string;manifestArtifact:VerificationArtifactHandle}}};
const fixture=JSON.parse(await readFile(resolve("../internal/verification-frozen-source-registry-7a74a7a8-0dc4-4591-8bb1-5781ebddef42.json"),"utf8")) as {records:readonly{captureId:string;projections:readonly[{sourceArtifact:VerificationArtifactHandle;projectionArtifact:VerificationArtifactHandle;transformationArtifact:VerificationArtifactHandle;parserVersion:string;imageDigest:`sha256:${string}`}]}[]};
const nativeProjection=fixture.records.find(item=>item.captureId===proof.projection.captureId)?.projections[0];assert.ok(nativeProjection);assert.equal(digestCanonicalJson(nativeProjection.projectionArtifact),digestCanonicalJson(proof.projection.projectionArtifact));
// @ts-expect-error reviewed local-only helper intentionally lives outside the package graph.
const {loadVerifiedLocalDevelopmentConfig}=await import("../../internal/verification-local-direct-config.mjs") as {loadVerifiedLocalDevelopmentConfig():Promise<{DB_URL:string;API_URL:string;SECRET_KEY:string}>};
const local=await loadVerifiedLocalDevelopmentConfig();for(const [value,port] of [[local.DB_URL,"54322"],[local.API_URL,"54321"]] as const){const url=new URL(value);if(!["localhost","127.0.0.1"].includes(url.hostname)||url.port!==port)throw new Error("LOCAL_ONLY_AUDIT_PROOF_REQUIRED");}
const namespace=randomUUID(),tenantId=proof.tenantId,missionId=randomUUID(),deploymentId=`audit-inspection-proof-${namespace}`,bucket="ai-engineer-cloud-bucket",token=`audit-proof-token-${namespace}`;
const actor={kind:"service" as const,id:randomUUID(),serviceIdentity:"mission_control_client" as const},surfaces=["http","client","cli","mcp"] as const,kinds=["claims","report"] as const;
type Plan={surface:typeof surfaces[number];kind:typeof kinds[number];operationId:string;workItemId:string;attemptId:string;idempotencyKey:string;context:OperationContext};
const plans:Plan[]=[];for(const kind of kinds)for(const surface of surfaces){const idempotencyKey=`audit-${namespace}-${kind}-${surface}`,operationId=deterministicUuid("verification-http-operation",`${tenantId}:requestAdjudication:${idempotencyKey}`),workItemId=randomUUID(),attemptId=randomUUID();plans.push({kind,surface,operationId,workItemId,attemptId,idempotencyKey,context:{contractVersion:"v1",tenantId,operationId,attemptId,missionId,workItemId,correlationId:`audit-${kind}-${surface}`,actor,capabilityVersion:"verification-adjudication.v1",idempotencyKey,reason:"Native public audit inspection proof"}});}
const denied={operationId:deterministicUuid("verification-http-operation",`${tenantId}:requestAdjudication:audit-${namespace}-denied`),workItemId:randomUUID(),attemptId:randomUUID(),idempotencyKey:`audit-${namespace}-denied`};
const cancelled={operationId:deterministicUuid("verification-http-operation",`${tenantId}:requestAdjudication:audit-${namespace}-cancelled`),workItemId:randomUUID(),attemptId:randomUUID(),idempotencyKey:`audit-${namespace}-cancelled`};
const startupJournal=resolve("../internal",`verification-adjudication-worker-startup-${namespace}.json`);await writeFile(startupJournal,JSON.stringify({schemaVersion:"verification-adjudication-worker-startup.v1",namespace,tenantId,missionId,plannedOperationIds:[...plans.map(p=>p.operationId),denied.operationId,cancelled.operationId],sourceProof:proofPath,intendedMutationScope:"isolated local adjudication request worker and transport proof",createdAt:new Date().toISOString()},null,2)+"\n",{flag:"wx"});
const database=new PostgresCanonicalRepository({connectionString:local.DB_URL,localOnly:true});let server:ReturnType<typeof buildServer>|undefined;const createdOperationIds:string[]=[];
try{
  const allOwnership=[...plans,denied,cancelled];await database.transaction(tenantId,async client=>{await client.query("insert into orchestration.mission(id,tenant_id,slug,goal) values($1,$2,$3,$4)",[missionId,tenantId,`audit-inspection-${namespace}`,"Native public audit inspection proof"]);for(const item of allOwnership){await client.query("insert into orchestration.work_item(id,tenant_id,mission_id,kind,spec) values($1,$2,$3,'verify_extraction',$4::jsonb)",[item.workItemId,tenantId,missionId,JSON.stringify({namespace,role:"audit_inspector"})]);await client.query("insert into orchestration.attempt(id,tenant_id,work_item_id,attempt_no,agent_deployment_id,started_at) values($1,$2,$3,1,$4,$5)",[item.attemptId,tenantId,item.workItemId,deploymentId,new Date().toISOString()]);}});
  const artifacts=new SupabaseArtifactStore({projectUrl:local.API_URL,serviceRoleKey:local.SECRET_KEY,bucket,maximumBytes:32_000_000});
  const repository=new PostgresVerificationRepository(database,artifacts,{async authorize(input){assert.equal(input.tenantId,tenantId);assert.ok(["verification_admission","verification_replay","policy_replay"].includes(input.purpose));}});
  const subjects=new PostgresVerificationAdjudicationRepository(database,repository);
  const admission=new VerificationAdmissionService(repository,{async parse():Promise<never>{throw new Error("PARSER_FORBIDDEN_IN_AUDIT_PUBLIC_PROOF");}},{parserVersion:nativeProjection.parserVersion as "verification-native-parser.v1",imageDigest:nativeProjection.imageDigest,limits:VERIFICATION_PARSER_LIMITS},{storageBucket:bucket,producerVersion:"verification-admission.v1",encryptionClass:"supabase-managed",retentionClass:"verification-audit",now:()=>new Date().toISOString()});
  async function sourceTerminal(kind:"claims"|"report"){const entry=kind==="claims"?proof.results.claimsRecovery:proof.results.reportRecovery,receipts=await database.listReceipts(tenantId,entry.operationId);assert.equal(receipts.length,1);const {eventId:_eventId,fencingToken:_fencingToken,...body}=receipts[0]!.body as Record<string,unknown>;return kind==="claims"?VerificationClaimsOperationResultSchema.parse(body):VerificationReportOperationResultSchema.parse(body);}
  const terminals={claims:await sourceTerminal("claims"),report:await sourceTerminal("report")};
  const projectionGrants=new VerificationClaimsProjectionGrantCatalog(kinds.map(kind=>({tenantId,assertions:{artifactId:terminals[kind].output.verified.assertionsArtifact.artifactId,digest:terminals[kind].output.verified.assertionsArtifact.digest},admissions:[{captureId:proof.projection.captureId,projectionArtifactId:nativeProjection.projectionArtifact.artifactId,transformationArtifactId:nativeProjection.transformationArtifact.artifactId}]})));
  const auditGrantValues=kinds.map(kind=>{const entry=kind==="claims"?proof.results.claimsRecovery:proof.results.reportRecovery;return{tenantId,auditArtifact:{artifactId:entry.manifestArtifact.artifactId,digest:entry.manifestArtifact.digest},runKind:kind};});
  const auditGrants=new VerificationAuditInspectionGrantCatalog(auditGrantValues),handler=createVerificationAdjudicationRequestHandler({subjects,reviewRequirements:{eligibleReviewerRoles:["expert"],quorumRequired:2},database,repository,admission,projectionGrants,auditGrants,trustedPublicKeys:{[`claims-report-proof-${proof.namespace}`]:proof.publicKeyPem},storageBucket:bucket,maximumInspectionMs:30_000,now:()=>new Date().toISOString()});
  const registry=new CanonicalActivityRegistry([handler]),executor=createCanonicalActivityExecutor(database,registry),operationService=new PostgresKnowledgeOperationService(database,{admittedOperationKinds:["verification_adjudication"]});
  const ownershipGrants=JSON.stringify([{tenantId,actor,missionId,agentDeploymentId:deploymentId,capabilityVersion:"verification-adjudication.v1"}]);
  const admissionCheck=async(candidateTenant:string,request:any)=>{let grant;try{grant=auditGrants.resolve(candidateTenant,{verificationContractVersion:request.verificationContractVersion,auditBundle:request.evidencePacket});}catch{return false;}const expectedKind=grant.runKind==="claims"?"verification_claims":"verification_report";const rows=await database.transaction(candidateTenant,async client=>(await client.query<{operation_kind:string;status:string}>("select o.operation_kind,o.status from evidence.verification_run r join knowledge_service.operation o on o.tenant_id=r.tenant_id and o.id=r.operation_id where r.tenant_id=$1 and r.run_manifest_artifact_id=$2 and r.manifest_sha256=$3",[candidateTenant,request.evidencePacket.artifactId,request.evidencePacket.digest.slice(7)])).rows);return rows.length===1&&rows[0]!.operation_kind===expectedKind&&rows[0]!.status==="succeeded";};
  server=buildServer({publicOrigin:"http://127.0.0.1",verificationOperationService:operationService,isAdjudicationRequestAdmitted:admissionCheck,resolveIdentity:candidate=>candidate===token?{actor,grants:[{tenantId,roles:["knowledge_operator"],scopes:[]}]}:undefined,resolveVerificationContext:createVerificationOwnershipResolver(database,ownershipGrants)});await server.listen({host:"127.0.0.1",port:0});const address=server.server.address();assert.ok(address&&typeof address!=="string");const baseUrl=`http://127.0.0.1:${address.port}`,client=new KnowledgeClient({baseUrl,getAccessToken:()=>token});
  const requestFor=(kind:"claims"|"report")=>{const entry=kind==="claims"?proof.results.claimsRecovery:proof.results.reportRecovery;return{verificationContractVersion:"verification.v1" as const,target:{kind:"run" as const,runId:entry.runId},reason:"appeal" as const,evidencePacket:{artifactId:entry.manifestArtifact.artifactId,digest:entry.manifestArtifact.digest as `sha256:${string}`}};};
  const headers=(plan:{attemptId:string;workItemId:string;idempotencyKey:string},correlationId:string)=>({authorization:`Bearer ${token}`,"content-type":"application/json","x-tenant-id":tenantId,"x-correlation-id":correlationId,"idempotency-key":plan.idempotencyKey,"x-verification-attempt-id":plan.attemptId,"x-verification-work-item-id":plan.workItemId,"x-verification-mission-id":missionId});
  for(const plan of plans){const request=requestFor(plan.kind),wireContext={tenantId,correlationId:plan.context.correlationId,idempotencyKey:plan.idempotencyKey,attemptId:plan.attemptId,workItemId:plan.workItemId,missionId};let accepted:any;if(plan.surface==="http"){const response=await fetch(`${baseUrl}/v1/verification/adjudications:request`,{method:"POST",headers:headers(plan,plan.context.correlationId),body:JSON.stringify(request)});assert.equal(response.status,202);accepted=await response.json();}else if(plan.surface==="client")accepted=await client.requestAdjudication(request,wireContext);else if(plan.surface==="cli")accepted=await dispatchCliCommand(client as never,resolveCommand("adjudication","request")!,request,plan.context);else accepted=(await createVerificationMcpToolExecutor({operationService,apiOrigin:baseUrl,identity:{actor,grants:[{tenantId,roles:["knowledge_operator"],scopes:[]}]},apiClient:client})("knowledge_request_adjudication",{context:wireContext,request}) as any).structuredContent;assert.equal(accepted.operationId,plan.operationId);createdOperationIds.push(plan.operationId);}
  const deniedResponse=await fetch(`${baseUrl}/v1/verification/adjudications:request`,{method:"POST",headers:headers(denied,"audit-denied"),body:JSON.stringify({...requestFor("claims"),evidencePacket:{...requestFor("claims").evidencePacket,digest:`sha256:${"0".repeat(64)}`}})});assert.equal(deniedResponse.status,403);assert.equal(await database.getOperation(tenantId,denied.operationId),undefined);
  const cancelledRequest=requestFor("claims"),cancelledAccepted=await fetch(`${baseUrl}/v1/verification/adjudications:request`,{method:"POST",headers:headers(cancelled,"audit-cancelled"),body:JSON.stringify(cancelledRequest)});assert.equal(cancelledAccepted.status,202);createdOperationIds.push(cancelled.operationId);const cancelledLease=await database.claimOperation(tenantId,cancelled.operationId,`${namespace}-cancelled`,30_000);assert.ok(cancelledLease);await database.cancelOperation(tenantId,cancelled.operationId,{actorIdentity:`service:${actor.id}`,correlationId:randomUUID()});await assert.rejects(executor(cancelledLease));assert.equal((await database.getOperation(tenantId,cancelled.operationId))?.status,"cancelled");assert.equal((await database.listReceipts(tenantId,cancelled.operationId)).length,0);
  let interruptedLease:LeasedStep|undefined;const interruptedDatabase=new Proxy(database,{get(target,property){if(property==="completeStep")return async(_tenant:string,lease:LeasedStep)=>{interruptedLease=lease;throw new Error("SIMULATED_POST_RESULT_STOP");};if(property==="failStep")return async()=>{throw new Error("SIMULATED_STOP_PREVENTS_CATCH_CLEANUP");};const value=Reflect.get(target,property,target);return typeof value==="function"?value.bind(target):value;}});const first=plans[0]!;const interruptedWorker=new CanonicalDurableKnowledgeWorker(`${namespace}-interrupted`,tenantId,interruptedDatabase,executor,350,registry.operationKinds());await assert.rejects(interruptedWorker.runOperationOnce(first.operationId),/SIMULATED_POST_RESULT_STOP/);assert.ok(interruptedLease);assert.equal((await database.listReceipts(tenantId,first.operationId)).length,0);await new Promise(resolveWait=>setTimeout(resolveWait,550));const worker=new CanonicalDurableKnowledgeWorker(`${namespace}-worker`,tenantId,database,executor,30_000,registry.operationKinds());const recovered=await worker.runOperationOnce(first.operationId);assert.ok(recovered);const recoveredReceipt=(await database.listReceipts(tenantId,first.operationId))[0]!;assert.ok(Number((recoveredReceipt.body as any).fencingToken)>interruptedLease.fencingToken);
  for(const plan of plans.slice(1))assert.ok(await worker.runOperationOnce(plan.operationId));
  const publicResults=[];
  for(const plan of plans){
    assert.equal((await database.getOperation(tenantId,plan.operationId))?.status,"succeeded");
    const receipts=await database.listReceipts(tenantId,plan.operationId);assert.equal(receipts.length,1);
    const {eventId,fencingToken,...body}=receipts[0]!.body as Record<string,unknown>;
    assert.equal(typeof eventId,"string");assert.ok(Number(fencingToken)>0);
    const result=VerificationAdjudicationOperationResultSchema.parse(body);
    assert.equal(result.operationId,plan.operationId);assert.equal(result.requestDigest,digestCanonicalJson(requestFor(plan.kind)));
    assert.equal(result.output.status,"pending_human_adjudication");assert.equal(result.output.humanDecisionRecorded,false);assert.equal(result.output.admissionChanged,false);
    const resolver=repository.createTrustedArtifactResolver();await resolver.authorizeArtifact({tenantId,artifactId:result.resultArtifact.artifactId,purpose:"verification_replay"});
    const hydrated=await resolver.hydrateRegisteredArtifact({tenantId,artifactId:result.resultArtifact.artifactId});
    const packet=VerificationAdjudicationPacketSchema.parse(JSON.parse(new TextDecoder("utf-8",{fatal:true}).decode(hydrated.bytes)));
    assert.equal(digestCanonicalJson(packet),result.resultArtifact.digest);assert.equal(packet.requestBinding.requestDigest,result.requestDigest);
    assert.deepEqual(packet.requestBinding.target,requestFor(plan.kind).target);assert.equal(packet.reviewRequirements.quorumRequired,2);
    const rows=await database.transaction(tenantId,async connection=>(await connection.query("select id,packet_artifact_id,packet_sha256,request_payload_sha256,run_kind from evidence.verification_adjudication_subject where tenant_id=$1 and request_operation_id=$2",[tenantId,plan.operationId])).rows);
    assert.equal(rows.length,1);assert.ok(rows[0]);assert.equal(rows[0].id,result.output.subjectId);assert.equal(rows[0].packet_artifact_id,result.resultArtifact.artifactId);assert.equal(rows[0].packet_sha256,result.resultArtifact.digest.slice(7));assert.equal(rows[0].request_payload_sha256,result.requestDigest.slice(7));assert.equal(rows[0].run_kind,plan.kind);
    publicResults.push({kind:plan.kind,surface:plan.surface,operationId:plan.operationId,subjectId:result.output.subjectId,packetArtifact:{artifactId:result.resultArtifact.artifactId,digest:result.resultArtifact.digest},originalPolicyOutcome:result.output.originalPolicyOutcome,receiptId:receipts[0]!.id,fencingToken:Number(fencingToken)});
  }
  const cancelledSubjects=await database.transaction(tenantId,async connection=>(await connection.query("select id from evidence.verification_adjudication_subject where tenant_id=$1 and request_operation_id=$2",[tenantId,cancelled.operationId])).rows);assert.equal(cancelledSubjects.length,0);
  const cancelledPackets=await database.transaction(tenantId,async connection=>(await connection.query("select id from orchestration.artifact where tenant_id=$1 and producer_attempt_id=$2 and artifact_type='verification_adjudication_packet'",[tenantId,cancelled.attemptId])).rows);assert.equal(cancelledPackets.length,0);
  const authorityInjection=await fetch(`${baseUrl}/v1/verification/adjudications:request`,{method:"POST",headers:headers(denied,"adjudication-authority-denied"),body:JSON.stringify({...requestFor("claims"),decision:"overturn",humanGold:true})});assert.equal(authorityInjection.status,400);assert.equal(await database.getOperation(tenantId,denied.operationId),undefined);
  const sourcePaths=["packages/contracts/src/verification/adjudication.ts","packages/application/src/verification-adjudication.ts","packages/persistence/src/verification-adjudication.ts","apps/worker/src/verification-adjudication-activity.ts","apps/worker/src/verification-adjudication-runtime.ts","apps/worker/src/verification-audit-inspection-runtime.ts","apps/api/src/server.ts","packages/client-typescript/src/client.ts","apps/cli/src/commands.ts","apps/mcp/src/index.ts","scripts/prove-verification-adjudication-worker.ts"];
  const sourceFiles=await Promise.all(sourcePaths.map(async path=>({path,sha256:createHash("sha256").update(await readFile(path)).digest("hex")})));
  const output=resolve("../internal",`verification-adjudication-worker-${namespace}.json`),receipt={schemaVersion:"verification-adjudication-worker-proof.v1",namespace,tenantId,sourceProof:{path:proofPath,sha256:createHash("sha256").update(await readFile(proofPath)).digest("hex")},startupJournal,createdAt:new Date().toISOString(),checks:{exact_claims_report_grants_before_enqueue:true,http_client_cli_mcp_submission_and_native_packet_subjects:true,canonical_signed_source_inspected_before_packet:true,post_result_completion_interruption_reclaimed_with_higher_fence:true,cancelled_activity_has_no_receipt:true,wrong_digest_has_no_operation:true,pending_subjects_do_not_record_human_decision_or_admission:true},parserDispatches:0,providerDispatches:0,results:publicResults,cancelledOperationId:cancelled.operationId,deniedOperationId:denied.operationId,sourceFiles,limitations:["Claims/report run-target request packets only; human decisions/overrides and public terminal reads remain separate","Local development PostgreSQL and Storage; no remote environment","Post-result interruption is injected at completeStep; no OS process kill"]};await writeFile(output,JSON.stringify(receipt,null,2)+"\n",{flag:"wx"});console.log(JSON.stringify({output,sha256:createHash("sha256").update(await readFile(output)).digest("hex"),checks:Object.keys(receipt.checks).length,operations:createdOperationIds.length,parserDispatches:0,providerDispatches:0}));
}catch(error){const failure=error instanceof Error?error:new Error("UNKNOWN_AUDIT_PUBLIC_PROOF_FAILURE");await writeFile(resolve("../internal",`verification-adjudication-worker-failure-${namespace}.json`),JSON.stringify({schemaVersion:"verification-adjudication-worker-failure.v1",namespace,startupJournal,failedAt:new Date().toISOString(),errorName:failure.name,errorCode:typeof(failure)==="object"&&"code" in failure?String((failure as any).code):"UNCLASSIFIED",errorMessage:failure.message,createdOperationIds},null,2)+"\n",{flag:"wx"});throw error;}finally{if(server)await server.close();await database.close();}

