import assert from "node:assert/strict";
import { createHash,randomUUID } from "node:crypto";
import { readFile,readdir,writeFile } from "node:fs/promises";
import { basename,resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { VerificationAdjudicationTerminalResourceSchema,VerificationClaimsOperationResultSchema,VerificationReportOperationResultSchema,type Actor,type RequestAdjudicationRequest,type OperationContext,type VerificationArtifactHandle } from "@aiengineer/knowledge-contracts";
import { VerificationAdmissionService,VerificationAuditInspectionGrantCatalog,VerificationClaimsProjectionGrantCatalog } from "@aiengineer/knowledge-application";
import { VERIFICATION_PARSER_LIMITS } from "@aiengineer/knowledge-conversion";
import { PostgresCanonicalRepository,PostgresVerificationAdjudicationRepository,PostgresKnowledgeOperationService,PostgresVerificationRepository } from "@aiengineer/knowledge-persistence";
import { deterministicUuid,SupabaseArtifactStore } from "@aiengineer/knowledge-runtime";
import { canonicalizeJson,digestCanonicalJson } from "@aiengineer/knowledge-verification";
import { buildServer } from "../apps/api/src/server.js";
import { createVerificationAdjudicationReads } from "../apps/api/src/verification-adjudication-reads-runtime.js";
import { createVerificationOwnershipResolver } from "../apps/api/src/verification-ownership.js";
import { CanonicalActivityRegistry,createCanonicalActivityExecutor } from "../apps/worker/src/activity-registry.js";
import { CanonicalDurableKnowledgeWorker } from "../apps/worker/src/canonical-worker.js";
import { createVerificationAdjudicationRequestHandler } from "../apps/worker/src/verification-adjudication-runtime.js";

type SourceProof={namespace:string;tenantId:string;publicKeyPem:string;projection:{captureId:string;projectionArtifact:VerificationArtifactHandle};results:{claimsRecovery:{operationId:string;runId:string;manifestArtifact:VerificationArtifactHandle};reportRecovery:{operationId:string;runId:string;manifestArtifact:VerificationArtifactHandle}}};
type FrozenRegistry={records:readonly{captureId:string;projections:readonly[{sourceArtifact:VerificationArtifactHandle;projectionArtifact:VerificationArtifactHandle;transformationArtifact:VerificationArtifactHandle;parserVersion:string;imageDigest:`sha256:${string}`}]}[]};
type McReceipt={proof:string;workflowId:string;operationId:string;receiptId:string;requestDigest:string;disposition:string;historyPath:string;historySha256:string;historyEventCount:number;checks:{replayPassed:boolean};passed:boolean};
type Plan={kind:"claims"|"report";missionId:string;workItemId:string;attemptId:string;workflowId:string;expectedOperationId:string;idempotencyKey:string;context:OperationContext;request:RequestAdjudicationRequest};

const sourceProofPath=resolve(process.argv[2]??"../internal/verification-claims-report-worker-22c6b3e4-b5d6-4d34-923b-4846e37fdfaa.json");
const temporalAddress=process.argv[3]?.trim()||"127.0.0.1:7233";
const outputPath=resolve(process.argv[4]??`../internal/verification-adjudication-mission-control-${randomUUID()}.json`);
const sourceProof=JSON.parse(await readFile(sourceProofPath,"utf8")) as SourceProof;
const frozenRegistry=JSON.parse(await readFile(resolve("../internal/verification-frozen-source-registry-7a74a7a8-0dc4-4591-8bb1-5781ebddef42.json"),"utf8")) as FrozenRegistry;
const priorFacade=JSON.parse(await readFile(resolve(`../internal/verification-claims-report-audit-inspection-${sourceProof.namespace}.json`),"utf8")) as {inspections:readonly{kind:"claims"|"report";result:unknown}[]};
// @ts-expect-error reviewed local-only helper intentionally lives outside the package graph.
const {loadVerifiedLocalDevelopmentConfig}=await import("../../internal/verification-local-direct-config.mjs") as {loadVerifiedLocalDevelopmentConfig():Promise<{DB_URL:string;API_URL:string;SECRET_KEY:string}>};
const local=await loadVerifiedLocalDevelopmentConfig();
for(const [value,port] of [[local.DB_URL,"54322"],[local.API_URL,"54321"]] as const){const url=new URL(value);assert.ok(["localhost","127.0.0.1"].includes(url.hostname),"LOCAL_NATIVE_ONLY");assert.equal(url.port,port);}
assert.ok(/^(127\.0\.0\.1|localhost):\d{1,5}$/u.test(temporalAddress),"LOCAL_TEMPORAL_ONLY");

const namespace=randomUUID(),tenantId=sourceProof.tenantId,bucket="ai-engineer-cloud-bucket",deploymentId=`mission-control-audit-${namespace}`;
const actor:Actor={kind:"service",id:randomUUID(),serviceIdentity:"mission_control_client"};
const plans:Plan[]=["claims","report"].map(kindValue=>{
  const kind=kindValue as "claims"|"report",missionId=randomUUID(),workItemId=randomUUID(),attemptId=randomUUID(),workflowId=`audit-${kind}-${randomUUID()}`;
  const idempotencyKey=["vd1","requestAdjudication",tenantId,missionId,workItemId,attemptId].join(":");
  const expectedOperationId=deterministicUuid("verification-http-operation",`${tenantId}:requestAdjudication:${idempotencyKey}`);
  const source=kind==="claims"?sourceProof.results.claimsRecovery:sourceProof.results.reportRecovery;
  const request={verificationContractVersion:"verification.v1" as const,target:{kind:"run" as const,runId:source.runId},reason:"policy_review" as const,evidencePacket:{artifactId:source.manifestArtifact.artifactId,digest:source.manifestArtifact.digest as `sha256:${string}`}};
  const context:OperationContext={tenantId,operationId:expectedOperationId,attemptId,missionId,workItemId,correlationId:`mission-control-audit-${kind}-${namespace}`,actor,capabilityVersion:"verification-adjudication.v1",idempotencyKey,reason:"Native Mission Control Temporal audit proof",contractVersion:"v1",externalExecution:{runtime:"mission_control",runId:workflowId}};
  return{kind,missionId,workItemId,attemptId,workflowId,expectedOperationId,idempotencyKey,context,request};
});
const internalDir=resolve("../internal"),startupPath=resolve(internalDir,`verification-adjudication-mission-control-startup-${namespace}.json`),failurePath=resolve(internalDir,`verification-adjudication-mission-control-failure-${namespace}.json`);
await writeFile(startupPath,JSON.stringify({schemaVersion:"verification-adjudication-mission-control-startup.v1",namespace,tenantId,temporalNamespace:"verification-local",temporalAddress,sourceProof:{path:sourceProofPath,sha256:createHash("sha256").update(await readFile(sourceProofPath)).digest("hex")},plannedOperations:plans.map(plan=>({kind:plan.kind,sourceManifest:plan.request.evidencePacket,missionId:plan.missionId,workItemId:plan.workItemId,attemptId:plan.attemptId,workflowId:plan.workflowId,expectedOperationId:plan.expectedOperationId,requestDigest:digestCanonicalJson(plan.request),externalExecution:plan.context.externalExecution})),intendedMutationScope:"isolated local missions, work items, attempts, verification audit operations, receipts, and registered inspection results",createdAt:new Date().toISOString()},null,2)+"\n",{flag:"wx"});

const database=new PostgresCanonicalRepository({connectionString:local.DB_URL,localOnly:true});let server:ReturnType<typeof buildServer>|undefined,stopWorker=false,workerFailure:unknown,workerPump:Promise<void>|undefined,phase="fixture";const createdOperationIds:string[]=[];
try{
  phase="canonical_fixture";
  await database.transaction(tenantId,async client=>{for(const plan of plans){await client.query("insert into orchestration.mission(id,tenant_id,slug,goal) values($1,$2,$3,$4)",[plan.missionId,tenantId,`mc-audit-${plan.kind}-${namespace}`,"Native Mission Control Temporal audit inspection proof"]);await client.query("insert into orchestration.work_item(id,tenant_id,mission_id,kind,spec) values($1,$2,$3,'verify_extraction',$4::jsonb)",[plan.workItemId,tenantId,plan.missionId,JSON.stringify({namespace,role:"mission_control_audit",sourceKind:plan.kind})]);await client.query("insert into orchestration.attempt(id,tenant_id,work_item_id,attempt_no,agent_deployment_id,started_at) values($1,$2,$3,1,$4,$5)",[plan.attemptId,tenantId,plan.workItemId,deploymentId,new Date().toISOString()]);}});
  const nativeProjection=frozenRegistry.records.find(item=>item.captureId===sourceProof.projection.captureId)?.projections[0];assert.ok(nativeProjection);assert.equal(digestCanonicalJson(nativeProjection.projectionArtifact),digestCanonicalJson(sourceProof.projection.projectionArtifact));
  const store=new SupabaseArtifactStore({projectUrl:local.API_URL,serviceRoleKey:local.SECRET_KEY,bucket,maximumBytes:32_000_000});
  const repository=new PostgresVerificationRepository(database,store,{async authorize(input){assert.equal(input.tenantId,tenantId);assert.ok(["verification_admission","verification_replay","policy_replay"].includes(input.purpose));}});
  const admission=new VerificationAdmissionService(repository,{async parse():Promise<never>{throw new Error("PARSER_FORBIDDEN_IN_MISSION_CONTROL_AUDIT_PROOF");}},{parserVersion:nativeProjection.parserVersion as "verification-native-parser.v1",imageDigest:nativeProjection.imageDigest,limits:VERIFICATION_PARSER_LIMITS},{storageBucket:bucket,producerVersion:"verification-admission.v1",encryptionClass:"supabase-managed",retentionClass:"verification-audit",now:()=>new Date().toISOString()});
  async function sourceTerminal(kind:"claims"|"report"){const operationId=kind==="claims"?sourceProof.results.claimsRecovery.operationId:sourceProof.results.reportRecovery.operationId,receipts=await database.listReceipts(tenantId,operationId);assert.equal(receipts.length,1);const {eventId:_eventId,fencingToken:_fencingToken,...body}=receipts[0]!.body as Record<string,unknown>;return kind==="claims"?VerificationClaimsOperationResultSchema.parse(body):VerificationReportOperationResultSchema.parse(body);}
  const terminals={claims:await sourceTerminal("claims"),report:await sourceTerminal("report")};
  const projectionGrants=new VerificationClaimsProjectionGrantCatalog(plans.map(plan=>({tenantId,assertions:{artifactId:terminals[plan.kind].output.verified.assertionsArtifact.artifactId,digest:terminals[plan.kind].output.verified.assertionsArtifact.digest},admissions:[{captureId:sourceProof.projection.captureId,projectionArtifactId:nativeProjection.projectionArtifact.artifactId,transformationArtifactId:nativeProjection.transformationArtifact.artifactId}]})));
  const auditGrants=new VerificationAuditInspectionGrantCatalog(plans.map(plan=>({tenantId,auditArtifact:plan.request.evidencePacket,runKind:plan.kind})));
  const handler=createVerificationAdjudicationRequestHandler({subjects:new PostgresVerificationAdjudicationRepository(database,repository),reviewRequirements:{eligibleReviewerRoles:["expert"],quorumRequired:2},database,repository,admission,projectionGrants,auditGrants,trustedPublicKeys:{[`claims-report-proof-${sourceProof.namespace}`]:sourceProof.publicKeyPem},storageBucket:bucket,maximumInspectionMs:30_000,now:()=>new Date().toISOString()});
  const registry=new CanonicalActivityRegistry([handler]),executor=createCanonicalActivityExecutor(database,registry),nativeWorker=new CanonicalDurableKnowledgeWorker(`mission-control-audit-${namespace}`,tenantId,database,executor,30_000,registry.operationKinds()),operationService=new PostgresKnowledgeOperationService(database,{admittedOperationKinds:["verification_adjudication"]});
  const ownershipGrants=JSON.stringify(plans.map(plan=>({tenantId,actor,missionId:plan.missionId,agentDeploymentId:deploymentId,capabilityVersion:plan.context.capabilityVersion,externalExecution:plan.context.externalExecution})));
  const reads=createVerificationAdjudicationReads(database,{VERIFICATION_ADJUDICATION_PUBLIC_KEYS_JSON:JSON.stringify([{keyId:`claims-report-proof-${sourceProof.namespace}`,publicKeyPem:sourceProof.publicKeyPem}]),VERIFICATION_ADJUDICATION_GRANTS_JSON:JSON.stringify(plans.map(plan=>({tenantId,auditArtifact:plan.request.evidencePacket,runKind:plan.kind}))),VERIFICATION_CLAIMS_PROJECTION_GRANTS_JSON:JSON.stringify(plans.map(plan=>({tenantId,assertions:{artifactId:terminals[plan.kind].output.verified.assertionsArtifact.artifactId,digest:terminals[plan.kind].output.verified.assertionsArtifact.digest},admissions:[{captureId:sourceProof.projection.captureId,projectionArtifactId:nativeProjection.projectionArtifact.artifactId,transformationArtifactId:nativeProjection.transformationArtifact.artifactId}]}))),VERIFICATION_PARSER_IMAGE_DIGEST:nativeProjection.imageDigest,VERIFICATION_SERVICE_OWNERSHIP_GRANTS_JSON:ownershipGrants,SUPABASE_URL:local.API_URL,SUPABASE_SECRET_KEY:local.SECRET_KEY,VERIFICATION_STORAGE_BUCKET:bucket});assert.ok(reads);
  const admitted=async(candidateTenant:string,request:RequestAdjudicationRequest)=>{let grant;try{grant=auditGrants.resolve(candidateTenant,{verificationContractVersion:request.verificationContractVersion,auditBundle:request.evidencePacket});}catch{return false;}const expectedKind=grant.runKind==="claims"?"verification_claims":"verification_report";const rows=await database.transaction(candidateTenant,async client=>(await client.query<{operation_kind:string;status:string}>("select o.operation_kind,o.status from evidence.verification_run r join knowledge_service.operation o on o.tenant_id=r.tenant_id and o.id=r.operation_id where r.tenant_id=$1 and r.run_manifest_artifact_id=$2 and r.manifest_sha256=$3",[candidateTenant,request.evidencePacket.artifactId,request.evidencePacket.digest.slice(7)])).rows);return rows.length===1&&rows[0]!.operation_kind===expectedKind&&rows[0]!.status==="succeeded";};
  const token=`mission-control-audit-token-${namespace}`;
  server=buildServer({publicOrigin:"http://127.0.0.1",verificationOperationService:operationService,verificationAdjudicationReadService:reads,isAdjudicationRequestAdmitted:admitted,resourceReader:database,resolveIdentity:candidate=>candidate===token?{actor,grants:[{tenantId,roles:["knowledge_operator"],scopes:[]}]}:undefined,resolveVerificationContext:createVerificationOwnershipResolver(database,ownershipGrants)});
  await server.listen({host:"127.0.0.1",port:0});const address=server.server.address();assert.ok(address&&typeof address!=="string");const baseUrl=`http://127.0.0.1:${address.port}`;
  workerPump=(async()=>{while(!stopWorker){for(const plan of plans){const current=await database.getOperationRecord(tenantId,plan.expectedOperationId);if(current&&!createdOperationIds.includes(plan.expectedOperationId))createdOperationIds.push(plan.expectedOperationId);if(current&&!['succeeded','failed','cancelled'].includes(current.status)){try{await nativeWorker.runOperationOnce(plan.expectedOperationId);}catch(error){workerFailure=error;stopWorker=true;return;}}}await new Promise(resolveWait=>setTimeout(resolveWait,50));}})();
  const helperPath=resolve("../ai-engineer-mission-control/scripts/prove-verification-adjudication-temporal.ts");
  const {proveVerificationAdjudicationTemporal}=await import(pathToFileURL(helperPath).href) as {proveVerificationAdjudicationTemporal(input:{baseUrl:string;token:string;context:OperationContext;request:RequestAdjudicationRequest;missionExecutionId:string;temporalAddress?:string}):Promise<{realTemporalAdjudicationWorkflowCompleted:true;realTemporalAdjudicationHistoryReplayPassed:true}>};
  const operationResults=[];
  for(const plan of plans){
    phase=`temporal_${plan.kind}`;const existing=new Set(await readdir(internalDir));
    const helperResult=await proveVerificationAdjudicationTemporal({baseUrl,token,context:plan.context,request:plan.request,missionExecutionId:plan.workflowId,temporalAddress});
    assert.deepEqual(helperResult,{realTemporalAdjudicationWorkflowCompleted:true,realTemporalAdjudicationHistoryReplayPassed:true});assert.equal(workerFailure,undefined);
    const files=(await readdir(internalDir)).filter(name=>!existing.has(name)&&/^verification-adjudication-temporal-[0-9a-f-]+\.json$/u.test(name));assert.equal(files.length,1);
    const mcReceiptPath=resolve(internalDir,files[0]!),mcReceipt=JSON.parse(await readFile(mcReceiptPath,"utf8")) as McReceipt;
    assert.equal(mcReceipt.proof,"verification-adjudication-temporal.v1");assert.equal(mcReceipt.workflowId,plan.workflowId);assert.equal(mcReceipt.operationId,plan.expectedOperationId);assert.equal(mcReceipt.requestDigest,digestCanonicalJson(plan.request));assert.equal(mcReceipt.disposition,"completed_without_admission");assert.equal(mcReceipt.checks.replayPassed,true);assert.equal(mcReceipt.passed,true);
    const operation=await database.getOperationRecord(tenantId,plan.expectedOperationId);assert.ok(operation);assert.equal(operation.status,"succeeded");assert.equal(operation.operationKind,"verification_adjudication");assert.equal(operation.ownershipMode,"mission_control");assert.equal(operation.externalRunId,plan.workflowId);const durableRequest=operation.request as {authenticatedContext?:{externalExecution?:unknown}};assert.equal(canonicalizeJson(durableRequest.authenticatedContext?.externalExecution),canonicalizeJson(plan.context.externalExecution));
    const receipts=await database.listReceipts(tenantId,plan.expectedOperationId);assert.equal(receipts.length,1);assert.equal(receipts[0]!.id,mcReceipt.receiptId);
    const publicResult=VerificationAdjudicationTerminalResourceSchema.parse(await reads.getPendingSubject({tenantId,operationId:plan.expectedOperationId,actor}));
    const expected=priorFacade.inspections.find(item=>item.kind===plan.kind)?.result;assert.ok(expected);assert.equal(publicResult.output.originalPolicyOutcome,(expected as {run:{policyOutcome:string}}).run.policyOutcome);assert.equal(publicResult.output.status,"pending_human_adjudication");assert.equal(publicResult.output.humanDecisionRecorded,false);assert.equal(publicResult.output.admissionChanged,false);assert.equal(JSON.stringify(publicResult).includes("objectKey"),false);
    if(!createdOperationIds.includes(plan.expectedOperationId))createdOperationIds.push(plan.expectedOperationId);
    operationResults.push({kind:plan.kind,sourceManifest:plan.request.evidencePacket,missionId:plan.missionId,workItemId:plan.workItemId,attemptId:plan.attemptId,workflowId:plan.workflowId,expectedOperationId:plan.expectedOperationId,operationId:mcReceipt.operationId,requestDigest:mcReceipt.requestDigest,receiptId:mcReceipt.receiptId,resultArtifact:publicResult.packetArtifact,policyOutcome:publicResult.output.originalPolicyOutcome,externalExecution:plan.context.externalExecution,mcProof:{receiptPath:mcReceiptPath,receiptSha256:createHash("sha256").update(await readFile(mcReceiptPath)).digest("hex"),historyPath:mcReceipt.historyPath,historySha256:mcReceipt.historySha256,historyEventCount:mcReceipt.historyEventCount,replayPassed:mcReceipt.checks.replayPassed}});
  }
  stopWorker=true;await workerPump;if(workerFailure)throw workerFailure;
  phase="receipt";
  const sourcePaths=["scripts/prove-verification-adjudication-mission-control.ts","apps/worker/src/verification-adjudication-runtime.ts","apps/worker/src/verification-adjudication-activity.ts","packages/persistence/src/verification-adjudication-runtime.ts","packages/persistence/src/verification-audit-runtime.ts","packages/persistence/src/verification-adjudication-reads.ts","apps/api/src/server.ts","apps/api/src/verification-adjudication-reads-runtime.ts","apps/api/src/verification-ownership.ts","../ai-engineer-mission-control/scripts/prove-verification-adjudication-temporal.ts","../ai-engineer-mission-control/apps/worker/src/verification-runtime.ts","../ai-engineer-mission-control/apps/worker/src/verification-activities.ts","../ai-engineer-mission-control/apps/worker/src/verification-workflow.ts","../ai-engineer-mission-control/packages/mission-kernel/src/verification-dispatch.ts"];
  const sourceFiles=await Promise.all(sourcePaths.map(async path=>({path,sha256:createHash("sha256").update(await readFile(resolve(path))).digest("hex")})));
  const receipt={schemaVersion:"verification-adjudication-mission-control-proof.v1",namespace,tenantId,temporalNamespace:"verification-local",temporalAddress,startupJournal:startupPath,sourceProof:{path:sourceProofPath,sha256:createHash("sha256").update(await readFile(sourceProofPath)).digest("hex")},operations:operationResults,checks:{real_temporal_claims_workflow_completed:true,real_temporal_report_workflow_completed:true,mission_control_activity_called_real_ks_http:true,exact_external_execution_ownership_bound:true,ks_native_worker_only_targeted_expected_operations:true,canonical_signed_claims_and_report_replay_preserved:true,compact_terminal_reads_match_mc_receipts:true,temporal_histories_replayed:true,temporal_histories_exclude_credentials_and_raw_receipts:true},parserDispatches:0,providerDispatches:0,sourceFiles,limitations:["Local development Temporal, PostgreSQL, and Storage only","No cancellation or OS-process crash in this bounded proof; accepted EV117 covers injected cancellation and fenced recovery","No remote deployment or provider/parser execution"]};
  await writeFile(outputPath,JSON.stringify(receipt,null,2)+"\n",{flag:"wx"});console.log(JSON.stringify({output:outputPath,sha256:createHash("sha256").update(await readFile(outputPath)).digest("hex"),checks:Object.keys(receipt.checks).length,operations:operationResults.length,parserDispatches:0,providerDispatches:0}));
}catch(error){stopWorker=true;const failure=error instanceof Error?error:new Error("UNKNOWN_MISSION_CONTROL_AUDIT_FAILURE"),explicit=error&&typeof error==="object"&&"code" in error?String((error as {code:unknown}).code):failure.message,code=/^[A-Z][A-Z0-9_]{2,127}$/u.test(explicit)?explicit:"UNCLASSIFIED";await writeFile(failurePath,JSON.stringify({schemaVersion:"verification-adjudication-mission-control-failure.v1",namespace,tenantId,temporalNamespace:"verification-local",temporalAddress,startupJournal:startupPath,phase,failedAt:new Date().toISOString(),errorClass:failure.name,errorCode:code,plannedOperationIds:plans.map(plan=>plan.expectedOperationId),createdOperationIds},null,2)+"\n",{flag:"wx"});throw error;}finally{stopWorker=true;if(workerPump)await workerPump.catch(()=>undefined);if(server)await server.close();await database.close();}

