import type { OperationKind } from "@aiengineer/knowledge-contracts";

export const MCP_TOOL_CATALOG = Object.freeze({
  "source.discover": "source_discovery",
  "source.resolve_identity": "source_resolution",
  "source.fetch": "capture",
  "source.inspect_capture": "capture_inspection",
  "source.compare_captures": "capture_comparison",
  "source.propose_vetting": "source_vetting",
  "vector_store.create": "vector_store_create",
  "vector_store.add_documents": "vector_store_documents",
  "vector_store.ingestion_status": "vector_store_ingestion",
  "vector_store.search": "vector_store_search",
  "vector_store.evaluate": "vector_store_evaluation",
  "document.convert": "transformation",
  "document.inspect_representation": "representation_inspection",
  "document.compare_representations": "representation_comparison",
  "document.request_manual_review": "review",
  "knowledge.propose_domain_mapping": "promotion_proposal",
  "knowledge.propose_claims": "promotion_proposal",
  "knowledge.propose_entity_links": "promotion_proposal",
  "chunk.strategy_list": "chunk_preview",
  "chunk.preview": "chunk_preview",
  "chunk.compare": "chunk_comparison",
  "chunk.inspect": "chunk_set_inspection",
  "chunk.create_intent": "chunk_set",
  "embedding.model_list": "embedding_run",
  "embedding.estimate": "embedding_run",
  "embedding.create_intent": "embedding_run",
  "embedding.run_status": "embedding_run",
  "retrieval.plan_validate": "retrieval_run",
  "retrieval.search": "retrieval_run",
  "retrieval.explain_run": "retrieval_run",
  "retrieval.build_evidence_packet": "evidence_packet",
  "evaluation.generate_query_candidates": "evaluation_dataset",
  "evaluation.run_experiment": "evaluation_run",
  "evaluation.compare_experiments": "experiment",
  "evaluation.inspect_failures": "evaluation_run",
  "promotion.submit": "promotion_proposal",
  "promotion.status": "promotion_proposal",
} satisfies Record<string, OperationKind>);

export type McpToolName = keyof typeof MCP_TOOL_CATALOG;
export const VERIFICATION_MCP_TOOL_NAMES = Object.freeze([
  "knowledge_extract_structured_data",
  "knowledge_capture_source",
  "knowledge_parse_artifact",
  "knowledge_verify_extraction",
  "knowledge_verify_claims",
  "knowledge_verify_report",
  "knowledge_verify_metric",
  "knowledge_request_adjudication",
  "knowledge_record_adjudication_decision",
  "knowledge_inspect_audit_bundle",
  "knowledge_replay_run",
  "knowledge_run_benchmark",
  "knowledge_compare_benchmark_runs",
] as const);
export const FORBIDDEN_MCP_CAPABILITIES = Object.freeze([
  "raw_sql",
  "secret.read",
  "storage.list",
  "publication.approve",
  "publication.publish",
  "capability.admit",
]);
