import type { OperationKind } from "@aiengineer/knowledge-contracts";

export const MCP_TOOL_CATALOG = Object.freeze({
  knowledge_source_discover: "source_discovery",
  knowledge_source_resolve: "source_resolution",
  knowledge_source_fetch: "capture",
  knowledge_source_inspect_capture: "capture_inspection",
  knowledge_source_compare_captures: "capture_comparison",
  knowledge_source_vet: "source_vetting",
  knowledge_store_create: "vector_store_create",
  knowledge_store_add_documents: "vector_store_documents",
  knowledge_store_status: "vector_store_ingestion",
  knowledge_store_search: "vector_store_search",
  knowledge_store_evaluate: "vector_store_evaluation",
  knowledge_document_convert: "transformation",
  knowledge_document_inspect: "representation_inspection",
  knowledge_document_compare: "representation_comparison",
  knowledge_document_request_review: "review",
  knowledge_promotion_propose_domain_mapping: "promotion_proposal",
  knowledge_promotion_propose_claims: "promotion_proposal",
  knowledge_promotion_propose_entity_links: "promotion_proposal",
  knowledge_chunk_strategies: "chunk_preview",
  knowledge_chunk_preview: "chunk_preview",
  knowledge_chunk_compare: "chunk_comparison",
  knowledge_chunk_inspect: "chunk_set_inspection",
  knowledge_chunk_build: "chunk_set",
  knowledge_embed_models: "embedding_run",
  knowledge_embed_estimate: "embedding_run",
  knowledge_embed_run: "embedding_run",
  knowledge_embed_status: "embedding_run",
  knowledge_retrieve_plan: "retrieval_run",
  knowledge_retrieve_search: "retrieval_run",
  knowledge_retrieve_explain: "retrieval_run",
  knowledge_retrieve_run: "retrieval_run",
  knowledge_retrieve_packet: "evidence_packet",
  knowledge_retrieve_citations: "evidence_packet",
  knowledge_retrieve_build_packet: "evidence_packet",
  knowledge_eval_generate: "evaluation_dataset",
  knowledge_eval_run: "evaluation_run",
  knowledge_eval_compare: "experiment",
  knowledge_eval_failures: "evaluation_run",
  knowledge_promotion_propose: "promotion_proposal",
  knowledge_promotion_status: "promotion_proposal",
} satisfies Record<string, OperationKind>);

export type McpToolName = keyof typeof MCP_TOOL_CATALOG;
export const VERIFICATION_MCP_TOOL_NAMES = Object.freeze([
  "verify_extraction_run",
  "verify_benchmark_capture",
  "verify_artifact_parse",
  "verify_extract",
  "verify_citations",
  "verify_report",
  "verify_metric",
  "verify_adjudication_request",
  "verify_adjudication_decision",
  "verify_bundle_inspect",
  "verify_bundle_replay",
  "verify_benchmark_run",
  "verify_benchmark_compare",
] as const);
export const FORBIDDEN_MCP_CAPABILITIES = Object.freeze([
  "raw_sql",
  "secret.read",
  "storage.list",
  "publication.approve",
  "publication.publish",
  "capability.admit",
]);
