import { describe,expect,it,vi } from "vitest";
import { createClaimsReportReadMcpExecutor,createVerificationMcpToolExecutor } from "./index.js";

describe("metric MCP adapter",()=>{
  it("submits comparison references through the API and rejects caller inference",async()=>{
    const compareBenchmarkRuns=vi.fn(async()=>({operationId:id(80),state:"queued"})),execute=createVerificationMcpToolExecutor({operationService:{} as never,apiOrigin:"https://knowledge.example",identity:{actor,grants:[{tenantId:tenant,roles:["knowledge_operator"],scopes:[]}]},apiClient:{compareBenchmarkRuns} as never});
    const request={verificationContractVersion:"verification.v1",baselineRunId:id(81),candidateRunId:id(82),comparisonProfile:"paired_default"};
    await expect(execute("knowledge_compare_benchmark_runs",{context,request})).resolves.toMatchObject({structuredContent:{operationId:id(80)}});expect(compareBenchmarkRuns).toHaveBeenCalledWith(request,context);await expect(execute("knowledge_compare_benchmark_runs",{context,request:{...request,statistics:{}}})).rejects.toThrow();expect(compareBenchmarkRuns).toHaveBeenCalledTimes(1);
  });
  it("routes offline benchmarks and rejects caller checkpoint plans",async()=>{
    const runBenchmark=vi.fn(async()=>({operationId:id(8),state:"queued"}));
    const execute=createVerificationMcpToolExecutor({operationService:{} as never,apiOrigin:"https://knowledge.example",identity:{actor,grants:[{tenantId:tenant,roles:["knowledge_operator"],scopes:[]}]},apiClient:{runBenchmark} as never});
    const request={verificationContractVersion:"verification.v1",dataset:{artifactId:id(12),digest:`sha256:${"3".repeat(64)}`},experimentDefinition:{artifactId:id(13),digest:`sha256:${"4".repeat(64)}`},executionMode:"offline_recorded"};
    await expect(execute("knowledge_run_benchmark",{context,request})).resolves.toMatchObject({structuredContent:{operationId:id(8)}});
    expect(runBenchmark).toHaveBeenCalledWith(request,context);
    await expect(execute("knowledge_run_benchmark",{context,request:{...request,checkpointPlan:[]}})).rejects.toThrow();
    expect(runBenchmark).toHaveBeenCalledTimes(1);
  });
  it("forwards metric routing hints through the API and rejects synthesized findings",async()=>{
    const verifyMetricObservation=vi.fn(async()=>({operationId:id(8),state:"queued"}));
    const execute=createVerificationMcpToolExecutor({operationService:{} as never,apiOrigin:"https://knowledge.example",identity:{actor,grants:[{tenantId:tenant,roles:["knowledge_operator"],scopes:[]}]},apiClient:{verifyMetricObservation} as never});
    const metricContext={...context,missionId:id(9),workItemId:id(10),attemptId:id(11)};
    const metricRequest={verificationContractVersion:"verification.v1",captureIds:["capture-1"],observations:{artifactId:id(12),digest:`sha256:${"3".repeat(64)}`}};
    await expect(execute("knowledge_verify_metric",{context:metricContext,request:metricRequest})).resolves.toMatchObject({structuredContent:{operationId:id(8)}});
    expect(verifyMetricObservation).toHaveBeenCalledWith(metricRequest,metricContext);
    await expect(execute("knowledge_verify_metric",{context:metricContext,request:{...metricRequest,findings:[]}})).rejects.toThrow();
  });
});

const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`,tenant=id(1),actor={kind:"service" as const,id:id(2),serviceIdentity:"mission_control_client" as const};
const context={tenantId:tenant,correlationId:"mcp-verification",idempotencyKey:"mcp-verification-001"},request={verificationContractVersion:"verification.v1" as const,captureIds:["capture-1"],extractionSchema:{artifactId:id(3),digest:`sha256:${"1".repeat(64)}` as const},extractionOutput:{artifactId:id(4),digest:`sha256:${"2".repeat(64)}` as const}};
describe("verification MCP adapter",()=>{it("uses bearer-bound identity and the strict API client without accepting actor context",async()=>{const verifyExtraction=vi.fn(async()=>({operationId:id(5),state:"queued"})),execute=createVerificationMcpToolExecutor({operationService:{} as never,apiOrigin:"https://knowledge.example",identity:{actor,grants:[{tenantId:tenant,roles:["knowledge_operator"],scopes:[]}]},apiClient:{verifyExtraction} as never});await expect(execute("knowledge_verify_extraction",{context,request})).resolves.toMatchObject({structuredContent:{operationId:id(5)}});expect(verifyExtraction).toHaveBeenCalledWith(request,context);await expect(execute("knowledge_verify_extraction",{context:{...context,actor},request})).rejects.toThrow();});it("denies a tenant outside the authenticated grant before calling the client",async()=>{const verifyExtraction=vi.fn(),execute=createVerificationMcpToolExecutor({operationService:{} as never,apiOrigin:"https://knowledge.example",identity:{actor,grants:[{tenantId:id(99),roles:["knowledge_operator"],scopes:[]}]},apiClient:{verifyExtraction} as never});await expect(execute("knowledge_verify_extraction",{context,request})).resolves.toMatchObject({isError:true});expect(verifyExtraction).not.toHaveBeenCalled();});});

describe("parse MCP adapter",()=>{it("forwards only a strict artifact handle to the API client",async()=>{const parseArtifact=vi.fn(async()=>({operationId:id(70),state:"queued"})),execute=createVerificationMcpToolExecutor({operationService:{} as never,apiOrigin:"https://knowledge.example",identity:{actor,grants:[{tenantId:tenant,roles:["knowledge_operator"],scopes:[]}]},apiClient:{parseArtifact} as never}),parse={verificationContractVersion:"verification.v1",captureId:id(71),sourceArtifact:{artifactId:id(72),tenantId:tenant,digest:`sha256:${"7".repeat(64)}`,mediaType:"text/html",byteLength:4,objectKey:"tenant/object",createdAt:"2026-09-07T00:00:00.000Z",producerActivityId:"capture",producerVersion:"v1",encryptionClass:"managed",retentionClass:"audit",dataClassification:"restricted",parentArtifactIds:[]}};await execute("knowledge_parse_artifact",{context,request:parse});expect(parseArtifact).toHaveBeenCalledWith(parse,context);await expect(execute("knowledge_parse_artifact",{context,request:{...parse,parserKind:"html"}})).rejects.toThrow();});});

describe("claims MCP adapter",()=>{it("routes strict claims and reports without caller verifier authority",async()=>{const verifyClaims=vi.fn(async()=>({operationId:id(20),state:"queued"})),verifyReport=vi.fn(async()=>({operationId:id(21),state:"queued"})),execute=createVerificationMcpToolExecutor({operationService:{} as never,apiOrigin:"https://knowledge.example",identity:{actor,grants:[{tenantId:tenant,roles:["knowledge_operator"],scopes:[]}]},apiClient:{verifyClaims,verifyReport} as never});const ref={artifactId:id(30),digest:`sha256:${"a".repeat(64)}`},claims={verificationContractVersion:"verification.v1",captureIds:["capture-1"],assertions:ref},report={verificationContractVersion:"verification.v1",captureIds:["capture-1"],report:ref,claimLedger:{artifactId:id(31),digest:`sha256:${"b".repeat(64)}`}};await execute("knowledge_verify_claims",{context,request:claims});await execute("knowledge_verify_report",{context,request:report});expect(verifyClaims).toHaveBeenCalledWith(claims,context);expect(verifyReport).toHaveBeenCalledWith(report,context);await expect(execute("knowledge_verify_claims",{context,request:{...claims,verifierDeploymentId:id(90)}})).rejects.toThrow();});});

describe("audit inspection MCP adapter",()=>{it("routes only the strict audit reference through the authenticated client",async()=>{const inspectAuditBundle=vi.fn(async()=>({operationId:id(40),state:"queued"})),execute=createVerificationMcpToolExecutor({operationService:{} as never,apiOrigin:"https://knowledge.example",identity:{actor,grants:[{tenantId:tenant,roles:["knowledge_operator"],scopes:[]}]},apiClient:{inspectAuditBundle} as never}),auditRequest={verificationContractVersion:"verification.v1",auditBundle:{artifactId:id(41),digest:`sha256:${"c".repeat(64)}`}};await execute("knowledge_inspect_audit_bundle",{context,request:auditRequest});expect(inspectAuditBundle).toHaveBeenCalledWith(auditRequest,context);await expect(execute("knowledge_inspect_audit_bundle",{context,request:{...auditRequest,publicKey:"caller"}})).rejects.toThrow();});});

describe("claims/report read MCP adapter",()=>{it("uses bearer-bound read authority and strict operation input",async()=>{const getVerificationClaimsResult=vi.fn(async()=>({useCase:"verifyClaims"})),getVerificationReportResult=vi.fn(async()=>({useCase:"verifyReport"})),options={operationService:{} as never,apiOrigin:"https://knowledge.example",identity:{actor,grants:[{tenantId:tenant,roles:["knowledge_operator" as const],scopes:[]}]},apiClient:{getVerificationClaimsResult,getVerificationReportResult} as never};const readContext={tenantId:tenant,correlationId:"mcp-read"};await createClaimsReportReadMcpExecutor(options,"claims")({context:readContext,operationId:id(50)});await createClaimsReportReadMcpExecutor(options,"report")({context:readContext,operationId:id(51)});expect(getVerificationClaimsResult).toHaveBeenCalledWith(id(50),readContext);expect(getVerificationReportResult).toHaveBeenCalledWith(id(51),readContext);await expect(createClaimsReportReadMcpExecutor(options,"claims")({context:readContext,operationId:id(50),rawBundle:true})).rejects.toThrow();});it("denies an ungranted tenant before the client call",async()=>{const getVerificationClaimsResult=vi.fn(),execute=createClaimsReportReadMcpExecutor({operationService:{} as never,apiOrigin:"https://knowledge.example",identity:{actor,grants:[{tenantId:id(99),roles:["knowledge_operator"],scopes:[]}]},apiClient:{getVerificationClaimsResult} as never},"claims");await expect(execute({context:{tenantId:tenant,correlationId:"denied"},operationId:id(50)})).resolves.toMatchObject({isError:true});expect(getVerificationClaimsResult).not.toHaveBeenCalled();});});
