import { sha256Digest } from "@aiengineer/knowledge-domain";
import type { ArtifactStore } from "@aiengineer/knowledge-runtime";
import { deterministicUuid } from "@aiengineer/knowledge-runtime";
import type { ConversionMetrics, ConversionNode, ConversionNodeKind, ConversionOutput, ConversionRequest, DocumentConversionProvider, FidelityReport } from "./types.js";

const decoder = new TextDecoder("utf-8", { fatal: false }); const encoder = new TextEncoder();
function decodeEntities(value: string): string { return value.replace(/&nbsp;/gi, " ").replace(/&amp;/gi, "&").replace(/&lt;/gi, "<").replace(/&gt;/gi, ">").replace(/&quot;/gi, '"').replace(/&#39;/gi, "'"); }
function normalize(value: string): string { return value.replace(/\r\n?/g, "\n").replace(/[ \t]+\n/g, "\n").replace(/\n{3,}/g, "\n\n").trim(); }
function timestamp(value: string): number { const parts = value.split(":").map(Number); if (parts.some(Number.isNaN)) return 0; return Math.round((parts.length === 3 ? parts[0]! * 3600 + parts[1]! * 60 + parts[2]! : parts[0]! * 60 + parts[1]!) * 1000); }
function addNode(nodes: ConversionNode[], representationKey: string, kind: ConversionNodeKind, text: string, locator: ConversionNode["locator"], parentId?: string, label?: string) { const ordinal = nodes.length; const contentDigest = sha256Digest(text); const id = deterministicUuid("document-node", `${representationKey}:${ordinal}:${kind}:${contentDigest}`); const node: ConversionNode = { id, ordinal, kind, text, contentDigest, locator }; if (parentId) node.parentId = parentId; if (label) node.label = label; nodes.push(node); return node; }

export function convertTextToNodes(input: string, mediaType: string, representationKey: string): { nodes: ConversionNode[]; markdown: string; plainText: string } {
  let source = normalize(input); const nodes: ConversionNode[] = []; const root = addNode(nodes, representationKey, "document", source, { startOffset: 0, endOffset: source.length });
  if (mediaType.includes("html")) source = normalize(decodeEntities(source.replace(/<script[\s\S]*?<\/script>/gi, "").replace(/<style[\s\S]*?<\/style>/gi, "").replace(/<h([1-6])[^>]*>([\s\S]*?)<\/h\1>/gi, (_, level: string, text: string) => `\n${"#".repeat(Number(level))} ${text.replace(/<[^>]+>/g, " ")}\n`).replace(/<pre[^>]*>([\s\S]*?)<\/pre>/gi, (_, code: string) => `\n\`\`\`\n${decodeEntities(code.replace(/<[^>]+>/g, ""))}\n\`\`\`\n`).replace(/<li[^>]*>/gi, "\n- ").replace(/<br\s*\/?>/gi, "\n").replace(/<\/p>/gi, "\n\n").replace(/<[^>]+>/g, " ")));
  const transcript = mediaType.includes("vtt") || /^(?:\[)?\d{1,2}:\d{2}(?::\d{2})?(?:\.\d{1,3})?(?:\])?\s/m.test(source);
  const blocks = source.split(/\n{2,}/); let cursor = 0; let code = false; const headings: string[] = [];
  for (const raw of blocks) { const text = raw.trim(); if (!text || text === "WEBVTT") continue; const startOffset = source.indexOf(text, cursor); cursor = startOffset + text.length; let kind: ConversionNodeKind = "paragraph"; let label: string | undefined; const heading = text.match(/^(#{1,6})\s+(.+)$/s); const timed = text.match(/^(?:\[)?(\d{1,2}:\d{2}(?::\d{2})?(?:\.\d{1,3})?)(?:\])?(?:\s*-->\s*(\d{1,2}:\d{2}(?::\d{2})?(?:\.\d{1,3})?))?\s*\n?([\s\S]*)$/); if (heading) { kind = "heading"; label = heading[2]!.trim(); headings.length = heading[1]!.length - 1; headings.push(label); } else if (transcript && timed) { kind = "transcript_segment"; label = timed[3]?.match(/^([^:\n]{1,80}):\s/)?.[1]; } else if (text.startsWith("```") && text.endsWith("```")) { kind = "code_block"; code = !code; } else if (/^(?:[-*+] |\d+\. )/m.test(text)) kind = "list"; else if (/^\|.+\|\n\|[- :|]+\|/m.test(text)) kind = "table"; else if (/^>\s/m.test(text)) kind = "quotation";
    const locator: ConversionNode["locator"] = { startOffset, endOffset: startOffset + text.length, sectionPath: headings.filter((item): item is string => typeof item === "string") }; if (kind === "transcript_segment" && timed) { locator.startTimeMs = timestamp(timed[1]!); if (timed[2]) locator.endTimeMs = timestamp(timed[2]); if (label) locator.speaker = label; }
    addNode(nodes, representationKey, kind, text, locator, root.id, label);
  }
  void code; return { nodes, markdown: source, plainText: source.replace(/^#{1,6}\s+/gm, "").replace(/^```.*$/gm, "").replace(/^[-*+]\s+/gm, "") };
}
export function inspectConversion(input: string, output: string, nodes: readonly ConversionNode[]): { metrics: ConversionMetrics; fidelity: FidelityReport } { const nonRoot = nodes.slice(1); const counts = new Map<string, number>(); for (const node of nonRoot) counts.set(node.contentDigest, (counts.get(node.contentDigest) ?? 0) + 1); const repeated = nonRoot.filter((node) => (counts.get(node.contentDigest) ?? 0) > 1).length; const metrics: ConversionMetrics = { inputCharacters: input.length, outputCharacters: output.length, characterCoverage: input.length === 0 ? 1 : Math.min(1, output.length / input.length), headings: nonRoot.filter((n) => n.kind === "heading").length, tables: nonRoot.filter((n) => n.kind === "table").length, figures: nonRoot.filter((n) => n.kind === "figure" || n.kind === "image").length, codeBlocks: nonRoot.filter((n) => n.kind === "code_block").length, citations: nonRoot.filter((n) => n.kind === "citation").length, emptyNodes: nonRoot.filter((n) => !n.text.trim()).length, repeatedBlockRatio: nonRoot.length ? repeated / nonRoot.length : 0, locatorResolvability: nonRoot.length ? nonRoot.filter((n) => n.locator.startOffset !== undefined && n.locator.endOffset !== undefined).length / nonRoot.length : 1, encodingAnomalies: (output.match(/�/g) ?? []).length }; const findings: FidelityReport["findings"][number][] = []; if (metrics.characterCoverage < 0.5) findings.push({ disposition: "alternate_conversion", nodeIds: [], impact: "low text coverage", allowedAction: "route to admitted fallback" }); if (metrics.encodingAnomalies) findings.push({ disposition: "repair", nodeIds: [], impact: "encoding replacement characters", allowedAction: "retry pinned decoder" }); if (metrics.repeatedBlockRatio > 0.3) findings.push({ disposition: "review", nodeIds: [], impact: "probable boilerplate", allowedAction: "inspect duplicate blocks" }); const fidelity: FidelityReport = { grade: findings.some((f) => f.disposition === "alternate_conversion") ? "low" : findings.length ? "medium" : "high", metrics, checks: ["content_digest", "stable_nodes", "span_bounds", "locator_resolvability", "encoding_scan", "duplicate_scan"], findings }; return { metrics, fidelity }; }

export class DeterministicTextConversionProvider implements DocumentConversionProvider { readonly providerKey = "deterministic-structural-text"; readonly version = "1.0.0"; constructor(private readonly artifacts: ArtifactStore) {} supports(profile: ConversionRequest["profile"]) { return /text|json|xml|html|markdown|vtt/.test(profile.mediaType); } async convert(request: ConversionRequest): Promise<ConversionOutput> { const bytes = await this.artifacts.get(request.tenantId, request.sourceArtifact.digest); if (!bytes) throw new Error("SOURCE_ARTIFACT_NOT_FOUND"); const input = decoder.decode(bytes); const profileDigest = sha256Digest({ ...request.profile }); const requestDigest = sha256Digest({ sourceDigest: request.sourceArtifact.digest, profileDigest }); const converted = convertTextToNodes(input, request.profile.mediaType, requestDigest); const native = await this.artifacts.put({ tenantId: request.tenantId, mediaType: "application/vnd.aiengineer.document+json", bytes: encoder.encode(JSON.stringify(converted.nodes)) }); const markdown = await this.artifacts.put({ tenantId: request.tenantId, mediaType: "text/markdown", bytes: encoder.encode(converted.markdown) }); const plain = await this.artifacts.put({ tenantId: request.tenantId, mediaType: "text/plain", bytes: encoder.encode(converted.plainText) }); const inspected = inspectConversion(input, converted.markdown, converted.nodes); return { providerKey: this.providerKey, providerVersion: this.version, profileDigest, requestDigest, providerNativeArtifact: native, markdownArtifact: markdown, plainTextArtifact: plain, nodes: converted.nodes, metrics: inspected.metrics, fidelity: inspected.fidelity, receiptDigest: sha256Digest({ provider: `${this.providerKey}@${this.version}`, requestDigest, outputs: [native.digest, markdown.digest, plain.digest] }), observations: { deterministic: 1 } }; } }
