import { EveRuntimeAttestationEnvelopeSchema, ExternalExecutionContextSchema, type EveRuntimeAttestationEnvelope, type ExternalExecutionContext } from "@aiengineer/knowledge-contracts";
import { digestCanonicalJson } from "@aiengineer/knowledge-verification";
import type { Database } from "@aiengineer/database-contract";
import type { PostgresCanonicalRepository } from "./postgres.js";
type EveBindingRow = Database["knowledge_service"]["Tables"]["eve_operation_binding"]["Row"];
type EveInvocationRow = Database["knowledge_service"]["Tables"]["eve_operation_invocation"]["Row"];
const hex=(value:unknown)=>digestCanonicalJson(value).slice(7);
export async function resolveEveVerificationBinding(database:PostgresCanonicalRepository,envelope:EveRuntimeAttestationEnvelope):Promise<ExternalExecutionContext>{
 const parsed=EveRuntimeAttestationEnvelopeSchema.parse(envelope),p=parsed.payload,envelopeSha=hex(parsed),lineageSha=hex({tenantId:p.tenantId,operationId:p.operationId,issuer:p.issuer,externalExecution:p.externalExecution});
 return database.transaction(p.tenantId,async client=>{
  await client.query("select pg_advisory_xact_lock(hashtextextended($1,0))",[`eve-verification:${p.tenantId}:${p.idempotencyKey}`]);
  const own=await client.query<{id:string}>(`select a.id from orchestration.attempt a join orchestration.work_item w on w.tenant_id=a.tenant_id and w.id=a.work_item_id join orchestration.mission m on m.tenant_id=w.tenant_id and m.id=w.mission_id left join orchestration.agent_session s on s.tenant_id=a.tenant_id and s.id=a.agent_session_id where a.tenant_id=$1 and a.id=$2 and w.id=$3 and m.id=$4 and a.agent_deployment_id=$5 and(a.agent_session_id is null or s.eve_session_id=$6)and(cardinality(a.eve_turn_ids)=0 or $7=any(a.eve_turn_ids))`,[p.tenantId,p.attemptId,p.workItemId,p.missionId,p.agentDeploymentId,p.externalExecution.sessionId,p.externalExecution.turnId]);if(own.rows.length!==1)throw Error("EVE_VERIFICATION_OWNERSHIP_MISMATCH");
  const found=await client.query<EveBindingRow>(`select * from knowledge_service.eve_operation_binding where tenant_id=$1 and idempotency_key=$2 for update`,[p.tenantId,p.idempotencyKey]);let original:ExternalExecutionContext;
  if(!found.rows.length){await client.query(`insert into knowledge_service.eve_operation_binding(tenant_id,operation_id,idempotency_key,grant_id,use_case,request_sha256,actor_identity,mission_id,work_item_id,attempt_id,agent_deployment_id,capability_version,original_external_execution,issuer,original_key_id,original_jti,original_payload_sha256)values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13::jsonb,$14,$15,$16,$17)`,[p.tenantId,p.operationId,p.idempotencyKey,p.grantId,p.useCase,p.requestDigest.slice(7),`${p.principal.kind}:${p.principal.id}:${p.principal.serviceIdentity}`,p.missionId,p.workItemId,p.attemptId,p.agentDeploymentId,p.capabilityVersion,JSON.stringify(p.externalExecution),p.issuer,p.keyId,p.jti,hex(p)]);original=ExternalExecutionContextSchema.parse(p.externalExecution)}else{const row=found.rows[0]!,ok=row.operation_id===p.operationId&&row.grant_id===p.grantId&&row.use_case===p.useCase&&row.request_sha256===p.requestDigest.slice(7)&&row.actor_identity===`${p.principal.kind}:${p.principal.id}:${p.principal.serviceIdentity}`&&row.mission_id===p.missionId&&row.work_item_id===p.workItemId&&row.attempt_id===p.attemptId&&row.agent_deployment_id===p.agentDeploymentId&&row.capability_version===p.capabilityVersion&&row.issuer===p.issuer;if(!ok)throw Error("EVE_VERIFICATION_BINDING_CONFLICT");original=ExternalExecutionContextSchema.parse(row.original_external_execution)}
  const known=await client.query<Pick<EveInvocationRow,"operation_id"|"envelope_sha256">>(`select operation_id,envelope_sha256 from knowledge_service.eve_operation_invocation where issuer=$1 and jti=$2 for update`,[p.issuer,p.jti]);if(known.rows.length){const row=known.rows[0]!;if(row.operation_id!==p.operationId||row.envelope_sha256!==envelopeSha)throw Error("EVE_VERIFICATION_JTI_COLLISION");return original}
  await client.query(`insert into knowledge_service.eve_operation_invocation(tenant_id,operation_id,issuer,key_id,jti,invocation_kind,envelope,envelope_sha256,lineage_sha256,observed_external_execution,issued_at,expires_at)values($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,$10::jsonb,to_timestamp($11),to_timestamp($12))`,[p.tenantId,p.operationId,p.issuer,p.keyId,p.jti,found.rows.length?'retry':'original',JSON.stringify(parsed),envelopeSha,lineageSha,JSON.stringify(p.externalExecution),p.issuedAt,p.expiresAt]);return original;
 });
}
