import { KNOWLEDGE_OPERATION_REQUEST_SCHEMA_VERSION } from "@aiengineer/knowledge-application";
import { canonicalizeJson,digestCanonicalJson,sha256Digest } from "@aiengineer/knowledge-verification";
import { describe,expect,it } from "vitest";
import { AuditInspectionReadError,PostgresAuditInspectionReadRepository } from "./verification-audit-inspection-reads.js";

const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`,tenantId=id(1),operationId=id(2),attemptId=id(3),stepId=id(4),receiptId=id(5),eventId=id(6),artifactId=id(7),audit={artifactId:id(8),digest:sha256Digest("audit")},at="2026-09-07T00:00:00.000Z";
const context={tenantId:tenantId,operationId,attemptId,missionId:id(9),workItemId:id(10),correlationId:id(11),actor:{kind:"service" as const,id:id(12),serviceIdentity:"mission_control_client" as const},capabilityVersion:"verification-service.v1",idempotencyKey:"audit-read-key",reason:"test",contractVersion:"v1" as const};
const serviceInput={schemaVersion:"verification-service-request.v1" as const,useCase:"inspectAuditBundle" as const,request:{verificationContractVersion:"verification.v1" as const,auditBundle:audit}};
const durable={schemaVersion:KNOWLEDGE_OPERATION_REQUEST_SCHEMA_VERSION,kind:"verification_audit_bundle" as const,input:serviceInput,expectedVersions:{verification:"verification.v1",service:"verification-service-request.v1"},authenticatedContext:context};
const step={schemaVersion:KNOWLEDGE_OPERATION_REQUEST_SCHEMA_VERSION,kind:"verification_audit_bundle" as const,operationInput:serviceInput,expectedVersions:durable.expectedVersions,context,step:{name:"inspect_audit_bundle_and_register" as const,ordinal:0 as const}};
const output={schemaVersion:"verification-audit-inspection.v1" as const,verificationContractVersion:"verification.v1" as const,auditArtifact:{...audit,mediaType:"application/vnd.aiengineer.verification-run-manifest+json",sizeBytes:100},run:{runId:id(13),manifestId:id(14),manifestDigest:sha256Digest("manifest"),deterministicResultDigest:sha256Digest("deterministic"),policyDecisionDigest:sha256Digest("policy"),policyOutcome:"review" as const,startedAt:at,completedAt:at},proof:{payloadDigest:sha256Digest("payload"),signatureStatus:"verified" as const,deterministicReplay:"exact" as const,policyReplay:"exact" as const,replayedArtifactCount:4,inputArtifactCount:2,outputArtifactCount:3}};
function fixture(change:Record<string,unknown>={}){const requestDigest=digestCanonicalJson(serviceInput.request),body={schemaVersion:"verification-operation-result.v1" as const,operationId,useCase:"inspectAuditBundle" as const,requestDigest,output},bytes=new TextEncoder().encode(canonicalizeJson(body)),handle={artifactId,tenantId,digest:sha256Digest(bytes),mediaType:"application/vnd.aiengineer.verification-audit-inspection-result+json",byteLength:bytes.byteLength,objectKey:"internal/result",createdAt:at,producerActivityId:"verification-service:inspectAuditBundle",producerVersion:"verification-service.v1",encryptionClass:"supabase-managed",retentionClass:"verification-audit",dataClassification:"restricted" as const,parentArtifactIds:[audit.artifactId],transformationSignature:digestCanonicalJson({kind:"verification_audit_inspection_result.v1",operationId,requestDigest,auditArtifact:audit})},result={...body,resultArtifact:handle},row={status:"succeeded",request:durable,request_sha256:digestCanonicalJson(durable).slice(7),idempotency_key:context.idempotencyKey,actor_identity:`service:${context.actor.id}`,attempt_id:attemptId,mission_id:context.missionId,work_item_id:context.workItemId,correlation_id:context.correlationId,causation_id:null,ownership_mode:"standalone",external_run_id:null,step_id:stepId,step_status:"succeeded",step_key:"inspect_audit_bundle_and_register",step_kind:"inspect_audit_bundle_and_register",input:step,input_sha256:digestCanonicalJson(step).slice(7),receipt_id:receiptId,receipt_kind:"inspect_audit_bundle_and_register.succeeded",outcome:"succeeded",receipt_input_sha256:digestCanonicalJson(step).slice(7),output_sha256:digestCanonicalJson(result).slice(7),body:{...result,eventId,fencingToken:7},artifact_id:artifactId,artifact_type:"verification_audit_inspection_result",bucket_class:"ledger",event_id:eventId,event_operation_id:operationId,event_step_id:stepId,event_kind:"step.succeeded",event_from_state:"running",event_to_state:"succeeded",event_guarded_sha256:digestCanonicalJson(result).slice(7),event_payload:{outputSha256:digestCanonicalJson(result).slice(7),fencingToken:"7"},...change};return{row,bytes,handle,result};}
function subject(value:ReturnType<typeof fixture>){return new PostgresAuditInspectionReadRepository({transaction:async(_tenant:string,work:(client:any)=>Promise<any>)=>work({query:async()=>({rows:[value.row],rowCount:1})})} as never,()=>{let authorized=false;return{authorizeArtifact:async()=>{authorized=true;},hydrateRegisteredArtifact:async()=>{if(!authorized)throw new Error("NO_TICKET");return{registration:value.handle,bytes:value.bytes};}};});}
describe("native audit inspection result reads",()=>{
  it("requires the terminal event, receipt, exact request parent, and canonical registered bytes",async()=>{const value=fixture();await expect(subject(value).loadVerifiedInspection(tenantId,operationId)).resolves.toMatchObject({state:"succeeded",result:value.result});});
  it("attributes event and artifact drift to integrity rather than absence",async()=>{for(const change of [{event_guarded_sha256:"0".repeat(64)},{artifact_type:"verification_audit_bundle"},{receipt_input_sha256:"1".repeat(64)}]){await expect(subject(fixture(change)).loadVerifiedInspection(tenantId,operationId)).rejects.toBeInstanceOf(AuditInspectionReadError);}});
});
