import {describe,expect,it,vi} from "vitest";
import {canonicalizeJson,providerDigest} from "@aiengineer/knowledge-verification";
import {SemanticObservationArtifactComposer} from "@aiengineer/knowledge-application";
import {PostgresSemanticObservationArtifactRegistration} from "./verification-semantic-observation-registration.js";
const id = (suffix: string) => `00000000-0000-4000-8000-${suffix.padStart(12, "0")}`;
const digest = (character: string) => `sha256:${character.repeat(64)}`;
const handle = (suffix: string, character: string, parents: readonly string[] = []) => ({ artifactId: id(suffix), digest: digest(character), tenantId: id("1"), byteLength: 1, mediaType: "application/json", objectKey: `restricted/${suffix}`, createdAt: "2026-09-07T00:00:00.000Z", producerActivityId: "semantic-worker", producerVersion: "v1", encryptionClass: "managed", retentionClass: "verification-audit", dataClassification: "restricted" as const, parentArtifactIds: [...parents], transformationSignature: digest("f") });
const blinded = handle("3", "c"), request = handle("4", "d", [blinded.artifactId]), raw = handle("5", "e"), envelope = handle("6", "f", [request.artifactId, raw.artifactId]), profile = handle("2", "b");
const body = () => ({ schemaVersion: "verification-semantic-response-observation.v1" as const, verificationContractVersion: "verification.v1" as const, context: { tenantId: id("1"), operationId: id("8"), operationStepId: id("9"), leaseToken: id("10"), fencingToken: 2, holderIdentity: "verification-worker", producerAttemptId: id("12"), providerAttemptId: id("11"), host: { operationKind: "verification_claims" as const, stepKey: "verify_claims_and_register" as const, useCase: "verifyClaims" as const } }, profileArtifact: profile, blindedInputArtifact: blinded, requestArtifact: request, rawResponseArtifact: raw, responseEnvelopeArtifact: envelope, judgeIdentity: { deploymentId: "gateway-luna", provider: "vercel-ai-gateway", family: "openai", model: "openai/gpt-5.6-luna", capability: "llm_evidence_rubric" as const, graderVersion: "evidence-only.v1", promptDigest: digest("2"), outputSchemaDigest: digest("3"), configurationDigest: digest("4") }, inputArtifactDigest: blinded.digest, requestDigest: request.digest, rawResponseDigest: raw.digest, requestedModel: "openai/gpt-5.6-luna", observedModel: "openai/gpt-5.6-luna", modelStatus: "matched" as const, revalidationRequired: false, usage: { totalTokens: 0 }, costStatus: "unknown" as const });


const lease=()=>({id:id("9"),tenantId:id("1"),operationId:id("8"),leaseToken:id("10"),fencingToken:2,holderIdentity:"verification-worker",stepKey:"verify_claims_and_register",stepKind:"verify_claims_and_register",inputSha256:"a".repeat(64),status:"running",attemptCount:1,maxAttempts:1,rowVersion:1,expiresAt:"2026-09-07T01:00:00.000Z"});
const config={storageBucket:"ai-engineer-cloud-bucket",producerActivityId:"semantic-worker",producerVersion:"v1",encryptionClass:"managed",retentionClass:"verification-audit",now:()=>"2026-09-07T00:00:00.000Z"};
describe("fenced semantic observation registration",()=>{
 it("connects composer bytes to a native fenced registration request",async()=>{const register=vi.fn(async(input:any)=>({...handle("7","1",input.artifact.parentArtifactIds),digest:providerDigest(body()),byteLength:input.artifact.bytes.byteLength,mediaType:input.artifact.mediaType,transformationSignature:input.artifact.transformationSignature}));const adapter=new PostgresSemanticObservationArtifactRegistration({registerFencedContentAddressedArtifact:register},lease());const result=await new SemanticObservationArtifactComposer(adapter,config).compose(body());expect(result.observationArtifact.digest).toBe(providerDigest(body()));expect(register.mock.calls[0]![0].lease).toEqual({stepId:id("9"),leaseToken:id("10"),fencingToken:2,holderIdentity:"verification-worker"});});
 it("rejects mismatched lease before registration",async()=>{const register=vi.fn();const adapter=new PostgresSemanticObservationArtifactRegistration({registerFencedContentAddressedArtifact:register}, {...lease(),fencingToken:3});await expect(new SemanticObservationArtifactComposer(adapter,config).compose(body())).rejects.toThrow("SEMANTIC_OBSERVATION_REGISTRATION_BINDING_MISMATCH");expect(register).not.toHaveBeenCalled();});
 it("snapshots caller lease against mutation",async()=>{const register=vi.fn(async()=>{throw new Error("REGISTER_REACHED");}),l=lease();const adapter=new PostgresSemanticObservationArtifactRegistration({registerFencedContentAddressedArtifact:register},l);l.fencingToken=99;await expect(new SemanticObservationArtifactComposer(adapter,config).compose(body())).rejects.toThrow("REGISTER_REACHED");expect(register).toHaveBeenCalledOnce();});
 it("rejects changed parents before registration",async()=>{const register=vi.fn();const adapter=new PostgresSemanticObservationArtifactRegistration({registerFencedContentAddressedArtifact:register},lease());const composer=new SemanticObservationArtifactComposer({registerSemanticObservationArtifact:input=>adapter.registerSemanticObservationArtifact({...input,parentArtifactIds:[id("2"),id("6"),id("3")]})},config);await expect(composer.compose(body())).rejects.toThrow("SEMANTIC_OBSERVATION_REGISTRATION_BINDING_MISMATCH");expect(register).not.toHaveBeenCalled();});

});
