import { describe, expect, it } from "vitest";
import { canonicalizeJson, providerDigest } from "@aiengineer/knowledge-verification";
import { mapSemanticObservation } from "./verification-semantic-observation.js";
const id = (suffix: string) => `00000000-0000-4000-8000-${suffix.padStart(12, "0")}`;
const digest = (character: string) => `sha256:${character.repeat(64)}`;
const handle = (suffix: string, character: string, parents: readonly string[] = []) => ({ artifactId: id(suffix), digest: digest(character), tenantId: id("1"), byteLength: 1, mediaType: "application/json", objectKey: `restricted/${suffix}`, createdAt: "2026-09-07T00:00:00.000Z", producerActivityId: "semantic-worker", producerVersion: "v1", encryptionClass: "managed", retentionClass: "verification-audit", dataClassification: "restricted" as const, parentArtifactIds: [...parents], transformationSignature: digest("f") });
const blinded = handle("3", "c"), request = handle("4", "d", [blinded.artifactId]), raw = handle("5", "e"), envelope = handle("6", "f", [request.artifactId, raw.artifactId]), profile = handle("2", "b");
const body = () => ({ schemaVersion: "verification-semantic-response-observation.v1" as const, verificationContractVersion: "verification.v1" as const, context: { tenantId: id("1"), operationId: id("8"), operationStepId: id("9"), leaseToken: id("10"), fencingToken: 2, holderIdentity: "verification-worker", producerAttemptId: id("12"), providerAttemptId: id("11"), host: { operationKind: "verification_claims" as const, stepKey: "verify_claims_and_register" as const, useCase: "verifyClaims" as const } }, profileArtifact: profile, blindedInputArtifact: blinded, requestArtifact: request, rawResponseArtifact: raw, responseEnvelopeArtifact: envelope, judgeIdentity: { deploymentId: "gateway-luna", provider: "vercel-ai-gateway", family: "openai", model: "openai/gpt-5.6-luna", capability: "llm_evidence_rubric" as const, graderVersion: "evidence-only.v1", promptDigest: digest("2"), outputSchemaDigest: digest("3"), configurationDigest: digest("4") }, inputArtifactDigest: blinded.digest, requestDigest: request.digest, rawResponseDigest: raw.digest, requestedModel: "openai/gpt-5.6-luna", observedModel: "openai/gpt-5.6-luna", modelStatus: "matched" as const, revalidationRequired: false, usage: { totalTokens: 0 }, costStatus: "unknown" as const });

const observation = () => { const value=body(); return {...value,observationArtifact:{...handle("7","1",[blinded.artifactId,envelope.artifactId,profile.artifactId]),digest:providerDigest(value),byteLength:new TextEncoder().encode(canonicalizeJson(value)).byteLength,transformationSignature:providerDigest({kind:"verification_semantic_response_observation.v1",body:value})}}; };
describe("semantic observation persistence mapping",()=>{
 it("maps distinct producer/provider identity and preserves unknown usage",()=>{const row=mapSemanticObservation(observation());expect(row).toMatchObject({producerAttemptId:id("12"),providerAttemptId:id("11"),promptTokens:null,completionTokens:null,totalTokens:0,reportedCostMicros:null,reportedCostStatus:"unknown",responseEnvelopeArtifactId:envelope.artifactId,requestSha256:"d".repeat(64)});});
 it("rejects digest, size and signature corruption",()=>{for(const patch of [{digest:digest("0")},{byteLength:1},{transformationSignature:digest("0")}]) {const x=observation();expect(()=>mapSemanticObservation({...x,observationArtifact:{...x.observationArtifact,...patch}})).toThrow("SEMANTIC_OBSERVATION_BODY_BINDING_MISMATCH");}});
 it("rejects producer/provider alias and request parent substitution",()=>{const x=observation();expect(()=>mapSemanticObservation({...x,context:{...x.context,producerAttemptId:x.context.providerAttemptId}})).toThrow();expect(()=>mapSemanticObservation({...x,requestArtifact:{...x.requestArtifact,parentArtifactIds:[profile.artifactId]}})).toThrow();});
});
