import {describe,expect,it,vi} from "vitest";
import {canonicalizeJson,providerDigest} from "@aiengineer/knowledge-verification";
import {PostgresVerificationSemanticObservationStore} from "./verification-semantic-observation-store.js";
import {mapSemanticObservation} from "./verification-semantic-observation.js";
const id = (suffix: string) => `00000000-0000-4000-8000-${suffix.padStart(12, "0")}`;
const digest = (character: string) => `sha256:${character.repeat(64)}`;
const handle = (suffix: string, character: string, parents: readonly string[] = []) => ({ artifactId: id(suffix), digest: digest(character), tenantId: id("1"), byteLength: 1, mediaType: "application/json", objectKey: `restricted/${suffix}`, createdAt: "2026-09-07T00:00:00.000Z", producerActivityId: "semantic-worker", producerVersion: "v1", encryptionClass: "managed", retentionClass: "verification-audit", dataClassification: "restricted" as const, parentArtifactIds: [...parents], transformationSignature: digest("f") });
const blinded = handle("3", "c"), request = handle("4", "d", [blinded.artifactId]), raw = handle("5", "e"), envelope = handle("6", "f", [request.artifactId, raw.artifactId]), profile = handle("2", "b");
const body = () => ({ schemaVersion: "verification-semantic-response-observation.v1" as const, verificationContractVersion: "verification.v1" as const, context: { tenantId: id("1"), operationId: id("8"), operationStepId: id("9"), leaseToken: id("10"), fencingToken: 2, holderIdentity: "verification-worker", producerAttemptId: id("12"), providerAttemptId: id("11"), host: { operationKind: "verification_claims" as const, stepKey: "verify_claims_and_register" as const, useCase: "verifyClaims" as const } }, profileArtifact: profile, blindedInputArtifact: blinded, requestArtifact: request, rawResponseArtifact: raw, responseEnvelopeArtifact: envelope, judgeIdentity: { deploymentId: "gateway-luna", provider: "vercel-ai-gateway", family: "openai", model: "openai/gpt-5.6-luna", capability: "llm_evidence_rubric" as const, graderVersion: "evidence-only.v1", promptDigest: digest("2"), outputSchemaDigest: digest("3"), configurationDigest: digest("4") }, inputArtifactDigest: blinded.digest, requestDigest: request.digest, rawResponseDigest: raw.digest, requestedModel: "openai/gpt-5.6-luna", observedModel: "openai/gpt-5.6-luna", modelStatus: "matched" as const, revalidationRequired: false, usage: { totalTokens: 0 }, costStatus: "unknown" as const });

const observation = () => { const value=body(); return {...value,observationArtifact:{...handle("7","1",[blinded.artifactId,envelope.artifactId,profile.artifactId]),digest:providerDigest(value),byteLength:new TextEncoder().encode(canonicalizeJson(value)).byteLength,transformationSignature:providerDigest({kind:"verification_semantic_response_observation.v1",body:value})}}; };

function database(options:{stale?:boolean;badHost?:boolean;drift?:boolean;artifactDrift?:boolean;prior?:boolean;expireDuringReplay?:boolean}={}) {
 const value=observation();
 const handles=[value.profileArtifact,value.blindedInputArtifact,value.requestArtifact,value.rawResponseArtifact,value.responseEnvelopeArtifact,value.observationArtifact];
 const types=["verification_semantic_judge_profile","verification_semantic_blinded_input","verification_provider_request","verification_provider_raw_response","verification_provider_response_envelope","verification_semantic_response_observation"];
 const mapped=Object.fromEntries(Object.entries(mapSemanticObservation(value)).map(([k,v])=>[k.replace(/[A-Z]/g,l=>`_${l.toLowerCase()}`),v]));
 let scopeCalls=0;
 const query=vi.fn(async(sql:string,params:readonly unknown[]=[])=>{
  if(sql.includes("scope_tuple_is_live")){scopeCalls++;return {rows:[{live:!options.stale && !(options.expireDuringReplay && scopeCalls>1)}]};}
  if(sql.includes("select o.id"))return {rows:options.badHost?[]:[{id:value.context.operationId}]};
  if(sql.includes("select a.*")) {const i=handles.findIndex(h=>h.artifactId===params[1]),h=handles[i]!;return {rows:[{id:h.artifactId,tenant_id:h.tenantId,sha256:h.digest.slice(7),media_type:h.mediaType,size_bytes:h.byteLength,object_path:h.objectKey,created_at:h.createdAt,producer_activity_id:h.producerActivityId,producer_version:options.artifactDrift?"forged":h.producerVersion,encryption_class:h.encryptionClass,retention_class:h.retentionClass,data_classification:h.dataClassification,parent_artifact_ids:h.parentArtifactIds,transformation_signature:h.transformationSignature.slice(7),storage_state:"available",artifact_type:types[i],bucket_class:"ledger",storage_bucket:"private",producer_attempt_id:value.context.producerAttemptId}]};}
  if(sql.startsWith("select * from orchestration.verification_semantic_response_observation"))return {rows:options.prior?[{...mapped,...(options.drift?{requested_model:"wrong"}:{})}]:[]};
  if(sql.startsWith("insert into orchestration.verification_semantic_response_observation"))return {rows:[mapped]};
  return {rows:[]};
 });
 return {query,value,db:{transaction:async(_tenant:string,work:(client:unknown)=>Promise<unknown>)=>work({query})} as never};
}
describe("semantic observation store",()=>{
 it("inserts exact mapped row only after custody checks",async()=>{const f=database();expect(await new PostgresVerificationSemanticObservationStore(f.db).store(f.value)).toEqual(mapSemanticObservation(f.value));expect(f.query.mock.calls.filter(([sql])=>sql.includes("select a.*"))).toHaveLength(6);expect(f.query.mock.calls.some(([sql])=>sql.startsWith("insert into"))).toBe(true);});
 it("replays an exact prior row without reinserting",async()=>{const f=database({prior:true});await new PostgresVerificationSemanticObservationStore(f.db).store(f.value);expect(f.query.mock.calls.some(([sql])=>sql.startsWith("insert into"))).toBe(false);});
 it("rejects stale scope, wrong host, artifact drift and replay drift before writes",async()=>{for(const options of [{stale:true},{badHost:true},{artifactDrift:true},{prior:true,drift:true},{prior:true,expireDuringReplay:true}]){const f=database(options);await expect(new PostgresVerificationSemanticObservationStore(f.db).store(f.value)).rejects.toThrow();expect(f.query.mock.calls.some(([sql])=>sql.startsWith("insert into"))).toBe(false);}});
 it("uses current recovery lease while preserving original dispatch fence",async()=>{const f=database({prior:true}),c=f.value.context;const current={id:c.operationStepId,tenantId:c.tenantId,operationId:c.operationId,stepKey:c.host.stepKey,stepKind:c.host.stepKey,inputSha256:"a".repeat(64),status:"running",attemptCount:2,maxAttempts:3,rowVersion:2,holderIdentity:"replacement",leaseToken:id("99"),fencingToken:3,expiresAt:"2026-09-07T01:00:00.000Z"};const result=await new PostgresVerificationSemanticObservationStore(f.db).store(f.value,current);expect(result.dispatchFencingToken).toBe(2);const claim=f.query.mock.calls.find(([sql])=>sql.includes("set_config"));expect(JSON.parse(String(claim?.[1]?.[0]))).toMatchObject({fencingToken:3,holderIdentity:"replacement"});await expect(new PostgresVerificationSemanticObservationStore(f.db).store(f.value,{...current,fencingToken:1})).rejects.toThrow("SEMANTIC_OBSERVATION_RECOVERY_LEASE_MISMATCH");});

});
