import {describe,it,expect,vi} from "vitest";
import {VerificationAdjudicationDecisionPreparationService, type VerificationAdjudicationDecisionPreparationPort} from "./verification-adjudication-decision.js";
import type {OperationContext,VerificationAdjudicationTerminalResource} from "@aiengineer/knowledge-contracts";
import {VerificationOperationApplicationService} from "./verification-service.js";
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const digest=`sha256:${"a".repeat(64)}` as const;
const ref=(n:number)=>({artifactId:id(n),digest});
const context:OperationContext={tenantId:id(1),operationId:id(2),attemptId:id(3),correlationId:"synthetic-review-test",actor:{kind:"service",id:id(4),serviceIdentity:"human_reviewer"},capabilityVersion:"test.v1",idempotencyKey:"synthetic-review-test",reason:"Engineering fixture, not a human decision",contractVersion:"v1"};
const request={verificationContractVersion:"verification.v1" as const,subjectId:id(5),packetArtifact:ref(6),decision:"affirm" as const,rationale:"Synthetic review fixture only."};
function subject():VerificationAdjudicationTerminalResource{return {verificationContractVersion:"verification.v1",tenantId:id(1),operationId:id(7),requestDigest:digest,packetArtifact:ref(6),output:{subjectId:id(5),status:"pending_human_adjudication",target:{kind:"run",runId:id(8),objectDigest:digest},reason:"policy_review",reviewRequirements:{eligibleReviewerRoles:["verification_expert"],quorumRequired:2},originalPolicyOutcome:"fail",source:{runKind:"claims",runId:id(8),manifestArtifact:ref(9),manifestDigest:digest,bundleArtifact:ref(10),deterministicResultArtifact:ref(11),policyDecisionArtifact:ref(12)},proof:{payloadDigest:digest,signatureStatus:"verified",deterministicReplay:"exact",policyReplay:"exact",terminalFencingToken:1},humanDecisionRecorded:false,admissionChanged:false}};}
function fixture(){const authorizeReviewer=vi.fn<VerificationAdjudicationDecisionPreparationPort["authorizeReviewer"]>().mockResolvedValue({provenance:"synthetic_engineering",role:"verification_expert"});const loadVerifiedSubject=vi.fn<VerificationAdjudicationDecisionPreparationPort["loadVerifiedSubject"]>().mockImplementation(async()=>subject());const service=new VerificationAdjudicationDecisionPreparationService({authorizeReviewer,loadVerifiedSubject},()=>Date.parse("2026-09-08T00:00:00Z"));return {authorizeReviewer,loadVerifiedSubject,service};}
const input=()=>({request:structuredClone(request),context:structuredClone(context),signal:new AbortController().signal});
describe("packet-bound decision preparation (engineering fixtures only)",()=>{
 it("submits the exact decision envelope through the canonical operation port",()=>{
  const submit=vi.fn();const service=new VerificationOperationApplicationService({submit} as never,"http://localhost");
  service.submitRecordAdjudicationDecision(request,context);
  expect(submit).toHaveBeenCalledWith("verification_adjudication_decision",{context,input:{schemaVersion:"verification-service-request.v1",useCase:"recordAdjudicationDecision",request},expectedVersions:{verification:"verification.v1",service:"verification-service-request.v1"}},"http://localhost");
 });
 it("rejects caller authority fields and non-reviewer identities before submission",()=>{
  const submit=vi.fn();const service=new VerificationOperationApplicationService({submit} as never,"http://localhost");
  expect(()=>service.submitRecordAdjudicationDecision({...request,reviewerRole:"admin"},context)).toThrow();
  expect(()=>service.submitRecordAdjudicationDecision(request,{...context,actor:{kind:"service",id:id(4),serviceIdentity:"knowledge_worker"}})).toThrow("AUTHORITY_REQUIRED");
  expect(submit).not.toHaveBeenCalled();
 });
 it("binds stable immutable bytes to exact packet, identity and unchanged failed policy",async()=>{const {service}=fixture();const a=await service.prepare(input()),b=await service.prepare(input());expect(a.decisionDigest).toBe(b.decisionDigest);expect(a.decisionId).toBe(b.decisionId);expect(a.parentArtifactIds).toEqual([id(6)]);expect(JSON.parse(new TextDecoder().decode(a.decisionBytes))).toMatchObject({originalPolicyOutcome:"fail",admissionChanged:false,humanGoldScoringEligible:false,reviewer:{provenance:"synthetic_engineering",actorId:id(4)}});expect(Object.isFrozen(a.request.packetArtifact)).toBe(true);});
 it("rejects non-reviewer services before permission or packet reads",async()=>{const f=fixture(),value=input();value.context.actor={kind:"service",id:id(4),serviceIdentity:"knowledge_worker"};await expect(f.service.prepare(value)).rejects.toMatchObject({code:"AUTHORITY_REQUIRED"});expect(f.authorizeReviewer).not.toHaveBeenCalled();expect(f.loadVerifiedSubject).not.toHaveBeenCalled();});
 it("requires explicit permission and cannot upgrade service provenance to human",async()=>{const f=fixture();f.authorizeReviewer.mockResolvedValueOnce(undefined);await expect(f.service.prepare(input())).rejects.toMatchObject({code:"AUTHORITY_REQUIRED"});f.authorizeReviewer.mockResolvedValueOnce({provenance:"human_origin",grantId:id(20),role:"verification_expert"});await expect(f.service.prepare(input())).rejects.toMatchObject({code:"AUTHORITY_REQUIRED"});expect(f.loadVerifiedSubject).not.toHaveBeenCalled();});
 it("rejects packet, subject, tenant and role substitutions",async()=>{for(const change of [(s:VerificationAdjudicationTerminalResource)=>{s.tenantId=id(99);},(s:VerificationAdjudicationTerminalResource)=>{s.output.subjectId=id(99);},(s:VerificationAdjudicationTerminalResource)=>{s.packetArtifact=ref(99);},(s:VerificationAdjudicationTerminalResource)=>{s.packetArtifact.digest=`sha256:${"b".repeat(64)}`;},(s:VerificationAdjudicationTerminalResource)=>{s.output.reviewRequirements.eligibleReviewerRoles=["other"]; }]){const f=fixture(),s=subject();change(s);f.loadVerifiedSubject.mockResolvedValue(s);await expect(f.service.prepare(input())).rejects.toMatchObject({code:"BINDING"});}});
 it("rechecks expiry after hydration and rejects expired subjects",async()=>{const f=fixture(),s=subject();s.output.reviewRequirements.expiresAt="2026-09-07T00:00:00Z";f.loadVerifiedSubject.mockResolvedValue(s);await expect(f.service.prepare(input())).rejects.toMatchObject({code:"EXPIRED"});let now=Date.parse("2026-09-08T00:00:00Z");f.authorizeReviewer.mockResolvedValue({provenance:"synthetic_engineering",role:"verification_expert",expiresAt:"2026-09-08T00:00:01Z"});f.loadVerifiedSubject.mockImplementation(async()=>{now+=2000;return subject();});const service=new VerificationAdjudicationDecisionPreparationService(f,()=>now);await expect(service.prepare(input())).rejects.toMatchObject({code:"EXPIRED"});});
 it("honors cancellation after awaited authority and packet boundaries",async()=>{for(const at of ["authority","packet"]){const f=fixture(),controller=new AbortController();if(at==="authority")f.authorizeReviewer.mockImplementation(async()=>{controller.abort();return {provenance:"synthetic_engineering",role:"verification_expert"};});else f.loadVerifiedSubject.mockImplementation(async()=>{controller.abort();return subject();});await expect(f.service.prepare({...input(),signal:controller.signal})).rejects.toMatchObject({code:"CANCELLED"});if(at==="authority")expect(f.loadVerifiedSubject).not.toHaveBeenCalled();}});
});
