import type { OperationContext, SemanticAssessmentRecord, VerificationArtifactHandle, VerificationPolicyDefinition, VerificationRecordedPolicyInputs, VerificationRunManifest } from "@aiengineer/knowledge-contracts";
import { evaluateVerificationPolicy } from "@aiengineer/knowledge-policy";
import { canonicalizeJson, createEd25519Signer, createEd25519Verifier, digestCanonicalJson, sealAuditBundle, sha256Digest, verificationManifestDigest, verifyDeterministicBundle, type RuntimePrincipalBinding, type VerificationAuditBundle } from "@aiengineer/knowledge-verification";
import { generateKeyPairSync } from "node:crypto";
import { describe, expect, it, vi } from "vitest";
import { VerificationAuditInspectionApplicationService, VerificationAuditInspectionError } from "./verification-audit-inspection.js";

const tenantId="11111111-1111-4111-8111-111111111111",createdAt="2026-09-07T00:00:00.000Z";
type PrototypeFixture={prototypeClaimInput():{bundle:Parameters<typeof verifyDeterministicBundle>[0]["bundle"];artifacts:readonly {artifactId:string;content:string|Uint8Array}[]};runtimePrincipals:RuntimePrincipalBinding};
const fixtureUrl=new URL("../../verification/src/deterministic/testing/prototype-parity.fixture.js",import.meta.url).href;
const context:OperationContext={contractVersion:"v1",tenantId,operationId:"22222222-2222-4222-8222-222222222222",attemptId:"33333333-3333-4333-8333-333333333333",correlationId:"audit-inspection",actor:{kind:"service",id:"44444444-4444-4444-8444-444444444444",serviceIdentity:"knowledge_worker"},capabilityVersion:"verification.v1",idempotencyKey:"audit-inspection-key",reason:"test"};
function handle(artifactId:string,bytes:Uint8Array,mediaType="application/json",parents:readonly string[]=[]):VerificationArtifactHandle{const digest=sha256Digest(bytes);return{artifactId,tenantId,digest,mediaType,byteLength:bytes.byteLength,objectKey:`${tenantId}/${digest.slice(7,9)}/${digest.slice(7)}`,createdAt,producerActivityId:"fixture",producerVersion:"fixture.v1",encryptionClass:"managed",retentionClass:"audit",dataClassification:"restricted",parentArtifactIds:[...parents],...(parents.length?{transformationSignature:sha256Digest(`transform:${artifactId}`)}:{})};}
function semantic(assertionId:string):SemanticAssessmentRecord{return{assertionId,verdict:"pending_semantic_review",disposition:"review",evidenceSupport:"not_assessed",worldCorrectness:"not_assessed",attributionFaithfulness:"not_assessed",sourceAuthority:"not_assessed",provenanceIntegrity:"satisfied",judgeIdentities:[],supportingFragmentIds:[],contradictingFragmentIds:[],unsupportedFacets:[],reasonCodes:[],crossFamilySecondJudge:false,rawProviderConfidences:[]};}

async function fixture(signed=true,judged=false){
  const prototype=await import(fixtureUrl) as PrototypeFixture,input=prototype.prototypeClaimInput(),deterministicResult=verifyDeterministicBundle({bundle:input.bundle,artifacts:input.artifacts,runtimePrincipals:prototype.runtimePrincipals});
  const source=input.bundle.captures[0]!.contentArtifact,sourceBytes=new TextEncoder().encode(String(input.artifacts[0]!.content));
  const policy:VerificationPolicyDefinition={schemaVersion:"verification-policy.v1",policyVersion:input.bundle.policyVersion,definitionId:"inspection-policy",criticalDownstreamUses:[],requireCrossFamilyForRisk:[],requireIndependentAuthorityForScopes:[],mixedEvidenceOutcome:"review",unknownCriticalOutcome:"review",authorityWithheldOutcome:"review",reviewAvailable:true};
  const policyBytes=new TextEncoder().encode(canonicalizeJson(policy)),policyArtifact=handle("55555555-5555-4555-8555-555555555555",policyBytes);
  const recorded:VerificationRecordedPolicyInputs={schemaVersion:"verification-policy-inputs.v1",policyVersion:policy.policyVersion,runId:"inspection-run",recordedAt:createdAt,deterministicResult,assertions:input.bundle.assertions.map(assertion=>({assertionId:assertion.assertionId,riskClass:assertion.riskClass,downstreamUse:[...assertion.downstreamUse],claimScope:"descriptive_fact" as const,semantic:judged?{...semantic(assertion.assertionId),verdict:"directly_supported",disposition:"admit",evidenceSupport:"satisfied"}:semantic(assertion.assertionId),authorityStatus:"unknown" as const,independentCorroboration:false,conflictPresent:false,criticalFactsKnown:true})),metrics:[],sourceAssessments:[]};
  const recordedBytes=new TextEncoder().encode(canonicalizeJson(recorded)),recordedArtifact=handle("66666666-6666-4666-8666-666666666666",recordedBytes),decision=evaluateVerificationPolicy(policy,recorded);
  const manifest:VerificationRunManifest={verificationContractVersion:"verification.v1",manifestId:"inspection-manifest",runId:recorded.runId,versions:{policy:policy.policyVersion,schema:"verification.v1",normalizer:"RFC8785.v1"},code:{gitSha:"fixture",dirty:false},runtime:{platform:"test",deploymentId:input.bundle.verifier.deploymentId},inputArtifacts:[source,policyArtifact,recordedArtifact],outputArtifacts:[],stages:[{name:"verify",status:"succeeded",startedAt:createdAt,endedAt:createdAt}],calls:[],toolPolicy:[],networkPolicy:"disabled",deterministicResult,judgments:[],policyOutcome:decision.outcome,resultDigest:digestCanonicalJson(deterministicResult),lineage:[],canonicalization:{algorithm:"RFC8785",implementationVersion:"knowledge-verification.v1",manifestDigest:sha256Digest("")},startedAt:createdAt,completedAt:createdAt};manifest.canonicalization.manifestDigest=verificationManifestDigest(manifest);
  const keys=generateKeyPairSync("ed25519"),keyId="inspection-key",signer=createEd25519Signer(keys.privateKey.export({format:"pem",type:"pkcs8"}).toString(),keyId),verifier=createEd25519Verifier({[keyId]:keys.publicKey.export({format:"pem",type:"spki"}).toString()});
  const audit=await sealAuditBundle({tenantId,verificationBundle:input.bundle,manifest,policyBinding:{policyVersion:policy.policyVersion,policyArtifact,recordedPolicyInputsArtifact:recordedArtifact},recordedPolicyInputsBytes:recordedBytes,policyDecision:decision,...(signed?{signer}:{})});
  const auditBytes=new TextEncoder().encode(canonicalizeJson(audit)),auditArtifact=handle("77777777-7777-4777-8777-777777777777",auditBytes,"application/vnd.aiengineer.verification-run-manifest+json",[source,policyArtifact,recordedArtifact].map(item=>item.artifactId).sort());
  const values=new Map([[auditArtifact.artifactId,{registration:auditArtifact,bytes:auditBytes}],[source.artifactId,{registration:source,bytes:sourceBytes}],[policyArtifact.artifactId,{registration:policyArtifact,bytes:policyBytes}],[recordedArtifact.artifactId,{registration:recordedArtifact,bytes:recordedBytes}]]),authorized=new Set<string>();
  const resolver={async authorizeArtifact({artifactId}:{artifactId:string}){authorized.add(artifactId);},async hydrateRegisteredArtifact({artifactId}:{artifactId:string}){if(!authorized.delete(artifactId))throw new Error("HYDRATE_WITHOUT_AUTHORIZATION");return structuredClone(values.get(artifactId)!);}};
  const replayTrust={resolve:vi.fn(async()=>({runtimePrincipals:prototype.runtimePrincipals}))};
  return{audit,auditArtifact,auditBytes,values,resolver,replayTrust,verifier,prototype};
}

describe("verification audit inspection application",()=>{
  it("verifies the registered signed bundle and returns only compact replay proof",async()=>{const value=await fixture(),service=new VerificationAuditInspectionApplicationService({artifactResolver:value.resolver,signatureVerifier:value.verifier,replayTrust:value.replayTrust});const result=await service.inspect({verificationContractVersion:"verification.v1",auditBundle:{artifactId:value.auditArtifact.artifactId,digest:value.auditArtifact.digest}},context);expect(result).toMatchObject({schemaVersion:"verification-audit-inspection.v1",auditArtifact:{artifactId:value.auditArtifact.artifactId,digest:value.auditArtifact.digest},run:{runId:value.audit.manifest.runId,policyOutcome:value.audit.manifest.policyOutcome},proof:{signatureStatus:"verified",deterministicReplay:"exact",policyReplay:"exact"}});expect(result.auditArtifact).not.toHaveProperty("objectKey");expect(canonicalizeJson(result)).not.toContain("verificationBundle");expect(value.replayTrust.resolve).toHaveBeenCalledTimes(1);});
  it("rejects caller trust material and exact tenant/handle drift before replay trust",async()=>{const value=await fixture(),service=new VerificationAuditInspectionApplicationService({artifactResolver:value.resolver,signatureVerifier:value.verifier,replayTrust:value.replayTrust});await expect(service.inspect({verificationContractVersion:"verification.v1",auditBundle:{artifactId:value.auditArtifact.artifactId,digest:value.auditArtifact.digest},publicKeyPem:"caller"},context)).rejects.toThrow("VERIFICATION_AUDIT_INSPECTION_INVALID_REQUEST");await expect(service.inspect({verificationContractVersion:"verification.v1",auditBundle:{artifactId:value.auditArtifact.artifactId,digest:sha256Digest("drift")}},context)).rejects.toThrow("VERIFICATION_AUDIT_INSPECTION_ARTIFACT_INTEGRITY_FAILURE");await expect(service.inspect({verificationContractVersion:"verification.v1",auditBundle:{artifactId:value.auditArtifact.artifactId,digest:value.auditArtifact.digest}},{...context,tenantId:"99999999-9999-4999-8999-999999999999"})).rejects.toThrow("VERIFICATION_AUDIT_INSPECTION_ARTIFACT_INTEGRITY_FAILURE");expect(value.replayTrust.resolve).not.toHaveBeenCalled();});
  it("fails closed with typed signature and replay failures",async()=>{const unsigned=await fixture(false),unsignedService=new VerificationAuditInspectionApplicationService({artifactResolver:unsigned.resolver,signatureVerifier:unsigned.verifier,replayTrust:unsigned.replayTrust});await expect(unsignedService.inspect({verificationContractVersion:"verification.v1",auditBundle:{artifactId:unsigned.auditArtifact.artifactId,digest:unsigned.auditArtifact.digest}},context)).rejects.toThrow("VERIFICATION_AUDIT_INSPECTION_SIGNATURE_UNTRUSTED");expect(unsigned.replayTrust.resolve).not.toHaveBeenCalled();const tampered=await fixture(),recorded=tampered.audit.policyBinding.recordedPolicyInputsArtifact,stored=tampered.values.get(recorded.artifactId)!;stored.bytes=new TextEncoder().encode("{}");const service=new VerificationAuditInspectionApplicationService({artifactResolver:tampered.resolver,signatureVerifier:tampered.verifier,replayTrust:tampered.replayTrust});await expect(service.inspect({verificationContractVersion:"verification.v1",auditBundle:{artifactId:tampered.auditArtifact.artifactId,digest:tampered.auditArtifact.digest}},context)).rejects.toThrow("VERIFICATION_AUDIT_INSPECTION_REPLAY_FAILURE");});
  it("returns safe typed request, version, and bundle-corruption failures",async()=>{const value=await fixture(),service=new VerificationAuditInspectionApplicationService({artifactResolver:value.resolver,signatureVerifier:value.verifier,replayTrust:value.replayTrust});const unsupported=service.inspect({verificationContractVersion:"verification.v2",auditBundle:{artifactId:value.auditArtifact.artifactId,digest:value.auditArtifact.digest}},context);await expect(unsupported).rejects.toMatchObject({code:"VERIFICATION_AUDIT_INSPECTION_UNSUPPORTED_VERSION",message:"VERIFICATION_AUDIT_INSPECTION_UNSUPPORTED_VERSION"});const bytes=new TextEncoder().encode(canonicalizeJson({schemaVersion:"not-an-audit"})),artifact={...value.auditArtifact,digest:sha256Digest(bytes),byteLength:bytes.byteLength};value.values.set(artifact.artifactId,{registration:artifact,bytes});const corrupt=service.inspect({verificationContractVersion:"verification.v1",auditBundle:{artifactId:artifact.artifactId,digest:artifact.digest}},context);await expect(corrupt).rejects.toBeInstanceOf(VerificationAuditInspectionError);await expect(corrupt).rejects.toThrow("VERIFICATION_AUDIT_INSPECTION_BUNDLE_CORRUPT");expect(value.replayTrust.resolve).not.toHaveBeenCalled();});
  it("cancels a stalled replay hydration and propagates abort to the resolver",async()=>{const value=await fixture(),sourceId=value.audit.verificationBundle.captures[0]!.contentArtifact.artifactId;let started!:()=>void,resolverAborted=false;const replayHydrationStarted=new Promise<void>(resolve=>{started=resolve;});const resolver={authorizeArtifact:value.resolver.authorizeArtifact,hydrateRegisteredArtifact:async(input:{tenantId:string;artifactId:string;signal:AbortSignal})=>{if(input.artifactId===sourceId){started();return new Promise<never>((_resolve,reject)=>input.signal.addEventListener("abort",()=>{resolverAborted=true;reject(new Error("RESOLVER_ABORTED"));},{once:true}));}return value.resolver.hydrateRegisteredArtifact(input);}};const service=new VerificationAuditInspectionApplicationService({artifactResolver:resolver,signatureVerifier:value.verifier,replayTrust:value.replayTrust,maximumInspectionMs:1_000}),controller=new AbortController(),pending=service.inspect({verificationContractVersion:"verification.v1",auditBundle:{artifactId:value.auditArtifact.artifactId,digest:value.auditArtifact.digest}},context,controller.signal);await replayHydrationStarted;controller.abort();await expect(pending).rejects.toThrow("VERIFICATION_AUDIT_INSPECTION_CANCELLED");expect(resolverAborted).toBe(true);});
  it("enforces the inspection deadline during stalled replay hydration",async()=>{const value=await fixture(),sourceId=value.audit.verificationBundle.captures[0]!.contentArtifact.artifactId;let resolverAborted=false;const resolver={authorizeArtifact:value.resolver.authorizeArtifact,hydrateRegisteredArtifact:async(input:{tenantId:string;artifactId:string;signal:AbortSignal})=>input.artifactId===sourceId?new Promise<never>((_resolve,reject)=>input.signal.addEventListener("abort",()=>{resolverAborted=true;reject(new Error("RESOLVER_ABORTED"));},{once:true})):value.resolver.hydrateRegisteredArtifact(input)},service=new VerificationAuditInspectionApplicationService({artifactResolver:resolver,signatureVerifier:value.verifier,replayTrust:value.replayTrust,maximumInspectionMs:10});await expect(service.inspect({verificationContractVersion:"verification.v1",auditBundle:{artifactId:value.auditArtifact.artifactId,digest:value.auditArtifact.digest}},context)).rejects.toThrow("VERIFICATION_AUDIT_INSPECTION_TIMEOUT");expect(resolverAborted).toBe(true);});
});

it("passes server-resolved semantic replay through signed public inspection",async()=>{
 const value=await fixture(true,true),request={verificationContractVersion:"verification.v1",auditBundle:{artifactId:value.auditArtifact.artifactId,digest:value.auditArtifact.digest}};
 const unsupported=new VerificationAuditInspectionApplicationService({artifactResolver:value.resolver,signatureVerifier:value.verifier,replayTrust:value.replayTrust});
 await expect(unsupported.inspect(request,context)).rejects.toThrow("VERIFICATION_AUDIT_INSPECTION_REPLAY_FAILURE");
 const replay=vi.fn(async(input:import("@aiengineer/knowledge-verification").VerificationSemanticReplayPort extends {replay(input:infer T):unknown}?T:never)=>({assessments:input.recordedPolicyInputs.assertions.map(item=>item.semantic),replayedArtifactIds:[value.audit.verificationBundle.captures[0]!.contentArtifact.artifactId]}));
 const service=new VerificationAuditInspectionApplicationService({artifactResolver:value.resolver,signatureVerifier:value.verifier,replayTrust:{async resolve(){return {runtimePrincipals:value.prototype.runtimePrincipals,semanticReplay:{replay}};}}});
 const result=await service.inspect(request,context);expect(result.proof.policyReplay).toBe("exact");expect(replay).toHaveBeenCalledOnce();
});
