import { describe,expect,it } from "vitest";
import { VerificationAuditInspectionGrantCatalog } from "./verification-audit-inspection-grants.js";
import { VerificationAuditInspectionReadError,VerificationAuditInspectionReadService } from "./verification-audit-inspection-reads.js";
import { sha256Digest } from "@aiengineer/knowledge-verification";

const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`,tenant=id(1),operationId=id(2),digest=sha256Digest("audit"),at="2026-09-07T00:00:00.000Z";
const output={schemaVersion:"verification-audit-inspection.v1",verificationContractVersion:"verification.v1",auditArtifact:{artifactId:id(3),digest,mediaType:"application/vnd.aiengineer.verification-run-manifest+json",sizeBytes:12},run:{runId:id(4),manifestId:id(5),manifestDigest:sha256Digest("m"),deterministicResultDigest:sha256Digest("d"),policyDecisionDigest:sha256Digest("p"),policyOutcome:"review",startedAt:at,completedAt:at},proof:{payloadDigest:sha256Digest("x"),signatureStatus:"verified",deterministicReplay:"exact",policyReplay:"exact",replayedArtifactCount:3,inputArtifactCount:1,outputArtifactCount:2}};
const handle={artifactId:id(6),tenantId:tenant,digest:sha256Digest("result"),mediaType:"application/json",byteLength:1,objectKey:"secret/object",createdAt:at,producerActivityId:"p",producerVersion:"v",encryptionClass:"managed",retentionClass:"audit",dataClassification:"restricted",parentArtifactIds:[id(3)]};
describe("audit inspection public custody",()=>{
  it("admits only an exact claims/report artifact grant",()=>{const catalog=new VerificationAuditInspectionGrantCatalog([{tenantId:tenant,auditArtifact:{artifactId:id(3),digest},runKind:"report"}]);expect(catalog.resolve(tenant,{verificationContractVersion:"verification.v1",auditBundle:{artifactId:id(3),digest}}).runKind).toBe("report");expect(catalog.admits(tenant,{verificationContractVersion:"verification.v1",auditBundle:{artifactId:id(3),digest:sha256Digest("other")}})).toBe(false);expect(()=>new VerificationAuditInspectionGrantCatalog([{tenantId:tenant,auditArtifact:{artifactId:id(3),digest},runKind:"metric"}])).toThrow();});
  it("returns a sanitized strict resource and maps non-success states",async()=>{const result={schemaVersion:"verification-operation-result.v1",operationId,useCase:"inspectAuditBundle",requestDigest:sha256Digest("request"),output,resultArtifact:handle};const service=new VerificationAuditInspectionReadService({loadVerifiedInspection:async()=>({state:"succeeded",result})});const value=await service.getInspection({tenantId:tenant,operationId});expect(value.resultArtifact).toEqual({artifactId:handle.artifactId,digest:handle.digest});expect(JSON.stringify(value)).not.toContain("secret/object");for(const state of ["pending","failed","cancelled"] as const){const failed=new VerificationAuditInspectionReadService({loadVerifiedInspection:async()=>({state})});await expect(failed.getInspection({tenantId:tenant,operationId})).rejects.toBeInstanceOf(VerificationAuditInspectionReadError);}});
});
