import { describe, expect, it, vi } from "vitest";
import { VerificationDriftRevalidationPlanner, semanticObservationDrift } from "./verification-drift-revalidation.js";
const value=(extra:Record<string,unknown>={})=>({tenantId:"11111111-1111-4111-8111-111111111111",observationArtifactId:"22222222-2222-4222-8222-222222222222",observationDigest:`sha256:${"a".repeat(64)}` as const,sourceOperationId:"33333333-3333-4333-8333-333333333333",dimensions:["policy","model"] as const,disposition:"revalidate" as const,...extra});
describe("VerificationDriftRevalidationPlanner",()=>{
 it("commits one normalized atomic plan",async()=>{const persistPlan=vi.fn().mockResolvedValue("planned");await expect(new VerificationDriftRevalidationPlanner({persistPlan}).plan(value())).resolves.toBe("planned");expect(persistPlan).toHaveBeenCalledWith(expect.objectContaining({dimensions:["model","policy"],disposition:"revalidate"}));});
 it("does not leave an application claim after a failed durable transaction",async()=>{const persistPlan=vi.fn().mockRejectedValueOnce(new Error("DB_DOWN")).mockResolvedValueOnce("planned");const planner=new VerificationDriftRevalidationPlanner({persistPlan});await expect(planner.plan(value())).rejects.toThrow("DB_DOWN");await expect(planner.plan(value())).resolves.toBe("planned");expect(persistPlan).toHaveBeenCalledTimes(2);});
 it("fails closed for untrusted dimension values",async()=>{const persistPlan=vi.fn();await expect(new VerificationDriftRevalidationPlanner({persistPlan}).plan(value({dimensions:["unknown"]}))).rejects.toThrow("DRIFT_REVALIDATION_INPUT_INVALID");expect(persistPlan).not.toHaveBeenCalled();});
 it("routes explicit ineligible policy to review and does not invent provider drift",async()=>{const persistPlan=vi.fn().mockResolvedValue("planned"),planner=new VerificationDriftRevalidationPlanner({persistPlan});await expect(planner.plan(value({disposition:"review_required"}))).rejects.toThrow("DRIFT_REVALIDATION_INPUT_INVALID");await planner.plan(value({disposition:"review_required",reviewReason:"BUDGET_NOT_ADMITTED"}));expect(persistPlan).toHaveBeenCalledWith(expect.objectContaining({disposition:"review_required"}));expect(semanticObservationDrift({...value(),context:{operationId:value().sourceOperationId},observationArtifact:{artifactId:value().observationArtifactId,digest:value().observationDigest},revalidationRequired:true,modelStatus:"missing"})).toMatchObject({dimensions:["model"]});});
});
